import { CurriculumTopicBank } from './types';

export const BUSINESS_ENGLISH_BANK: CurriculumTopicBank = {
  key: 'BUSINESS_ENGLISH',
  tenChuDe: 'Từ Vựng Tiếng Anh Công Sở & Giao Tiếp (Business English)',
  aliases: [
    'công sở',
    'cong so',
    'business english',
    'business',
    'giao tiếp công sở',
    'tiếng anh thương mại',
    'kinh doanh',
    'doanh nghiệp',
    'thương mại',
    'đàm phán',
    'hợp đồng',
    'meeting',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'Please review the attached meeting __________ thoroughly prior to our quarterly budget conference.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'agenda', B: 'receipt', C: 'brochure', D: 'syllabus' },
      dapAnDung: 'A',
      giaiThich: '"Agenda" là chương trình nghị sự, lịch trình các nội dung cần thảo luận trong cuộc họp.',
    },
    {
      id: 2,
      noiDung: 'After intense negotiation sessions, both corporations successfully reached a mutually beneficial __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'compromise', B: 'complaint', C: 'conflict', D: 'competition' },
      dapAnDung: 'A',
      giaiThich: '"Reach a compromise" là cụm từ thương mại chỉ việc đạt được thỏa hiệp, đồng thuận.',
    },
    {
      id: 3,
      noiDung: 'The customer service director presented an innovative strategy to boost long-term client __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'retention', B: 'rejection', C: 'reduction', D: 'reaction' },
      dapAnDung: 'A',
      giaiThich: '"Client / Customer retention" là thuật ngữ quản trị kinh doanh chỉ việc giữ chân và duy trì khách hàng trung thành.',
    },
    {
      id: 4,
      noiDung: 'All staff members are strictly mandated to abide by the corporation\'s professional code of __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'conduct', B: 'action', C: 'affair', D: 'manner' },
      dapAnDung: 'A',
      giaiThich: '"Code of conduct" nghĩa là quy tắc ứng xử / chuẩn mực đạo đức nghề nghiệp.',
    },
    {
      id: 5,
      noiDung: 'The enterprise reported a 18% increase in its quarterly net __________ following international market expansion.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'profit', B: 'loss', C: 'debt', D: 'deficit' },
      dapAnDung: 'A',
      giaiThich: '"Net profit" nghĩa là lợi nhuận ròng sau khi đã trừ toàn bộ chi phí và thuế.',
    },
    {
      id: 6,
      noiDung: 'To secure the venture capital funding, the founders delivered a compelling 10-minute investor __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'pitch', B: 'catch', C: 'throw', D: 'drop' },
      dapAnDung: 'A',
      giaiThich: '"Investor pitch" (bài thuyết trình gọi vốn đầu tư của startup trước các quỹ mạo hiểm).',
    },
    {
      id: 7,
      noiDung: 'Due to severe supply chain disruptions, we unfortunately cannot meet the strict project __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'deadline', B: 'headline', C: 'baseline', D: 'guideline' },
      dapAnDung: 'A',
      giaiThich: '"Meet the deadline" là cụm từ chỉ việc hoàn thành công việc đúng thời hạn chót.',
    },
    {
      id: 8,
      noiDung: 'A detailed feasibility study was conducted to evaluate the potential return on __________ (ROI).',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'investment', B: 'invention', C: 'invitation', D: 'inflation' },
      dapAnDung: 'A',
      giaiThich: 'ROI là viết tắt của "Return on Investment" (tỷ suất hoàn vốn đầu tư).',
    },
    {
      id: 9,
      noiDung: 'Our company has decided to __________ non-core accounting and payroll functions to a specialized agency.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'outsource', B: 'downsize', C: 'bankrupt', D: 'liquidate' },
      dapAnDung: 'A',
      giaiThich: '"Outsource" nghĩa là thuê ngoài các dịch vụ phụ trợ từ đơn vị thứ ba.',
    },
    {
      id: 10,
      noiDung: 'The CEO emphasized that our long-term competitive advantage lies in continuous technological __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'innovation', B: 'stagnation', C: 'limitation', D: 'deterioration' },
      dapAnDung: 'A',
      giaiThich: '"Innovation" (sự đổi mới sáng tạo) là yếu tố sống còn cho năng lực cạnh tranh doanh nghiệp.',
    },
    {
      id: 11,
      noiDung: 'Key project __________ including department heads and client representatives must attend the kickoff.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'stakeholders', B: 'stockbrokers', C: 'caretakers', D: 'shareholders' },
      dapAnDung: 'A',
      giaiThich: '"Stakeholders" (các bên liên quan trực tiếp đến dự án như đối tác, khách hàng, nhân sự).',
    },
    {
      id: 12,
      noiDung: 'The human resources team conducted an extensive annual employee performance __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'appraisal', B: 'approval', C: 'approach', D: 'appeal' },
      dapAnDung: 'A',
      giaiThich: '"Performance appraisal" nghĩa là đánh giá hiệu suất công việc định kỳ của nhân viên.',
    },
    {
      id: 13,
      noiDung: 'Could you please send me the revised price __________ before we sign the procurement agreement?',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'quotation', B: 'equation', C: 'question', D: 'recitation' },
      dapAnDung: 'A',
      giaiThich: '"Price quotation" (bản báo giá chính thức trong giao dịch thương mại).',
    },
    {
      id: 14,
      noiDung: 'The two pharmaceutical giants merged to achieve greater market __________ and operational efficiency.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'C1',
      luaChon: { A: 'synergy', B: 'apathy', C: 'discord', D: 'friction' },
      dapAnDung: 'A',
      giaiThich: '"Synergy" (sức mạnh cộng hưởng từ việc hợp nhất hai doanh nghiệp).',
    },
    {
      id: 15,
      noiDung: 'During the global recession, management had to implement cost-cutting measures to maintain healthy cash __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'flow', B: 'drop', C: 'leak', D: 'tide' },
      dapAnDung: 'A',
      giaiThich: '"Cash flow" (dòng tiền của doanh nghiệp).',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'The term "B2B" stands for "Business-to-Business", representing commercial transactions between two companies.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. B2B (Business-to-Business) chỉ mô hình kinh doanh giữa doanh nghiệp với doanh nghiệp.',
    },
    {
      id: 17,
      noiDung: 'A Non-Disclosure Agreement (NDA) is an open marketing brochure distributed freely to prospective clients.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. NDA (Non-Disclosure Agreement) là thỏa thuận bảo mật thông tin pháp lý bắt buộc, không phải tờ rơi quảng cáo.',
    },
    {
      id: 18,
      noiDung: 'A "brainstorming" session encourages participants to generate a wide variety of ideas without immediate criticism.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Brainstorming (động não) nhằm khuyến khích mọi ý tưởng tự do và sáng tạo trước khi sàng lọc.',
    },
    {
      id: 19,
      noiDung: '"Cold calling" involves contacting prospective customers who have already expressed clear interest in buying.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Cold calling" là gọi điện tiếp thị cho khách hàng tiềm năng chưa từng có tương tác hoặc liên hệ trước đó.',
    },
    {
      id: 20,
      noiDung: 'The phrase "to touch base with someone" means to briefly make contact or update them on a situation.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Touch base" là thành ngữ công sở phổ biến nghĩa là liên lạc ngắn gọn để cập nhật thông tin.',
    },
    {
      id: 21,
      noiDung: 'Gross revenue refers to total business income before deducting expenses, taxes, and production costs.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Doanh thu gộp (Gross revenue) là tổng thu nhập trước khi trừ chi phí (phân biệt với Net profit).',
    },
    {
      id: 22,
      noiDung: 'In professional business emails, using aggressive ALL CAPS indicates superior executive leadership and politeness.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Viết hoa toàn bộ (ALL CAPS) trong email được coi là hành vi la hét, thiếu lịch sự và thiếu chuyên nghiệp.',
    },
    {
      id: 23,
      noiDung: 'A Memorandum of Understanding (MOU) is a formal document outlining bilateral terms between cooperating entities.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. MOU (Biên bản ghi nhớ) xác lập thỏa thuận hợp tác ban đầu giữa các đối tác.',
    },
    {
      id: 24,
      noiDung: 'Corporate Social Responsibility (CSR) refers to a company integrating social and environmental concerns into its business operations.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. CSR là trách nhiệm xã hội của doanh nghiệp đối với cộng đồng và môi trường.',
    },
    {
      id: 25,
      noiDung: '"Benchmarking" is the process of comparing a business\'s processes and performance metrics to industry bests.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Benchmarking là việc so sánh các chỉ số hiệu quả của doanh nghiệp với các đối thủ hàng đầu trong ngành.',
    },
    {
      id: 26,
      noiDung: 'The closing sign-off "Yours faithfully" is used when you know the recipient\'s name personally (e.g., Dear Mr. Smith).',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Yours faithfully" dùng khi mở đầu thư bằng "Dear Sir/Madam" (không biết tên). Khi biết tên (Dear Mr. Smith), dùng "Yours sincerely".',
    },
    {
      id: 27,
      noiDung: '"Liquid assets" are assets that can be quickly and easily converted into cash with minimal loss of value.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Tài sản thanh khoản (Liquid assets) là tài sản dễ dàng quy đổi thành tiền mặt (như tiền gửi ngân hàng).',
    },
    {
      id: 28,
      noiDung: 'An invoice is a formal commercial document issued by a seller to a buyer relating to a sale transaction, indicating quantities and costs.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Hóa đơn (Invoice) là chứng từ yêu cầu thanh toán do người bán phát hành cho người mua.',
    },
    {
      id: 29,
      noiDung: '"Whistleblowing" refers to an employee reporting illegal, unethical, or dangerous activities occurring inside an organization.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'C1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Whistleblowing (tố giác sai phạm nội bộ) bảo vệ tính minh bạch và tuân thủ pháp luật.',
    },
    {
      id: 30,
      noiDung: 'In business idioms, "thinking outside the box" means sticking strictly to traditional conventional rules.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Think outside the box" nghĩa là suy nghĩ sáng tạo, phá cách, vượt ra khỏi những lối mòn truyền thống.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which of the following are formal sign-offs in professional business correspondence? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Best regards',
        B: 'Sincerely yours',
        C: 'See ya later buddy',
        D: 'Yours faithfully',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Best regards, Sincerely yours, Yours faithfully là lời kết thư trang trọng. C là khẩu ngữ thân mật không dùng trong email công sở.',
    },
    {
      id: 32,
      noiDung: 'Which acronyms represent executive C-level management positions? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'CEO (Chief Executive Officer)',
        B: 'CFO (Chief Financial Officer)',
        C: 'CTO (Chief Technology Officer)',
        D: 'FAQ (Frequently Asked Questions)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'CEO, CFO, CTO là các chức danh lãnh đạo cấp cao trong hội đồng quản trị công ty.',
    },
    {
      id: 33,
      noiDung: 'Which terms directly relate to corporate finance and balance sheets? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Assets (Tài sản)',
        B: 'Liabilities (Nợ phải trả)',
        C: 'Equity (Vốn chủ sở hữu)',
        D: 'Popcorn consumption',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Assets = Liabilities + Equity là phương trình kế toán cơ bản trong bảng cân đối kế toán.',
    },
    {
      id: 34,
      noiDung: 'Which idioms are commonly used in business meetings to describe progress or agreement? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'On the same page (đồng thuận ý kiến)',
        B: 'In the loop (được cập nhật thông tin liên tục)',
        C: 'Touch base (trao đổi nhanh)',
        D: 'Bite the dust (thất bại hoàn toàn)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'On the same page, In the loop, Touch base là các thành ngữ kinh doanh rất tích cực và phổ biến.',
    },
    {
      id: 35,
      noiDung: 'Which strategies help maintain professional telephone etiquette in an office? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Stating your name and department clearly when answering',
        B: 'Listening actively without interrupting the caller',
        C: 'Leaving callers on hold indefinitely without warning',
        D: 'Summarizing key action items before ending the call',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là chuẩn mực giao tiếp qua điện thoại chuyên nghiệp. Để người gọi chờ vô thời hạn (C) là hành vi thiếu tôn trọng.',
    },
    {
      id: 36,
      noiDung: 'Which documents are formally utilized during a procurement and vendor selection process? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'RFP (Request for Proposal)',
        B: 'RFQ (Request for Quotation)',
        C: 'Purchase Order (PO)',
        D: 'Personal diary',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'RFP, RFQ, PO là các tài liệu mua sắm và đấu thầu thương mại tiêu chuẩn.',
    },
    {
      id: 37,
      noiDung: 'Select all essential elements typically included in a formal meeting agenda: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Meeting objectives and topics of discussion',
        B: 'Allocated time per topic and session chairs',
        C: 'Action items and expected deliverables',
        D: 'The favorite hobbies of the receptionist',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Mục tiêu, phân bổ thời gian và đầu việc hành động là cốt lõi của một agenda chuyên nghiệp.',
    },
    {
      id: 38,
      noiDung: 'Which phrases are polite ways to disagree in a business meeting? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'I see your point, however, we must also consider the budget constraints.',
        B: 'I am afraid I have a slightly different perspective on this matter.',
        C: 'You are completely wrong and making no sense at all.',
        D: 'While I appreciate that idea, my concern revolves around delivery timelines.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là cách phản biện lịch sự, xây dựng và ngoại giao trong môi trường chuyên nghiệp.',
    },
    {
      id: 39,
      noiDung: 'Which terms describe different marketing channels and promotional methods? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Search Engine Optimization (SEO)',
        B: 'Pay-Per-Click (PPC) Advertising',
        C: 'Content Marketing',
        D: 'Thermal Insulation Foam',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'SEO, PPC và Content Marketing là các phương thức tiếp thị kỹ thuật số cốt lõi.',
    },
    {
      id: 40,
      noiDung: 'Select all indicators of positive workplace engagement and corporate culture: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Low employee turnover rate',
        B: 'Open horizontal and vertical communication',
        C: 'Encouragement of continuous learning and training',
        D: 'Frequent unpaid compulsory overtime without consent',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Tỷ lệ nghỉ việc thấp (A), giao tiếp cởi mở (B) và văn hóa học tập (C) là biểu hiện của môi trường làm việc lý tưởng.',
    },
    {
      id: 41,
      noiDung: 'Which components are fundamental in a standard business proposal? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Executive Summary',
        B: 'Problem statement and proposed solution',
        C: 'Cost estimate and milestone schedule',
        D: 'Astrological birth chart of the project manager',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Tóm tắt điều hành, giải pháp đề xuất và chi phí/tiến độ là 3 phần bắt buộc của bản đề xuất kinh doanh.',
    },
    {
      id: 42,
      noiDung: 'Which terms describe modern employment contracts or working arrangements? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Remote working / Telecommuting',
        B: 'Hybrid model',
        C: 'Flexible working hours (Flextime)',
        D: 'Centrifugal acceleration',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Làm việc từ xa (A), mô hình kết hợp (B), giờ giấc linh hoạt (C) là các chế độ lao động hiện đại.',
    },
    {
      id: 43,
      noiDung: 'Which verbs are commonly paired with "contract" in business English? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Sign a contract',
        B: 'Breach a contract (vi phạm)',
        C: 'Terminate a contract (chấm dứt)',
        D: 'Bake a contract',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Sign, Breach, Terminate là các động từ kết hợp tự nhiên (collocations) với danh từ contract.',
    },
    {
      id: 44,
      noiDung: 'Select all appropriate email greetings for someone whose name is known: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Dear Ms. Johnson,',
        B: 'Dear Dr. Robinson,',
        C: 'To whom it may concern,',
        D: 'Good morning Peter,',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là lời chào khi đã biết danh tính người nhận. C dùng khi không biết cụ thể người nhận là ai.',
    },
    {
      id: 45,
      noiDung: 'Which attributes define an effective professional presentation? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Clear structure with introduction, body, and conclusion',
        B: 'Visually balanced slides with concise bullet points',
        C: 'Reading long paragraphs directly from the screen with back turned to the audience',
        D: 'Engaging eye contact and interactive Q&A session',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Cấu trúc mạch lạc (A), slide cô đọng (B) và giao lưu ánh mắt/hỏi đáp (D) là các kỹ năng thuyết trình xuất sắc. Quay lưng đọc chữ (C) là lỗi cấm kỵ.',
    },
  ],
};
