import { CurriculumTopicBank } from './types';

export const COMPARATIVES_BANK: CurriculumTopicBank = {
  key: 'COMPARATIVES',
  tenChuDe: 'So Sánh Hơn & So Sánh Nhất (Comparatives & Superlatives)',
  aliases: [
    'so sánh',
    'so sanh',
    'comparative',
    'comparatives',
    'superlative',
    'superlatives',
    'so sánh hơn',
    'so sánh nhất',
    'so sánh kép',
    'the more the more',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'The newly developed electric engine is significantly __________ than the previous diesel model.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'more efficient', B: 'most efficient', C: 'efficienter', D: 'as efficient' },
      dapAnDung: 'A',
      giaiThich: '"Efficient" là tính từ dài có 3 âm tiết, dạng so sánh hơn là "more efficient + than".',
    },
    {
      id: 2,
      noiDung: 'Mount Everest is the __________ mountain peak on planet Earth.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'highest', B: 'higher', C: 'most high', D: 'more higher' },
      dapAnDung: 'A',
      giaiThich: '"High" là tính từ ngắn 1 âm tiết, so sánh nhất là "the highest".',
    },
    {
      id: 3,
      noiDung: 'The __________ you practice speaking English with native speakers, the __________ fluent you will become.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'more / more', B: 'most / most', C: 'many / much', D: 'better / best' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc so sánh kép (Double comparative): "The + comparative ..., the + comparative ...".',
    },
    {
      id: 4,
      noiDung: 'His performance during the second interview was far __________ than his initial presentation.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'better', B: 'gooder', C: 'best', D: 'more good' },
      dapAnDung: 'A',
      giaiThich: '"Good" là tính từ bất quy tắc: good - better - the best.',
    },
    {
      id: 5,
      noiDung: 'That was by far the __________ film I have ever watched at an international cinema festival.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'most captivating', B: 'more captivating', C: 'captivatingest', D: 'so captivating' },
      dapAnDung: 'A',
      giaiThich: '"By far the + superlative" dùng để nhấn mạnh so sánh nhất (vượt trội hơn hẳn tất cả).',
    },
    {
      id: 6,
      noiDung: 'Traveling by high-speed bullet train is not __________ expensive as taking a commercial flight.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'as', B: 'than', C: 'more', D: 'like' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc so sánh ngang bằng / không bằng: "not as / not so + adj + as".',
    },
    {
      id: 7,
      noiDung: 'The weather in the southern delta is becoming __________ and hotter as summer approaches.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'hotter', B: 'more hot', C: 'hottest', D: 'as hot' },
      dapAnDung: 'A',
      giaiThich: 'So sánh càng ngày càng... với tính từ ngắn: "adj-er and adj-er" (hotter and hotter).',
    },
    {
      id: 8,
      noiDung: 'Of the two candidate proposals submitted, the board selected the __________ innovative one.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'more', B: 'most', C: 'much', D: 'best' },
      dapAnDung: 'A',
      giaiThich: 'Khi so sánh giữa ĐÚNG HAI đối tượng ("Of the two..."), ta dùng "the + comparative" ("the more innovative one").',
    },
    {
      id: 9,
      noiDung: 'The traffic congestion in this metropolitan city is getting worse and __________ every year.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'worse', B: 'badder', C: 'worst', D: 'more bad' },
      dapAnDung: 'A',
      giaiThich: 'Tính từ bất quy tắc "bad" có so sánh hơn là "worse" (worse and worse: ngày càng tệ hơn).',
    },
    {
      id: 10,
      noiDung: 'Can you please drive a little __________? We are approaching an elementary school zone.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'more slowly', B: 'slowlier', C: 'slowest', D: 'most slowly' },
      dapAnDung: 'A',
      giaiThich: 'Trạng từ tận cùng bằng "-ly" (slowly) có dạng so sánh hơn là "more slowly".',
    },
    {
      id: 11,
      noiDung: 'This luxury leather handbag costs three times as __________ as the synthetic canvas bag.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'much', B: 'more', C: 'many', D: 'most' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc so sánh bội số (gấp bao nhiêu lần): "multiple (three times) + as much/many as". Giá cả dùng "as much as".',
    },
    {
      id: 12,
      noiDung: 'For further details regarding the scholarship, please visit our __________ information counter.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'nearest', B: 'nearer', C: 'most near', D: 'next' },
      dapAnDung: 'A',
      giaiThich: '"Nearest" (gần nhất về mặt khoảng cách không gian vật lý).',
    },
    {
      id: 13,
      noiDung: 'The cost of living in Tokyo is much higher than __________ in rural Hokkaido.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'that', B: 'this', C: 'those', D: 'it' },
      dapAnDung: 'A',
      giaiThich: 'Dùng đại từ "that" để thay thế cho danh từ không đếm được ("The cost of living") tránh lặp từ trong câu so sánh.',
    },
    {
      id: 14,
      noiDung: 'She is easily the __________ qualified surgeon in the entire cardiovascular department.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'most', B: 'more', C: 'much', D: 'best' },
      dapAnDung: 'A',
      giaiThich: '"Easily the most + adjective" dùng để nhấn mạnh vị trí số một tuyệt đối, không bàn cãi.',
    },
    {
      id: 15,
      noiDung: 'He is senior __________ me by three years in terms of corporate service tenure.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'to', B: 'than', C: 'from', D: 'with' },
      dapAnDung: 'A',
      giaiThich: 'Các tính từ gốc Latinh tận cùng bằng "-ior" (senior, junior, superior, inferior) đi với giới từ "TO", không dùng "than".',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'Two-syllable adjectives ending in "-y" (like "happy", "busy", "easy") form their comparative by changing "-y" to "-ier".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Tính từ 2 âm tiết kết thúc bằng đuôi "-y" đổi thành "-ier" (happier, busier, easier).',
    },
    {
      id: 17,
      noiDung: 'The comparative form of "bad" is "badder".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Bad" là tính từ bất quy tắc: bad -> worse -> worst.',
    },
    {
      id: 18,
      noiDung: 'In the double comparative structure "the more..., the more...", both clauses must begin with the definite article "the".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Cấu trúc so sánh kép bắt buộc cả 2 vế đều bắt đầu bằng "The + so sánh hơn" (The more you learn, the wiser you become).',
    },
    {
      id: 19,
      noiDung: 'Latin comparatives ending in "-ior" such as "superior", "inferior", "senior", and "junior" are followed by "than".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Các tính từ Latinh như superior, junior, senior luôn đi kèm với giới từ "TO", tuyệt đối không dùng "than".',
    },
    {
      id: 20,
      noiDung: 'We can use words like "much", "far", "a lot", "significantly" to modify and strengthen comparative adjectives.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Much / Far / Significantly / Considerably / A lot + comparative dùng để nhấn mạnh mức độ chênh lệch lớn.',
    },
    {
      id: 21,
      noiDung: '"Farther" and "further" can both be used for physical distance, but only "further" can mean "additional" or "more".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Cả 2 đều chỉ khoảng cách địa lý, nhưng chỉ "further" mới mang nghĩa thông tin thêm, sâu hơn (further details).',
    },
    {
      id: 22,
      noiDung: 'The superlative form of "clever" can be either "cleverest" or "most clever".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Một số tính từ 2 âm tiết (clever, simple, narrow, quiet) chấp nhận cả 2 dạng: đuôi -est hoặc most.',
    },
    {
      id: 23,
      noiDung: 'The sentence "He is more taller than his brother" is grammatically correct and standard.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Đây là lỗi so sánh hơn trùng lặp (double comparative error); "tall" là tính từ ngắn nên chỉ dùng "taller than", không thêm "more".',
    },
    {
      id: 24,
      noiDung: 'When comparing two persons or things, standard traditional grammar uses the comparative degree, not the superlative.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. So sánh giữa 2 đối tượng ta dùng so sánh hơn (e.g., "the taller of the two brothers"), so sánh từ 3 đối tượng trở lên mới dùng so sánh nhất.',
    },
    {
      id: 25,
      noiDung: '"As... as" can enclose both adjectives and adverbs in their positive (base) degree.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "As + adj/adv nguyên thể + as" (as fast as, as carefully as).',
    },
    {
      id: 26,
      noiDung: 'The superlative of "little" when referring to amount is "least".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Bảng so sánh bất quy tắc: little -> less -> the least.',
    },
    {
      id: 27,
      noiDung: 'One-syllable adjectives ending in a single vowel and a single consonant (like "big", "thin") double the final consonant in comparative forms.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Big -> bigger, Thin -> thinner, Hot -> hotter (gấp đôi phụ âm cuối trước khi thêm -er/-est).',
    },
    {
      id: 28,
      noiDung: '"Elder" and "eldest" can be followed directly by "than" (e.g., "My sister is elder than me").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Elder" chỉ đứng trước danh từ để chỉ thứ bậc trong gia đình (my elder brother); khi có "than", bắt buộc phải dùng "older than".',
    },
    {
      id: 29,
      noiDung: 'Modifiers like "slightly", "a bit", "a little" indicate small differences in comparative sentences.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Slightly / A bit / A little + comparative diễn tả mức độ chênh lệch ít.',
    },
    {
      id: 30,
      noiDung: 'Absolute adjectives like "unique", "perfect", and "dead" are universally encouraged to take comparative forms like "more unique".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'C1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Các tính từ mang nghĩa tuyệt đối (unique, perfect, dead, square) theo ngữ pháp chuẩn mực không có cấp độ so sánh hơn kém.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which of the following adjectives have IRREGULAR comparative and superlative forms? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Good (better, best)',
        B: 'Bad (worse, worst)',
        C: 'Far (farther/further, farthest/furthest)',
        D: 'Tall (taller, tallest)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Good, Bad, Far là các tính từ bất quy tắc kinh điển. Tall là tính từ theo quy tắc thông thường (+er, +est).',
    },
    {
      id: 32,
      noiDung: 'Which adverbs or phrases can be used to intensify a comparative adjective? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Much (much faster)',
        B: 'Far (far more reliable)',
        C: 'Significantly (significantly higher)',
        D: 'Very (very faster)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Much, Far, Significantly đi với so sánh hơn. "Very" chỉ đi với tính từ nguyên thể (very fast), không đi với so sánh hơn.',
    },
    {
      id: 33,
      noiDung: 'Which two-syllable adjectives can form their comparative with EITHER "-er" OR "more"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Quiet (quieter / more quiet)',
        B: 'Simple (simpler / more simple)',
        C: 'Clever (cleverer / more clever)',
        D: 'Recent (recenter / more recent)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Quiet, Simple, Clever chấp nhận cả 2 dạng so sánh. "Recent" chỉ có một dạng duy nhất là "more recent".',
    },
    {
      id: 34,
      noiDung: 'Select all grammatically correct double comparative sentences: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The more you study, the higher your test scores will be.',
        B: 'The harder we work, the sooner we will finish.',
        C: 'The more expensive the hotel, the better the service.',
        D: 'The more you study, higher your test scores will be.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C đúng cấu trúc The + comparative, the + comparative. D sai vì vế sau thiếu mạo từ "the".',
    },
    {
      id: 35,
      noiDung: 'Which phrases indicate equality or near-equality in comparisons? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'As skilled as',
        B: 'The same as',
        C: 'Just as fast as',
        D: 'More slower than',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'As skilled as, The same as, Just as fast as là các cấu trúc so sánh bằng. D là câu sai ngữ pháp.',
    },
    {
      id: 36,
      noiDung: 'Select all sentences containing double comparative or superlative errors: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'This is the most cheapest airline ticket available.',
        B: 'She is more cleverer than her classmate.',
        C: 'This is the cheapest flight available.',
        D: 'He runs more faster than me.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A (most cheapest), B (more cleverer), D (more faster) là các lỗi trùng lặp so sánh cấm kỵ. C hoàn toàn chuẩn.',
    },
    {
      id: 37,
      noiDung: 'Which of the following demonstrate correct multiple comparisons (so sánh bội số)? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'This apartment is twice as large as my previous one.',
        B: 'The company\'s revenue was three times as high as last quarter.',
        C: 'She earns four times more than her assistant.',
        D: 'He is two times taller than his son.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Twice as large as, three times as high as, four times more than là các cấu trúc so sánh bội số chuẩn. Với "gấp đôi" người ta dùng "twice", không dùng "two times".',
    },
    {
      id: 38,
      noiDung: 'Which Latin comparatives take the preposition "to" instead of "than"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Superior to',
        B: 'Junior to',
        C: 'Prior to',
        D: 'Faster to',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Superior to, Junior to, Prior to đi với "to". "Faster" là từ thuần Anh đi với "than".',
    },
    {
      id: 39,
      noiDung: 'Select all sentences correctly using "that" or "those" to avoid noun repetition in comparative sentences: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'C1',
      luaChon: {
        A: 'The climate of Singapore is hotter than that of London.',
        B: 'The roads in our district are wider than those in the neighboring province.',
        C: 'The quality of these cameras is better than those of the cheap models.',
        D: 'The climate of Singapore is hotter than London.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A dùng "that" thay cho climate. B dùng "those" thay cho roads. C sai vì "The quality" số ít phải dùng "that", không dùng "those". D là lỗi so sánh khập khiễng (so sánh khí hậu với một thành phố).',
    },
    {
      id: 40,
      noiDung: 'Which words indicate a minor difference in comparison? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Slightly',
        B: 'A fraction',
        C: 'A little',
        D: 'Vastly',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Slightly, A fraction, A little chỉ sự chênh lệch nhỏ. "Vastly" chỉ sự khác biệt cực kỳ to lớn.',
    },
    {
      id: 41,
      noiDung: 'Which sentences correctly illustrate continuous progression ("càng ngày càng...")? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The days are getting longer and longer in spring.',
        B: 'Air quality in the city is becoming more and more polluted.',
        C: 'Technology is advancing faster and faster.',
        D: 'The exam is becoming most and most difficult.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Longer and longer, more and more polluted, faster and faster thể hiện sự phát triển tăng dần. D sai ngữ pháp.',
    },
    {
      id: 42,
      noiDung: 'Select all sentences where the superlative is properly constructed: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'She is the most talented pianist in our conservatory.',
        B: 'Tokyo is one of the safest cities in the world.',
        C: 'He is the tallest student in the classroom.',
        D: 'He is tallest student in the classroom.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C có đầy đủ mạo từ "the" và dạng so sánh nhất chuẩn. D sai vì thiếu mạo từ "the".',
    },
    {
      id: 43,
      noiDung: 'Which phrases can emphasize a superlative degree? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'By far the best',
        B: 'Easily the most impressive',
        C: 'Much the tallest',
        D: 'More the best',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'By far the, Easily the, Much the là các phó từ nhấn mạnh cho so sánh nhất. D là cụm từ sai.',
    },
    {
      id: 44,
      noiDung: 'Select all correct comparative forms of "far": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Farther (chỉ khoảng cách vật lý xa hơn)',
        B: 'Further (chỉ khoảng cách vật lý hoặc thông tin sâu hơn)',
        C: 'Farest',
        D: 'More far',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'Far có 2 dạng so sánh hơn là Farther và Further. C và D sai.',
    },
    {
      id: 45,
      noiDung: 'Which of the following demonstrate correct comparisons between two options? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Between these two laptops, the ultrabook is the lighter option.',
        B: 'Of the twin sisters, Clara is the more outgoing.',
        C: 'Between these two laptops, the ultrabook is the lightest option.',
        D: 'He prefers walking to taking the subway.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A và B tuân thủ so sánh giữa 2 đối tượng dùng "the + comparative". D đúng cấu trúc "prefer V-ing to V-ing". C sai vì dùng lightest cho 2 đối tượng.',
    },
  ],
};
