import { CurriculumTopicBank } from './types';

export const CONDITIONALS_BANK: CurriculumTopicBank = {
  key: 'CONDITIONALS',
  tenChuDe: 'Câu Điều Kiện Loại 1, 2, 3 (Conditional Sentences)',
  aliases: [
    'điều kiện',
    'dieu kien',
    'conditional',
    'câu điều kiện',
    'cau dieu kien',
    'if',
    'unless',
    'câu if',
    'cau if',
    'mixed conditional',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'If it rains heavily tomorrow, we __________ the outdoor graduation photo session.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'cancel', B: 'will cancel', C: 'cancelled', D: 'would cancel' },
      dapAnDung: 'B',
      giaiThich: 'Câu điều kiện loại 1 diễn tả sự việc có thể xảy ra ở hiện tại hoặc tương lai: If + S + V(hiện tại đơn), S + will + V-inf.',
    },
    {
      id: 2,
      noiDung: 'If I __________ in your position right now, I would accept that international scholarship without hesitation.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'am', B: 'was', C: 'were', D: 'have been' },
      dapAnDung: 'C',
      giaiThich: 'Câu điều kiện loại 2 giả định điều trái với thực tế ở hiện tại: dùng "were" cho tất cả các ngôi trong mệnh đề If.',
    },
    {
      id: 3,
      noiDung: 'If she had studied more diligently for the entrance exam, she __________ it with flying colors last month.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'would pass', B: 'would have passed', C: 'will pass', D: 'passed' },
      dapAnDung: 'B',
      giaiThich: 'Câu điều kiện loại 3 giả định điều trái thực tế trong quá khứ: If + S + had V3/ed, S + would have V3/ed.',
    },
    {
      id: 4,
      noiDung: 'Water boils if you __________ it to 100 degrees Celsius under standard atmospheric pressure.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'heat', B: 'heats', C: 'heated', D: 'will heat' },
      dapAnDung: 'A',
      giaiThich: 'Câu điều kiện loại 0 (Zero conditional) diễn tả quy luật tự nhiên, chân lý khoa học: cả 2 mệnh đề đều dùng thì Hiện tại đơn.',
    },
    {
      id: 5,
      noiDung: 'Unless you __________ an umbrella, you will get soaked by the tropical storm.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'bring', B: 'don\'t bring', C: 'brought', D: 'will bring' },
      dapAnDung: 'A',
      giaiThich: '"Unless" mang nghĩa phủ định (= If ... not). Mệnh đề đi liền sau unless luôn ở thể khẳng định.',
    },
    {
      id: 6,
      noiDung: 'If I had won that lottery jackpot last year, I __________ in a luxury villa right now.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'would live', B: 'would have lived', C: 'will live', D: 'lived' },
      dapAnDung: 'A',
      giaiThich: 'Câu điều kiện hỗn hợp (Mixed conditional: loại 3 + 2): Giả định quá khứ ("had won") dẫn đến kết quả ở hiện tại ("would live right now").',
    },
    {
      id: 7,
      noiDung: '__________ you require any further assistance, please do not hesitate to contact our customer support desk.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'Should', B: 'Were', C: 'Had', D: 'If' },
      dapAnDung: 'A',
      giaiThich: 'Đảo ngữ câu điều kiện loại 1: "Should + S + V-inf, ...". Mang sắc thái lịch sự, trang trọng.',
    },
    {
      id: 8,
      noiDung: '__________ he known about the hazardous road conditions, he would not have driven late at night.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'Had', B: 'Should', C: 'Were', D: 'Unless' },
      dapAnDung: 'A',
      giaiThich: 'Đảo ngữ câu điều kiện loại 3: "Had + S + V3/ed, S + would have V3/ed".',
    },
    {
      id: 9,
      noiDung: 'Provided that you __________ all company safety regulations, you are permitted to enter the laboratory.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'follow', B: 'will follow', C: 'followed', D: 'would follow' },
      dapAnDung: 'A',
      giaiThich: '"Provided that / As long as" mang nghĩa "miễn là / với điều kiện là" hoạt động như liên từ If ở loại 1.',
    },
    {
      id: 10,
      noiDung: 'If you __________ ice in warm sunlight, it melts rapidly.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'place', B: 'placed', C: 'will place', D: 'had placed' },
      dapAnDung: 'A',
      giaiThich: 'Điều kiện loại 0: sự thật hiển nhiên luôn dùng thì Hiện tại đơn ở cả hai vế.',
    },
    {
      id: 11,
      noiDung: 'If I had enough savings, I __________ a new electric car tomorrow.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'would purchase', B: 'will purchase', C: 'purchased', D: 'have purchased' },
      dapAnDung: 'A',
      giaiThich: 'Điều kiện loại 2: Mệnh đề chính có cấu trúc "would + V-inf".',
    },
    {
      id: 12,
      noiDung: '__________ it not for your timely financial guidance, our startup would have collapsed last quarter.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'C1',
      luaChon: { A: 'Had it been', B: 'Had', C: 'Were', D: 'Should' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc đảo ngữ: "Had it not been for + N, S + would have V3/ed" (Nếu không nhờ có...).',
    },
    {
      id: 13,
      noiDung: 'You can borrow my laptop on condition that you __________ it back by Friday afternoon.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'give', B: 'will give', C: 'gave', D: 'would give' },
      dapAnDung: 'A',
      giaiThich: '"On condition that" (với điều kiện là) đi kèm mệnh đề hiện tại đơn trong câu điều kiện loại 1.',
    },
    {
      id: 14,
      noiDung: 'If the alarm goes off, all building occupants __________ immediately towards the emergency exits.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'must head', B: 'headed', C: 'would head', D: 'had headed' },
      dapAnDung: 'A',
      giaiThich: 'Mệnh đề chính của câu điều kiện loại 1 có thể sử dụng động từ khiếm khuyết (must, should, can) chỉ mệnh lệnh hoặc nghĩa vụ.',
    },
    {
      id: 15,
      noiDung: 'If I were you, I __________ some warm clothing because the temperature drops sharply at night.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'would pack', B: 'will pack', C: 'packed', D: 'pack' },
      dapAnDung: 'A',
      giaiThich: 'Cụm từ quen thuộc đưa ra lời khuyên: "If I were you, I would + V-inf".',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'In conditional sentences, "unless" is equivalent in meaning to "if ... not".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Unless S + V" hoàn toàn tương đương với "If S + do/does/did not + V".',
    },
    {
      id: 17,
      noiDung: 'In formal English, the subjunctive form "were" is preferred over "was" for all subjects in Type 2 conditionals.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Trong văn phong trang trọng, "were" được dùng cho mọi ngôi (I were, he were, she were) trong câu điều kiện loại 2.',
    },
    {
      id: 18,
      noiDung: 'In the if-clause of a Type 1 conditional sentence, the modal verb "will" is commonly and standardly used to express simple future.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Trong mệnh đề If của câu điều kiện loại 1, ta dùng thì Hiện tại đơn để chỉ tương lai, không dùng "will" (trừ trường hợp thể hiện sự lịch sự/sẵn lòng).',
    },
    {
      id: 19,
      noiDung: 'Zero conditional sentences describe scientific truths, general facts, or automatic habits.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Câu điều kiện loại 0 (If + hiện tại, hiện tại) diễn tả chân lý, quy luật khoa học hiển nhiên.',
    },
    {
      id: 20,
      noiDung: 'Third conditional sentences talk about hypothetical situations and outcomes in the past that never actually happened.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Câu điều kiện loại 3 giả định một quá khứ trái ngược với thực tế và hệ quả của nó.',
    },
    {
      id: 21,
      noiDung: 'The inversion structure for Type 1 conditionals uses "Should + Subject + V-infinitive".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Đảo ngữ loại 1: Should + S + V(nguyên mẫu)... (ví dụ: Should you need any help...).',
    },
    {
      id: 22,
      noiDung: 'The sentence "If I would have known, I would have told you" is considered standard formal English.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Trong tiếng Anh chuẩn, mệnh đề If loại 3 dùng "had known", không bao giờ dùng "would have known" trong vế If.',
    },
    {
      id: 23,
      noiDung: 'Mixed conditionals can combine a past condition (Type 3) with a present result (Type 2).',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Câu điều kiện hỗn hợp diễn tả hành động trong quá khứ dẫn đến kết quả còn kéo dài ở hiện tại.',
    },
    {
      id: 24,
      noiDung: 'When the if-clause comes at the beginning of the sentence, a comma is normally placed after it.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Nếu mệnh đề If đứng đầu câu, cần có dấu phẩy ngăn cách với mệnh đề chính.',
    },
    {
      id: 25,
      noiDung: '"As long as" and "provided that" have the opposite meaning of "if".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "As long as" và "provided that" đồng nghĩa với "if" (miễn là / với điều kiện là).',
    },
    {
      id: 26,
      noiDung: 'In the sentence "If you mix blue and yellow, you get green", this is an example of a Zero conditional.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Sự thật hiển nhiên trong pha chế màu sắc: cả 2 vế dùng thì Hiện tại đơn.',
    },
    {
      id: 27,
      noiDung: 'The inversion for Type 2 conditionals with regular verbs is formed using "Were + Subject + to-infinitive".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'C1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Đảo ngữ loại 2 với động từ thường: "Were + S + to V" (ví dụ: Were they to discover the truth...).',
    },
    {
      id: 28,
      noiDung: 'In Type 1 conditionals, imperative verbs can be used in the main clause (e.g., "If you feel unwell, see a doctor").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Mệnh đề chính có thể là câu mệnh lệnh trực tiếp.',
    },
    {
      id: 29,
      noiDung: 'The phrase "But for + Noun phrase" can replace an if-clause in Type 2 or Type 3 conditionals.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "But for your help" (= If it hadn\'t been for your help) mang nghĩa "Nếu không có...".',
    },
    {
      id: 30,
      noiDung: 'We can use "even if" to state that a condition will not alter the eventual outcome.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Even if" (ngay cả khi / dẫu cho) nhấn mạnh kết quả không bị thay đổi bởi điều kiện.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which of the following phrases can introduce a conditional clause instead of "if"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Provided that',
        B: 'As long as',
        C: 'In case',
        D: 'Because of',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Provided that, As long as, In case đều dùng để đặt điều kiện. "Because of" là chỉ nguyên nhân.',
    },
    {
      id: 32,
      noiDung: 'Which of the following are grammatically correct conditional inversion sentences? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Should you require further information, please visit our website.',
        B: 'Had she listened to the warning, she would have been safe.',
        C: 'Were I in your shoes, I would take the offer.',
        D: 'Will you call me, I will pick you up.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (đảo ngữ loại 1), B (đảo ngữ loại 3), C (đảo ngữ loại 2) đều chính xác. D sai vì không có cấu trúc đảo ngữ với "Will".',
    },
    {
      id: 33,
      noiDung: 'Select all sentences that represent Type 2 conditional sentences (unreal present): (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'If I had wings, I would fly around the globe.',
        B: 'If he spoke fluent German, he could work in Berlin.',
        C: 'If it freezes tonight, the pond will turn to ice.',
        D: 'If they were wealthier, they would donate more to charity.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D giả định điều không có thật ở hiện tại (loại 2). C là điều kiện có thể xảy ra ở tương lai (loại 1).',
    },
    {
      id: 34,
      noiDung: 'Which sentences correctly illustrate mixed conditionals? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'C1',
      luaChon: {
        A: 'If I hadn\'t broken my leg last month, I would participate in today\'s marathon.',
        B: 'If he had taken French lessons in school, he could translate this article right now.',
        C: 'If you heat water, it boils at 100 degrees Celsius.',
        D: 'If she were more punctual in general, she wouldn\'t have missed her morning flight.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A và B kết hợp điều kiện quá khứ (loại 3) với kết quả hiện tại (loại 2). D kết hợp tính cách hiện tại (loại 2) với kết quả quá khứ (loại 3). C là loại 0.',
    },
    {
      id: 35,
      noiDung: 'Which of the following modal verbs can replace "would" in the main clause of a Type 2 or Type 3 conditional to show possibility or ability? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Could',
        B: 'Might',
        C: 'Shall',
        D: 'Must',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: '"Could" (chỉ khả năng) và "Might" (chỉ xác suất có thể xảy ra) thường xuyên thay thế cho "would".',
    },
    {
      id: 36,
      noiDung: 'Select all sentences with grammatical errors in conditional structures: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'If I will see him tomorrow, I will invite him.',
        B: 'If she had known the deadline, she would have submitted earlier.',
        C: 'Unless you don\'t hurry, we will miss our train.',
        D: 'Had he called me, I would have arrived promptly.',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: 'A sai vì dùng "will see" trong mệnh đề If. C sai lỗi phủ định kép với "unless" ("Unless you don\'t hurry"). B và D hoàn toàn đúng.',
    },
    {
      id: 37,
      noiDung: 'Which of the following expressions mean "without" or "if it were not for"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'But for',
        B: 'Without',
        C: 'Had it not been for',
        D: 'Due to',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'But for, Without, Had it not been for đều mang ý nghĩa "nếu không nhờ có/nếu không vì...". Due to mang nghĩa "do/bởi vì".',
    },
    {
      id: 38,
      noiDung: 'Which sentences correctly use "in case"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Take an umbrella in case it rains later.',
        B: 'I wrote down his phone number in case I forgot it.',
        C: 'In case of fire, use the stairs instead of the elevator.',
        D: 'I will call you in case if I am delayed.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B dùng "in case" phòng ngừa rủi ro. C dùng cụm "in case of + N". D sai vì thừa chữ "if" ("in case if").',
    },
    {
      id: 39,
      noiDung: 'Which sentences represent valid Type 3 conditional sentences (unreal past)? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'If they had left earlier, they would not have missed the connecting flight.',
        B: 'If we had booked our tickets in advance, we would have saved 30%.',
        C: 'If you had touched the pan, you would burn your fingers today.',
        D: 'She would have accepted the proposal if he had asked her.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là câu điều kiện loại 3 chuẩn (If had V3, would have V3). C là câu hỗn hợp chưa chuẩn ngữ cảnh.',
    },
    {
      id: 40,
      noiDung: 'Which of the following demonstrate correct use of Zero conditional for habits or routines? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'If I have a headache, I usually drink herbal chamomile tea.',
        B: 'If my boss calls, tell him I am in a meeting.',
        C: 'If you freeze water, it expands.',
        D: 'If I were rich, I would buy a private island.',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: 'A (thói quen cá nhân) và C (chân lý tự nhiên) là điều kiện loại 0 (hiện tại - hiện tại). B là loại 1 dạng mệnh lệnh. D là loại 2.',
    },
    {
      id: 41,
      noiDung: 'Identify all sentences that correctly invert a Type 2 conditional sentence: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'C1',
      luaChon: {
        A: 'Were he my brother, I would give him the same advice.',
        B: 'Were the company to expand into Asia, it would face fierce competition.',
        C: 'Did he know the answer, he would tell us.',
        D: 'Were it not for the heavy snow, we could travel today.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là các dạng đảo ngữ loại 2 chuẩn với "Were". C sai vì tiếng Anh không dùng "Did he know" để đảo ngữ câu điều kiện.',
    },
    {
      id: 42,
      noiDung: 'Which conjunctions emphasize that the outcome remains true regardless of the condition? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Even if',
        B: 'Whether or not',
        C: 'Unless',
        D: 'Provided that',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: '"Even if" và "Whether or not" nhấn mạnh sự việc vẫn diễn ra dù điều kiện có xảy ra hay không.',
    },
    {
      id: 43,
      noiDung: 'Which sentences correctly use "supposing" or "suppose" to set a hypothetical scenario? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Supposing you won a million dollars, what would you do first?',
        B: 'Suppose it rains tomorrow, will they cancel the outdoor match?',
        C: 'Supposing he had refused to sign, what would have happened?',
        D: 'Suppose that you will lose your job, what did you do?',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (giả định loại 2), B (giả định loại 1), C (giả định loại 3) dùng Supposing/Suppose chuẩn xác. D sai cấu trúc thì.',
    },
    {
      id: 44,
      noiDung: 'Select all sentences where the condition is genuinely possible and realistic (Type 1): (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'If we finish our tasks early, we can watch a movie together.',
        B: 'If the traffic is light, I will arrive before 6 PM.',
        C: 'If dogs had wings, they could chase birds in the sky.',
        D: 'If you don\'t water these houseplants, they will wither.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là các tình huống thực tế có thể xảy ra ở hiện tại hoặc tương lai (loại 1). C là tình huống hoang đường không có thật (loại 2).',
    },
    {
      id: 45,
      noiDung: 'Which verbs in the main clause of a conditional sentence can express permission, obligation, or advice? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'You can park here if you display a valid permit. (Permission)',
        B: 'If you want to pass, you must practice every single day. (Obligation)',
        C: 'If your throat hurts, you should drink honey tea. (Advice)',
        D: 'If it rains, it does rain tomorrow. (Habit)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Can (cho phép), Must (nghĩa vụ), Should (lời khuyên) trong mệnh đề chính. D là câu vô nghĩa.',
    },
  ],
};
