import { CurriculumTopicBank } from './types';

export const ENTERTAINMENT_BANK: CurriculumTopicBank = {
  key: 'ENTERTAINMENT',
  tenChuDe: 'Điện Ảnh, Âm Nhạc & Giải Trí (Entertainment & Media)',
  aliases: [
    'giải trí',
    'giai tri',
    'entertainment',
    'điện ảnh',
    'dien anh',
    'cinema',
    'phim',
    'movie',
    'film',
    'âm nhạc',
    'am nhac',
    'music',
    'ca nhạc',
    'ca si',
    'concert',
    'showbiz',
    'hollywood',
    'oscar',
    'grammy',
    'nghệ thuật',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'The lead actor received a thunderous standing __________ from the packed theater audience after his solo performance.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'ovation', B: 'audition', C: 'rehearsal', D: 'broadcast' },
      dapAnDung: 'A',
      giaiThich: '"Standing ovation" là tràng pháo tay nhiệt liệt khi toàn thể khán phòng đứng dậy tán thưởng.',
    },
    {
      id: 2,
      noiDung: 'The theatrical cast and crew held their final dress __________ on stage late yesterday evening.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'rehearsal', B: 'premiere', C: 'interview', D: 'script' },
      dapAnDung: 'A',
      giaiThich: '"Dress rehearsal" là buổi tổng duyệt trang phục và diễn xuất hoàn chỉnh trước ngày công diễn.',
    },
    {
      id: 3,
      noiDung: 'The international film festival will host the world __________ of the director\'s new historical drama.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'premiere', B: 'remake', C: 'sequel', D: 'trailer' },
      dapAnDung: 'A',
      giaiThich: '"Premiere" (buổi công chiếu ra mắt lần đầu tiên của một bộ phim hoặc vở kịch).',
    },
    {
      id: 4,
      noiDung: 'The charity music concert was organized to __________ essential funds for impoverished rural children.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'raise', B: 'rise', C: 'spend', D: 'waste' },
      dapAnDung: 'A',
      giaiThich: '"Raise funds" là cụm từ cố định mang nghĩa gây quỹ từ thiện.',
    },
    {
      id: 5,
      noiDung: 'The original background musical score of the epic fantasy movie is called its official __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'soundtrack', B: 'subtitle', C: 'script', D: 'billboard' },
      dapAnDung: 'A',
      giaiThich: '"Soundtrack" (nhạc phim bao gồm các bản nhạc giao hưởng và bài hát chính thức).',
    },
    {
      id: 6,
      noiDung: 'Thousands of hopeful aspiring vocalists attended the nationwide __________ for the reality talent show.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'auditions', B: 'broadcasts', C: 'subtitles', D: 'reviews' },
      dapAnDung: 'A',
      giaiThich: '"Audition" (buổi thử giọng/thử vai biểu diễn trước ban giám khảo).',
    },
    {
      id: 7,
      noiDung: 'The science fiction masterpiece shattered box-office records and earned status as a global __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'blockbuster', B: 'flop', C: 'prequel', D: 'manuscript' },
      dapAnDung: 'A',
      giaiThich: '"Blockbuster" (phim bom tấn đạt doanh thu phòng vé khổng lồ).',
    },
    {
      id: 8,
      noiDung: 'Moviegoers who prefer watching foreign language cinema rely heavily on translated on-screen __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'subtitles', B: 'headlines', C: 'captions', D: 'brochures' },
      dapAnDung: 'A',
      giaiThich: '"Subtitles" (phụ đề dịch ngôn ngữ hiển thị trên màn hình phim).',
    },
    {
      id: 9,
      noiDung: 'A story that describes events that happened prior to an existing film is known as a __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'prequel', B: 'sequel', C: 'remake', D: 'parody' },
      dapAnDung: 'A',
      giaiThich: '"Prequel" (tiền truyện - phần phim kể về những sự việc xảy ra trước tác phẩm gốc).',
    },
    {
      id: 10,
      noiDung: 'The cinema critic gave the indie drama a glowing __________ for its poignant screenplay and cinematography.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'review', B: 'refusal', C: 'revenue', D: 'receipt' },
      dapAnDung: 'A',
      giaiThich: '"Review" (bài phê bình/đánh giá nghệ thuật của nhà chuyên môn).',
    },
    {
      id: 11,
      noiDung: 'The theater had to cancel tonight\'s live performance because the lead soprano lost her __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'voice', B: 'sound', C: 'noise', D: 'echo' },
      dapAnDung: 'A',
      giaiThich: '"Lose one\'s voice" nghĩa là bị khản tiếng, mất giọng.',
    },
    {
      id: 12,
      noiDung: 'The live television __________ reached an estimated fifty million viewers worldwide.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'broadcast', B: 'rehearsal', C: 'audition', D: 'script' },
      dapAnDung: 'A',
      giaiThich: '"Broadcast" (chương trình phát sóng trên đài truyền hình hoặc phát thanh).',
    },
    {
      id: 13,
      noiDung: 'Behind every successful film stands a visionary __________ who coordinates camera angles, lighting, and acting.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'director', B: 'spectator', C: 'usher', D: 'listener' },
      dapAnDung: 'A',
      giaiThich: '"Director" (đạo diễn điện ảnh chỉ đạo toàn bộ cảnh quay và diễn xuất).',
    },
    {
      id: 14,
      noiDung: 'The documentary vividly portrays the rich musical __________ of New Orleans jazz pioneers.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'heritage', B: 'shortage', C: 'storage', D: 'wreckage' },
      dapAnDung: 'A',
      giaiThich: '"Musical heritage" nghĩa là di sản âm nhạc truyền thống quý giá.',
    },
    {
      id: 15,
      noiDung: 'Tickets for the pop star\'s stadium tour __________ out completely within three minutes of public release.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'sold', B: 'bought', C: 'paid', D: 'borrowed' },
      dapAnDung: 'A',
      giaiThich: '"Sell out" (bán sạch vé, cháy vé).',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'A prequel is a film or book that portrays events that took place after the events of the original work.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Tác phẩm kể về sự kiện diễn ra "sau đó" là Sequel (hậu truyện). Prequel (tiền truyện) kể về những gì xảy ra TRƯỚC tác phẩm gốc.',
    },
    {
      id: 17,
      noiDung: 'The Academy Awards, popularly known as the Oscars, recognize cinematic artistic and technical excellence.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Giải Oscar tôn vinh các thành tựu điện ảnh xuất sắc toàn cầu.',
    },
    {
      id: 18,
      noiDung: 'Cinematography refers to the art and science of motion-picture photography, lighting, and camera movement.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Cinematography là nghệ thuật quay phim, tạo hình ánh sáng và góc máy trong điện ảnh.',
    },
    {
      id: 19,
      noiDung: 'A "soundtrack" consists solely of sound effects such as explosions and car crashes, excluding all musical compositions.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Soundtrack bao gồm toàn bộ các bài hát và nhạc nền (score) được sáng tác riêng cho bộ phim.',
    },
    {
      id: 20,
      noiDung: 'An audition is a practical trial performance conducted to determine whether an artist is suitable for a role.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Audition là buổi thử diễn để tuyển chọn diễn viên hoặc ca sĩ phù hợp với vai trò.',
    },
    {
      id: 21,
      noiDung: 'The cast refers to the collective group of actors and performers appearing in a motion picture or theatrical play.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Cast" là dàn diễn viên tham gia diễn xuất trong phim hoặc vở kịch.',
    },
    {
      id: 22,
      noiDung: 'A "box-office flop" refers to a commercially triumphant movie that set historic financial profit records.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Flop" chỉ bộ phim thất bại thảm hại về doanh thu phòng vé. Thành công lớn gọi là "blockbuster" hoặc "hit".',
    },
    {
      id: 23,
      noiDung: 'Genre categorization in film includes categories like comedy, horror, documentary, and science fiction.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Thể loại phim (Genre) bao gồm hài kịch, kinh dị, tài liệu, khoa học viễn tưởng...',
    },
    {
      id: 24,
      noiDung: 'A conductor in an orchestra plays the primary violin while also singing the vocal chorus.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Nhạc trưởng (Conductor) điều khiển và chỉ huy toàn bộ dàn nhạc giao hưởng bằng dùi chỉ huy, không phải người chơi violin hay hát.',
    },
    {
      id: 25,
      noiDung: 'Streaming platforms allow subscribers to access films and songs on demand via an active internet connection.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Nền tảng phát trực tuyến (Streaming) cung cấp nội dung giải trí theo yêu cầu qua internet.',
    },
    {
      id: 26,
      noiDung: 'A cameo is a brief, uncredited or credited appearance by a famous celebrity in a film or television show.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Vai diễn khách mời "cameo" là sự xuất hiện ngắn bất ngờ của một ngôi sao nổi tiếng.',
    },
    {
      id: 27,
      noiDung: 'Subtitles and audio dubbing are two common techniques used to localize international media for foreign audiences.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Phụ đề (subtitles) và lồng tiếng (dubbing) là hai phương pháp chuyển ngữ phim phổ biến.',
    },
    {
      id: 28,
      noiDung: 'A cliffhanger is a dramatic ending to an episode that leaves the audience in suspense about what happens next.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Cliffhanger" là cái kết bỏ lửng hồi hộp cuối tập phim nhằm kích thích người xem đón chờ phần tiếp theo.',
    },
    {
      id: 29,
      noiDung: 'In cinema, the crew includes actors, whereas the cast refers only to camera operators and sound technicians.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Ngược lại: "Cast" là dàn diễn viên trước ống kính, "Crew" là đoàn làm phim kỹ thuật phía sau hậu trường.',
    },
    {
      id: 30,
      noiDung: 'An encore is an additional performance given by musicians at the end of a concert in response to passionate audience cheers.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Màn diễn "Encore" là tiết mục biểu diễn thêm theo yêu cầu nhiệt liệt của khán giả sau khi buổi hòa nhạc kết thúc.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which of the following are prestigious international entertainment awards? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The Academy Awards (Oscars) for film',
        B: 'The Grammy Awards for music',
        C: 'The Emmy Awards for television broadcasting',
        D: 'The periodic table of elements',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Oscars, Grammys, Emmys là các giải thưởng danh giá bậc nhất thế giới trong nghệ thuật giải trí.',
    },
    {
      id: 32,
      noiDung: 'Which cinematic genres are typically recognized in film studies? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Science Fiction (Sci-Fi)',
        B: 'Psychological Thriller',
        C: 'Documentary',
        D: 'Computer Random Access Memory',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Khoa học viễn tưởng, giật gân tâm lý, phim tài liệu là các thể loại điện ảnh kinh điển.',
    },
    {
      id: 33,
      noiDung: 'Which roles are directly involved in film production behind the scenes (the crew)? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Director of Photography (Cinematographer)',
        B: 'Film Editor',
        C: 'Costume and Production Designer',
        D: 'Popcorn vendor in the lobby',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Đạo diễn hình ảnh, dựng phim và thiết kế phục trang là các vị trí then chốt trong đoàn làm phim (crew).',
    },
    {
      id: 34,
      noiDung: 'Which musical instruments belong to the string family? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Violin',
        B: 'Cello',
        C: 'Acoustic Guitar',
        D: 'Trumpet',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Violin, Cello và Guitar là nhạc cụ bộ dây. Trumpet là nhạc cụ bộ hơi kim loại (brass).',
    },
    {
      id: 35,
      noiDung: 'Select all terms that relate to musical performance and composition: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Melody',
        B: 'Harmony',
        C: 'Rhythm',
        D: 'Photosynthesis',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Giai điệu (Melody), Hòa âm (Harmony) và Nhịp điệu (Rhythm) là 3 trụ cột của âm nhạc.',
    },
    {
      id: 36,
      noiDung: 'Which factors usually determine the commercial success of a major theatrical film release? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Box-office ticket revenues on opening weekend',
        B: 'Positive critical acclaim and word-of-mouth recommendations',
        C: 'Global streaming rights and syndication deals',
        D: 'The color of the cinema carpet',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Doanh thu mở màn, phản hồi tích cực của giới phê bình và hợp đồng bản quyền phát trực tuyến quyết định thành bại của phim.',
    },
    {
      id: 37,
      noiDung: 'Which compound terms describe entertainment media formats? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Feature-length film',
        B: 'Miniseries',
        C: 'Reality television show',
        D: 'Turbo diesel injection',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Phim điện ảnh dài tập (A), phim ngắn tập (B) và chương trình truyền hình thực tế (C) là các định dạng giải trí.',
    },
    {
      id: 38,
      noiDung: 'Which phrases describe enthusiastic audience reactions at live events? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Thunderous applause',
        B: 'Standing ovation',
        C: 'Enthusiastic cheers and encores',
        D: 'Silent indifferent snoring',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Tràng pháo tay ròn rã, đứng dậy hoan hô và reo hò cuồng nhiệt là biểu hiện của sự tán thưởng.',
    },
    {
      id: 39,
      noiDung: 'Select all visual components managed by the production design team in movie making: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Set construction and background environments',
        B: 'Period-accurate costumes and wardrobe',
        C: 'Makeup, prosthetics, and special effects styling',
        D: 'Theater ticket pricing algorithm',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Dựng bối cảnh, phục trang đúng niên đại và hóa trang nhân vật là nhiệm vụ của đội ngũ thiết kế sản xuất mỹ thuật.',
    },
    {
      id: 40,
      noiDung: 'Which terms describe different styles or movements in modern music? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Jazz and Blues',
        B: 'Classical Symphony',
        C: 'Hip-Hop and R&B',
        D: 'Reinforced concrete pouring',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Jazz, Nhạc cổ điển giao hưởng, Hip-Hop và R&B là các dòng nhạc quốc tế tiêu biểu.',
    },
    {
      id: 41,
      noiDung: 'Which benefits have digital streaming platforms brought to viewers? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Binge-watching entire television seasons without waiting weeks',
        B: 'Accessing international cinema from home with multilingual subtitles',
        C: 'On-demand playback pausing and resuming across multiple devices',
        D: 'Mandatory queuing in rain for paper tickets',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Xem liên tục nhiều tập (binge-watching), xem phim quốc tế tại nhà và đồng bộ nhiều thiết bị là ưu thế vượt trội của streaming.',
    },
    {
      id: 42,
      noiDung: 'Which vocabulary items relate to dramatic theater productions? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Monologue (độc thoại)',
        B: 'Curtain call (nghệ sĩ ra chào khán giả)',
        C: 'Stage stagecraft and lighting',
        D: 'Submarine periscope',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Độc thoại, màn chào cuối vở diễn và kỹ thuật dàn dựng sân khấu là các thuật ngữ kịch nghệ kinh điển.',
    },
    {
      id: 43,
      noiDung: 'Select all verbs that naturally collocate with "album" in music: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Release a new album',
        B: 'Record an album in the studio',
        C: 'Promote an album on tour',
        D: 'Boil an album',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Release (phát hành), Record (thu âm), Promote (quảng bá) album là các kết hợp từ chuẩn.',
    },
    {
      id: 44,
      noiDung: 'Which of the following describe animated movies and techniques? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Computer-Generated Imagery (CGI)',
        B: 'Stop-motion claymation',
        C: 'Traditional hand-drawn 2D animation',
        D: 'Live volcanic eruption monitoring',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'CGI, Stop-motion và vẽ tay 2D là các kỹ thuật làm phim hoạt hình kinh điển.',
    },
    {
      id: 45,
      noiDung: 'Which adjectives describe high praise from entertainment critics? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Mesmerizing',
        B: 'Critically acclaimed',
        C: 'Riveting',
        D: 'Boring and dull',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Mesmerizing (mê hoặc), Critically acclaimed (được giới phê bình khen ngợi hết lời), Riveting (cuốn hút). D mang nghĩa chê bai.',
    },
  ],
};
