import { CurriculumTopicBank } from './types';

export const ENVIRONMENT_SOCIETY_BANK: CurriculumTopicBank = {
  key: 'ENVIRONMENT_SOCIETY',
  tenChuDe: 'Từ Vựng IELTS Chủ Đề Môi Trường & Xã Hội',
  aliases: [
    'môi trường',
    'moi truong',
    'xã hội',
    'xa hoi',
    'environment',
    'society',
    'biến đổi khí hậu',
    'ô nhiễm',
    'o nhiem',
    'climate change',
    'ielts writing task 2',
    'ielts writing',
    'sinh thái',
    'bảo tồn',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'The unprecedented melting of polar ice caps is primarily attributed to accelerated global __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'warming', B: 'warning', C: 'cooling', D: 'freezing' },
      dapAnDung: 'A',
      giaiThich: '"Global warming" (sự nóng lên toàn cầu) là thuật ngữ chỉ sự gia tăng nhiệt độ bề mặt Trái Đất.',
    },
    {
      id: 2,
      noiDung: 'Governments worldwide must enact strict emissions regulations to curb the catastrophic impact of climate __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'change', B: 'chance', C: 'charge', D: 'chase' },
      dapAnDung: 'A',
      giaiThich: '"Climate change" (biến đổi khí hậu toàn cầu).',
    },
    {
      id: 3,
      noiDung: 'Transitioning towards __________ energy sources such as wind, solar, and tidal power is imperative for net-zero goals.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'renewable', B: 'fossil', C: 'exhaustible', D: 'depletable' },
      dapAnDung: 'A',
      giaiThich: '"Renewable energy" (năng lượng tái tạo/năng lượng sạch có khả năng tự phục hồi).',
    },
    {
      id: 4,
      noiDung: 'Rampant commercial deforestation poses an existential threat to tropical rainforest __________ and wildlife.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'biodiversity', B: 'monopoly', C: 'uniformity', D: 'homogeneity' },
      dapAnDung: 'A',
      giaiThich: '"Biodiversity" (đa dạng sinh học - sự phong phú của các loài động thực vật trong hệ sinh thái).',
    },
    {
      id: 5,
      noiDung: 'Single-use plastic containers take hundreds of years to __________ in natural landfills.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'decompose', B: 'evaporate', C: 'germinate', D: 'amplify' },
      dapAnDung: 'A',
      giaiThich: '"Decompose" (phân hủy sinh học tự nhiên).',
    },
    {
      id: 6,
      noiDung: 'The growing wealth __________ between the ultra-rich and low-income demographics threatens societal harmony.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'gap', B: 'hole', C: 'ditch', D: 'crack' },
      dapAnDung: 'A',
      giaiThich: '"Wealth gap" (khoảng cách giàu nghèo trong xã hội).',
    },
    {
      id: 7,
      noiDung: 'Burning coal and petroleum fuels releases massive volumes of greenhouse gas __________ into the atmosphere.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'emissions', B: 'admissions', C: 'omissions', D: 'submissions' },
      dapAnDung: 'A',
      giaiThich: '"Greenhouse gas emissions" (khí thải nhà kính gây hiệu ứng ấm lên toàn cầu).',
    },
    {
      id: 8,
      noiDung: 'Many developing nations are experiencing rapid __________ as rural inhabitants migrate to urban centers in search of jobs.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'urbanization', B: 'industrialization', C: 'globalization', D: 'polarization' },
      dapAnDung: 'A',
      giaiThich: '"Urbanization" (quá trình đô thị hóa).',
    },
    {
      id: 9,
      noiDung: 'Individuals can substantially minimize their ecological __________ by utilizing public transport and recycling waste.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'footprint', B: 'shoeprint', C: 'handprint', D: 'fingerprint' },
      dapAnDung: 'A',
      giaiThich: '"Carbon / Ecological footprint" (dấu chân sinh thái / lượng khí thải carbon mà mỗi cá nhân thải ra).',
    },
    {
      id: 10,
      noiDung: 'Overfishing has drastically depleted marine fish __________ in international territorial waters.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'stocks', B: 'crops', C: 'herds', D: 'packs' },
      dapAnDung: 'A',
      giaiThich: '"Fish stocks" (trữ lượng cá trong môi trường tự nhiên).',
    },
    {
      id: 11,
      noiDung: 'Adequate access to clean drinking water and sanitary plumbing is an indispensable human __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'right', B: 'duty', C: 'favor', D: 'luxury' },
      dapAnDung: 'A',
      giaiThich: '"Human right" (quyền cơ bản của con người).',
    },
    {
      id: 12,
      noiDung: 'A circular economy promotes reusing, repairing, and __________ existing materials and products as long as possible.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'recycling', B: 'discarding', C: 'burning', D: 'burying' },
      dapAnDung: 'A',
      giaiThich: '"Recycling" (tái chế vật liệu) là một trong những trụ cột của nền kinh tế tuần hoàn.',
    },
    {
      id: 13,
      noiDung: 'Air pollution in major industrial hubs has triggered a sharp rise in chronic __________ illnesses among children.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'respiratory', B: 'digestive', C: 'auditory', D: 'cardiac' },
      dapAnDung: 'A',
      giaiThich: '"Respiratory illnesses" (các bệnh lý về đường hô hấp như hen suyễn, viêm phế quản do khói bụi).',
    },
    {
      id: 14,
      noiDung: 'Conserving natural wildlife __________ is essential to prevent vulnerable species from going extinct.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'habitats', B: 'apartments', C: 'factories', D: 'settlements' },
      dapAnDung: 'A',
      giaiThich: '"Habitats" (môi trường sống tự nhiên của động thực vật hoang dã).',
    },
    {
      id: 15,
      noiDung: 'The United Nations established 17 Sustainable Development __________ (SDGs) to guide global social progress.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'Goals', B: 'Wishes', C: 'Dreams', D: 'Guarantees' },
      dapAnDung: 'A',
      giaiThich: 'SDGs là viết tắt của "Sustainable Development Goals" (Các mục tiêu phát triển bền vững của Liên Hợp Quốc).',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'Deforestation directly accelerates climate change by reducing the planet\'s capacity to absorb carbon dioxide from the air.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Rừng là bể hấp thụ carbon tự nhiên; nạn phá rừng làm giảm khả năng quang hợp hấp thụ CO2 và giải phóng thêm khí nhà kính.',
    },
    {
      id: 17,
      noiDung: 'Fossil fuels such as coal, oil, and natural gas are infinite and replenish themselves within a few human generations.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Nhiên liệu hóa thạch là nguồn tài nguyên hữu hạn (non-renewable/finite) mất hàng triệu năm mới hình thành trong lòng đất.',
    },
    {
      id: 18,
      noiDung: 'The term "carbon footprint" represents the total greenhouse gas emissions caused directly or indirectly by an individual, event, or organization.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Dấu chân carbon" đo lường tổng lượng khí thải nhà kính (quy đổi theo CO2) sinh ra từ hoạt động con người.',
    },
    {
      id: 19,
      noiDung: 'Biodiversity refers to having only one single dominant agricultural crop species planted across vast agricultural fields.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Trồng một loại cây duy nhất là độc canh (Monoculture). Đa dạng sinh học (Biodiversity) là sự phong phú đa dạng của muôn loài sinh vật.',
    },
    {
      id: 20,
      noiDung: 'Endangered species are flora and fauna facing an exceptionally high risk of extinction in the immediate wild.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Các loài có nguy cơ tuyệt chủng (Endangered species) cần được bảo tồn nghiêm ngặt.',
    },
    {
      id: 21,
      noiDung: 'The greenhouse effect is an entirely man-made phenomenon that never existed prior to the Industrial Revolution.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Hiệu ứng nhà kính tự nhiên đã tồn tại để giữ ấm cho Trái Đất có sự sống. Khí thải nhân tạo chỉ làm gia tăng quá mức hiệu ứng này.',
    },
    {
      id: 22,
      noiDung: 'Urban sprawl describes the uncontrolled, unplanned expansion of metropolitan regions into surrounding rural countryside.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Urban sprawl" (sự mở rộng đô thị tự phát/loang lổ) gây tốn kém hạ tầng và mất đất nông nghiệp.',
    },
    {
      id: 23,
      noiDung: 'The "circular economy" model promotes a "take, make, and dispose" linear model where goods are discarded immediately after first use.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Mô hình "take, make, dispose" là kinh tế tuyến tính truyền thống. Kinh tế tuần hoàn (circular economy) hướng tới tái sử dụng, tái chế và khép kín vòng đời sản phẩm.',
    },
    {
      id: 24,
      noiDung: 'Renewable energy infrastructure generates minimal ongoing greenhouse gas emissions compared to traditional coal-fired power stations.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Năng lượng tái tạo (điện gió, mặt trời) không đốt nhiên liệu hóa thạch nên phát thải khí nhà kính cực thấp.',
    },
    {
      id: 25,
      noiDung: 'Social stratification refers to a society categorizing its people into socioeconomic tiers based on wealth, income, and power.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'C1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Phân tầng xã hội (Social stratification) là sự phân chia thứ bậc kinh tế - xã hội trong cộng đồng.',
    },
    {
      id: 26,
      noiDung: 'Microplastics have been detected throughout global marine food webs and even in human biological tissues.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Hạt vi nhựa (Microplastics) ô nhiễm sâu rộng vào chuỗi thức ăn đại dương và cơ thể sinh vật.',
    },
    {
      id: 27,
      noiDung: 'Greenwashing is when a company genuinely spends 100% of its operating budget on organic wildlife restoration.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Greenwashing" (tẩy xanh) là hành vi doanh nghiệp tiếp thị giả tạo nhằm đánh bóng hình ảnh thân thiện với môi trường trong khi thực tế không phải vậy.',
    },
    {
      id: 28,
      noiDung: 'Universal healthcare ensures that all citizens have access to necessary medical treatment without suffering financial hardship.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Chăm sóc y tế toàn dân (Universal healthcare) bảo đảm công bằng xã hội về mặt sức khỏe.',
    },
    {
      id: 29,
      noiDung: 'Desertification is the land degradation process in arid and dry sub-humid areas caused by climatic variations and unsustainable human activities.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Sa mạc hóa (Desertification) biến đất đai màu mỡ thành hoang mạc khô cằn.',
    },
    {
      id: 30,
      noiDung: 'Philanthropy refers to the practice of accumulating excessive corporate wealth through deceitful business monopolies.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Philanthropy" là hoạt động từ thiện, cống hiến tài sản và nguồn lực cá nhân vì lợi ích cộng đồng.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which of the following are recognized renewable energy resources? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Solar photovoltaic energy',
        B: 'Wind turbine energy',
        C: 'Geothermal energy',
        D: 'Anthracite coal',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Năng lượng mặt trời, gió, địa nhiệt là các nguồn năng lượng tái tạo sạch. Than đá là nhiên liệu hóa thạch gây ô nhiễm.',
    },
    {
      id: 32,
      noiDung: 'Which environmental issues are directly triggered by intensive plastic pollution? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Ingestion of microplastics by marine wildlife',
        B: 'Clogging of municipal urban drainage systems and riverways',
        C: 'Depletion of Earth\'s ozone layer',
        D: 'Leaching of toxic chemical additives into groundwater aquifers',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Rác thải nhựa đầu độc sinh vật biển (A), tắc cống nghẹt sông ngòi (B) và thẩm thấu hóa chất độc hại vào nguồn nước (D). Lỗ thủng ozone chủ yếu do khí CFC gây ra.',
    },
    {
      id: 33,
      noiDung: 'Select all factors driving the worldwide transition towards green transportation: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Mitigating urban smog and toxic tailpipe air emissions',
        B: 'Reducing national dependency on imported foreign crude oil',
        C: 'Advancing electric vehicle battery efficiency and charging networks',
        D: 'Maximizing diesel engine exhaust output',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Giảm ô nhiễm khói bụi (A), giảm lệ thuộc dầu mỏ (B) và công nghệ pin sạc tiến bộ (C) thúc đẩy giao thông xanh.',
    },
    {
      id: 34,
      noiDung: 'Which phrases describe social inequality or socio-economic disparity in IELTS Writing Task 2? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The growing wealth gap',
        B: 'Disproportionate distribution of resources',
        C: 'Equal financial prosperity for all citizens',
        D: 'Marginalization of underprivileged communities',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là các cụm từ học thuật chuẩn biểu đạt sự bất bình đẳng kinh tế - xã hội. C mang nghĩa ngược lại (thịnh vượng bình đẳng).',
    },
    {
      id: 35,
      noiDung: 'Which actions reflect sustainable conservation habits for modern households? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Sorting household solid waste into recyclables and organic compost',
        B: 'Turning off electrical appliances when not in active use',
        C: 'Running clean tap water continuously while brushing teeth',
        D: 'Utilizing energy-efficient LED light bulbs',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Phân loại rác (A), tắt thiết bị điện (B) và dùng đèn LED (D) giúp tiết kiệm năng lượng và bảo vệ môi trường.',
    },
    {
      id: 36,
      noiDung: 'Select all major causes of global biodiversity depletion: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Deforestation and natural habitat destruction',
        B: 'Poaching and illegal wildlife trafficking',
        C: 'Establishment of national nature conservation parks',
        D: 'Introduction of aggressive invasive alien species',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Mất môi trường sống (A), săn bắt trộm (B) và sinh vật ngoại lai xâm hại (D) đe dọa đa dạng sinh học. Thành lập vườn quốc gia (C) là hành động bảo tồn.',
    },
    {
      id: 37,
      noiDung: 'Which terms belong to United Nations Sustainable Development Goals (SDGs)? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'No Poverty and Zero Hunger',
        B: 'Quality Education and Gender Equality',
        C: 'Clean Water and Affordable Clean Energy',
        D: 'Unlimited Exploitation of Fossil Fuels',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C là các mục tiêu cốt lõi trong 17 SDGs của Liên Hợp Quốc.',
    },
    {
      id: 38,
      noiDung: 'Which gases are considered major greenhouse gases causing atmospheric heat retention? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Carbon dioxide (CO2)',
        B: 'Methane (CH4)',
        C: 'Nitrous oxide (N2O)',
        D: 'Pure Oxygen (O2)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'CO2, CH4, N2O là các khí nhà kính chính. O2 là dưỡng khí trong lành cho sự thở, không phải khí nhà kính.',
    },
    {
      id: 39,
      noiDung: 'Which terms refer to environmental degradation in agricultural practices? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Soil erosion',
        B: 'Excessive pesticide contamination',
        C: 'Salinization of freshwater irrigation systems',
        D: 'Organic crop rotation',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Xói mòn đất (A), nhiễm độc thuốc trừ sâu (B) và nhiễm mặn nước ngọt (C) là hệ lụy nông nghiệp thâm canh. Luân canh hữu cơ (D) là phương pháp bảo vệ đất.',
    },
    {
      id: 40,
      noiDung: 'Select all vocabulary items frequently employed in IELTS essays regarding education and social mobility: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Socioeconomic status',
        B: 'Equal access to higher tertiary education',
        C: 'Intergenerational upward mobility',
        D: 'Plastic bottle cap dimensions',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Địa vị kinh tế xã hội, bình đẳng tiếp cận đại học và sự dịch chuyển xã hội thăng tiến giữa các thế hệ là các cụm từ IELTS kinh điển.',
    },
    {
      id: 41,
      noiDung: 'Which international treaties or agreements target global carbon emission reductions? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The Paris Agreement on Climate Change',
        B: 'The Kyoto Protocol',
        C: 'The Montreal Protocol on Substances that Deplete the Ozone Layer',
        D: 'The Monopoly Board Game Rulebook',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Hiệp định Paris, Nghị định thư Kyoto và Montreal là các điều ước quốc tế lịch sử bảo vệ khí hậu và tầng ozone.',
    },
    {
      id: 42,
      noiDung: 'Which strategies help alleviate extreme poverty in vulnerable rural communities? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Microfinance loans for small-scale local entrepreneurs',
        B: 'Vocational training and agricultural technical education',
        C: 'Subsidized healthcare and clean piped water infrastructure',
        D: 'Completely confiscating rural farmers\' farming tools',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Tín dụng vi mô (A), đào tạo nghề (B) và hạ tầng y tế/nước sạch (C) giúp xóa đói giảm nghèo bền vững.',
    },
    {
      id: 43,
      noiDung: 'Select all consequences of severe ocean acidification: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'C1',
      luaChon: {
        A: 'Widespread bleaching and degradation of coral reefs',
        B: 'Impaired shell formation in mollusks and shellfish',
        C: 'Disruption of marine trophic food chains',
        D: 'Instant freezing of all ocean waters',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Axit hóa đại dương (do hấp thụ quá nhiều CO2) làm tẩy trắng san hô, cản trở sinh vật tạo vỏ vôi và xáo trộn chuỗi thức ăn biển.',
    },
    {
      id: 44,
      noiDung: 'Which of the following are components of the 3Rs ecological waste hierarchy? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A1',
      luaChon: {
        A: 'Reduce (giảm thiểu tiêu thụ thừa)',
        B: 'Reuse (tái sử dụng nhiều lần)',
        C: 'Recycle (tái chế vật liệu phế thải)',
        D: 'Ruined',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: '3Rs = Reduce, Reuse, Recycle là nguyên lý quản lý rác thải sinh thái toàn cầu.',
    },
    {
      id: 45,
      noiDung: 'Select all concepts associated with progressive societal reform: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Gender pay equity',
        B: 'Inclusion of people with disabilities in public life',
        C: 'Legal protection against racial discrimination',
        D: 'Compulsory child labor in textile factories',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Bình đẳng thu nhập giới, hòa nhập người khuyết tật và chống phân biệt đối xử là các giá trị xã hội tiến bộ. Lao động trẻ em (D) là bất hợp pháp.',
    },
  ],
};
