import { CurriculumTopicBank } from './types';

export const INFORMATION_TECHNOLOGY_BANK: CurriculumTopicBank = {
  key: 'INFORMATION_TECHNOLOGY',
  tenChuDe: 'Tiếng Anh Chuyên Ngành Công Nghệ Thông Tin (IT & Tech)',
  aliases: [
    'it',
    'cntt',
    'công nghệ thông tin',
    'cong nghe thong tin',
    'information technology',
    'tech',
    'technology',
    'software',
    'phần mềm',
    'phan mem',
    'hardware',
    'phần cứng',
    'lập trình',
    'lap trinh',
    'coding',
    'code',
    'developer',
    'programmer',
    'computer',
    'máy tính',
    'may tinh',
    'ai',
    'artificial intelligence',
    'machine learning',
    'trí tuệ nhân tạo',
    'tri tue nhan tao',
    'database',
    'cơ sở dữ liệu',
    'co so du lieu',
    'network',
    'cybersecurity',
    'an ninh mạng',
    'web',
    'backend',
    'frontend',
    'devops',
    'cloud',
  ],
  questions: [
    // === 15 CÂU SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'The systematic process of identifying, diagnosing, and resolving bugs in code is known as __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'debugging', B: 'compiling', C: 'encrypting', D: 'deploying' },
      dapAnDung: 'A',
      giaiThich: '"Debugging" là quá trình phát hiện và khắc phục các lỗi (bugs) trong mã nguồn ứng dụng.',
    },
    {
      id: 2,
      noiDung: 'Cloud computing allows organizations to dynamically __________ their server resources according to fluctuating user traffic.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'scale', B: 'crash', C: 'erase', D: 'reboot' },
      dapAnDung: 'A',
      giaiThich: '"Scale" (mở rộng/thu nhỏ quy mô) cho phép hệ thống đám mây tự động điều chỉnh năng lực máy chủ.',
    },
    {
      id: 3,
      noiDung: 'Software developers use Git branches to __________ new experimental features from the main stable release.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'isolate', B: 'destroy', C: 'delete', D: 'leak' },
      dapAnDung: 'A',
      giaiThich: '"Isolate" (cô lập, tách biệt) tính năng mới để phát triển mà không gây rủi ro cho nhánh mã nguồn chính.',
    },
    {
      id: 4,
      noiDung: 'Modern AI algorithms rely heavily on massive datasets to __________ their neural networks with high accuracy.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'train', B: 'erase', C: 'confuse', D: 'terminate' },
      dapAnDung: 'A',
      giaiThich: '"Train" (huấn luyện) mô hình mạng nơ-ron học sâu dựa trên dữ liệu lớn.',
    },
    {
      id: 5,
      noiDung: 'A __________ is a critical software update designed to fix security vulnerabilities and prevent exploits.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'patch', B: 'malware', C: 'trojan', D: 'firewall' },
      dapAnDung: 'A',
      giaiThich: '"Patch" (bản vá bảo mật) là bản cập nhật khẩn cấp vá lỗ hổng an ninh.',
    },
    {
      id: 6,
      noiDung: 'To ensure data privacy during transmission over public networks, sensitive data must be __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'encrypted', B: 'exposed', C: 'duplicated', D: 'deleted' },
      dapAnDung: 'A',
      giaiThich: '"Encrypted" (mã hóa) biến dữ liệu thô thành dạng mật mã để bên thứ ba không thể đọc lén.',
    },
    {
      id: 7,
      noiDung: 'A software architect designs the high-level system structure, including component __________ and data flow.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'interactions', B: 'collisions', C: 'distractions', D: 'corruptions' },
      dapAnDung: 'A',
      giaiThich: '"Interactions" (các tương tác/giao tiếp giữa các thành phần phần mềm).',
    },
    {
      id: 8,
      noiDung: 'The team follows the __________ development methodology, conducting daily stand-up meetings and two-week sprints.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'Agile', B: 'Fragile', C: 'Waterfall', D: 'Chaotic' },
      dapAnDung: 'A',
      giaiThich: '"Agile" (phương pháp phát triển phần mềm linh hoạt với Scrum, Sprint và Daily Stand-up).',
    },
    {
      id: 9,
      noiDung: 'A __________ query is used to retrieve specific columns and rows from a database table based on condition filters.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'SELECT', B: 'DROP', C: 'DELETE', D: 'ALTER' },
      dapAnDung: 'A',
      giaiThich: 'Lệnh "SELECT" trong ngôn ngữ SQL dùng để truy vấn và lấy dữ liệu.',
    },
    {
      id: 10,
      noiDung: 'When website traffic suddenly surges, a load __________ distributes incoming requests evenly across multiple servers.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'balancer', B: 'breaker', C: 'compressor', D: 'generator' },
      dapAnDung: 'A',
      giaiThich: '"Load balancer" (bộ cân bằng tải) phân phối lưu lượng truy cập tới nhiều máy chủ phụ trợ.',
    },
    {
      id: 11,
      noiDung: 'To prevent unauthorized network intrusion, companies set up a digital __________ between their internal network and the Internet.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'firewall', B: 'router', C: 'switch', D: 'cookie' },
      dapAnDung: 'A',
      giaiThich: '"Firewall" (tường lửa) giám sát và lọc các gói dữ liệu ra vào mạng.',
    },
    {
      id: 12,
      noiDung: 'The company migrated its monolithic application into a decoupled __________ architecture to enhance maintainability.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'microservices', B: 'hardwired', C: 'standalone', D: 'centralized' },
      dapAnDung: 'A',
      giaiThich: '"Microservices" (kiến trúc vi dịch vụ) phân chia ứng dụng thành các dịch vụ độc lập nhỏ.',
    },
    {
      id: 13,
      noiDung: 'Continuous Integration and Continuous Deployment (CI/CD) pipelines __________ the build and release workflow.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'automate', B: 'complicate', C: 'prohibit', D: 'delay' },
      dapAnDung: 'A',
      giaiThich: '"Automate" (tự động hóa) các bước đóng gói, kiểm thử và triển khai phần mềm.',
    },
    {
      id: 14,
      noiDung: 'A memory __________ occurs when an application fails to release allocated memory that is no longer needed.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'leak', B: 'boost', C: 'speed', D: 'gain' },
      dapAnDung: 'A',
      giaiThich: '"Memory leak" (rò rỉ bộ nhớ) là hiện tượng ứng dụng giữ bộ nhớ RAM không cần thiết làm cạn kiệt tài nguyên.',
    },
    {
      id: 15,
      noiDung: 'Frontend engineers focus on optimizing the user interface and overall user __________ (UX).',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'experience', B: 'experiment', C: 'expense', D: 'expectation' },
      dapAnDung: 'A',
      giaiThich: '"User Experience" (trải nghiệm người dùng - UX).',
    },

    // === 15 CÂU TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'Open-source software means the underlying source code is publicly accessible and can be modified and distributed.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Phần mềm mã nguồn mở (Open-source) cho phép mọi người xem, chỉnh sửa và phân phối lại mã nguồn.',
    },
    {
      id: 17,
      noiDung: 'Phishing is an authorized cybersecurity audit method used by network admins to securely verify employee passwords.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Phishing là hình thức tấn công lừa đảo trực tuyến giả mạo nhằm đánh cắp thông tin đăng nhập.',
    },
    {
      id: 18,
      noiDung: 'An API (Application Programming Interface) enables different software services to communicate using standard protocols.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. API là giao diện lập trình ứng dụng kết nối và trao đổi dữ liệu giữa các phần mềm.',
    },
    {
      id: 19,
      noiDung: 'HTTPS encrypts communication between the client web browser and the web server using SSL/TLS protocols.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. HTTPS mã hóa đường truyền nhằm bảo đảm tính toàn vẹn và bảo mật dữ liệu.',
    },
    {
      id: 20,
      noiDung: 'A compiler translates high-level programming language code directly into machine-readable code or bytecode.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Compiler (trình biên dịch) chuyển đổi mã nguồn bậc cao thành mã máy hoặc bytecode.',
    },
    {
      id: 21,
      noiDung: 'Relational databases use tables consisting of rows and columns to store structured data.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. CSDL quan hệ (RDBMS) lưu trữ dữ liệu có cấu trúc theo các bảng (tables) gồm hàng và cột.',
    },
    {
      id: 22,
      noiDung: 'Software testing should only be conducted manually after the entire project has been completely deployed to production.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Kiểm thử tự động (Unit, Integration Test) cần thực hiện liên tục xuyên suốt quá trình phát triển, không phải đợi đến sau khi lên production.',
    },
    {
      id: 23,
      noiDung: 'In Git version control, the command "git merge" combines changes from one branch into another.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "git merge" hợp nhất lịch sử và thay đổi của một nhánh vào nhánh hiện tại.',
    },
    {
      id: 24,
      noiDung: 'Machine learning algorithms can learn patterns from training data without being explicitly programmed for every specific scenario.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Học máy cho phép máy tính tự học quy luật từ dữ liệu thay vì lập trình thủ công từng trường hợp.',
    },
    {
      id: 25,
      noiDung: 'Hardcoding passwords and API secrets directly into GitHub public repositories is a recommended security practice.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Hardcode mật khẩu vào mã nguồn công khai là lỗi bảo mật nghiêm trọng; phải dùng biến môi trường (.env).',
    },
    {
      id: 26,
      noiDung: 'Responsive web design allows websites to automatically adapt their layout to screens of different sizes, such as mobile phones and tablets.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Thiết kế đáp ứng (Responsive Design) đảm bảo giao diện hiển thị tối ưu trên mọi kích thước màn hình.',
    },
    {
      id: 27,
      noiDung: 'A Denial of Service (DoS) attack aims to make a network service unavailable by overwhelming it with fake traffic.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Tấn công từ chối dịch vụ (DoS/DDoS) làm tê liệt hệ thống bằng cách gửi lượng request khổng lồ.',
    },
    {
      id: 28,
      noiDung: 'SQL injection occurs when malicious SQL statements are inserted into entry fields for execution by the database.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Lỗ hổng SQL Injection cho phép kẻ tấn công can thiệp vào câu lệnh truy vấn CSDL.',
    },
    {
      id: 29,
      noiDung: 'Docker containers share the host operating system kernel and are lighter than full virtual machines.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Container chia sẻ kernel của hệ điều hành máy chủ nên khởi động nhanh và tiêu tốn ít RAM hơn máy ảo (VM).',
    },
    {
      id: 30,
      noiDung: 'Two-Factor Authentication (2FA) relies solely on a single memorized password for identity verification.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Xác thực 2 yếu tố (2FA) đòi hỏi 2 lớp bảo vệ khác nhau (ví dụ: mật khẩu + mã OTP qua điện thoại).',
    },

    // === 15 CÂU MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which of the following are relational database management systems (RDBMS)? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'PostgreSQL',
        B: 'Docker Engine',
        C: 'MySQL',
        D: 'Kubernetes',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: 'PostgreSQL và MySQL là các hệ quản trị CSDL quan hệ. Docker và Kubernetes là công cụ điều phối container.',
    },
    {
      id: 32,
      noiDung: 'Which of the following are widely used Frontend development frameworks or libraries? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'React.js',
        B: 'Next.js',
        C: 'Linux Kernel',
        D: 'Vue.js',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'React, Next.js và Vue.js là các công nghệ xây dựng giao diện người dùng Frontend. Linux là hệ điều hành.',
    },
    {
      id: 33,
      noiDung: 'Which of the following are essential cybersecurity best practices for developers? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Hashing passwords with strong algorithms like Argon2 or bcrypt',
        B: 'Validating and sanitizing all incoming user inputs',
        C: 'Disabling HTTPS to increase network speed',
        D: 'Restricting access with Role-Based Access Control (RBAC)',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Mã hóa băm mật khẩu (A), lọc input (B) và phân quyền RBAC (D) là các nguyên tắc bảo mật trọng yếu. Tắt HTTPS (C) là hành động nguy hiểm.',
    },
    {
      id: 34,
      noiDung: 'Which HTTP methods are commonly used in RESTful API architectures? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'GET',
        B: 'POST',
        C: 'DELETE',
        D: 'RUN',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'GET, POST, PUT, PATCH, DELETE là các phương thức HTTP chuẩn trong REST API. "RUN" không phải phương thức HTTP.',
    },
    {
      id: 35,
      noiDung: 'Which of the following are common software architecture design patterns? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Model-View-Controller (MVC)',
        B: 'Repository Pattern',
        C: 'Microservices Architecture',
        D: 'Keyboard Typing Pattern',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'MVC, Repository và Microservices là các mẫu kiến trúc và thiết kế phần mềm kinh điển.',
    },
    {
      id: 36,
      noiDung: 'Which of the following are prominent cloud computing service providers? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Amazon Web Services (AWS)',
        B: 'Google Cloud Platform (GCP)',
        C: 'Microsoft Azure',
        D: 'Photoshop Cloud Engine',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'AWS, GCP và Microsoft Azure là 3 nhà cung cấp hạ tầng điện toán đám mây lớn nhất thế giới.',
    },
    {
      id: 37,
      noiDung: 'Which of the following protocols operate at the transport layer of the internet protocol suite? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'TCP (Transmission Control Protocol)',
        B: 'UDP (User Datagram Protocol)',
        C: 'HTML',
        D: 'CSS',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'TCP và UDP là hai giao thức tầng giao vận (Transport Layer). HTML và CSS là ngôn ngữ đánh dấu và tạo kiểu web.',
    },
    {
      id: 38,
      noiDung: 'Select the primary benefits of automated unit testing: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Catching software regressions early in development',
        B: 'Facilitating safe code refactoring',
        C: 'Completely eliminating the need for developer code review',
        D: 'Providing living documentation of module behavior',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Unit test giúp phát hiện lỗi sớm (A), refactor an toàn (B) và đóng vai trò tài liệu đặc tả (D). Unit test không thay thế hoàn toàn được Code Review của con người.',
    },
    {
      id: 39,
      noiDung: 'Which Git commands are used for collaborating with remote repositories? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'git push',
        B: 'git pull',
        C: 'git fetch',
        D: 'git reboot',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Push (đẩy code lên), Pull (kéo code về), Fetch (cập nhật metadata từ remote). "git reboot" không tồn tại.',
    },
    {
      id: 40,
      noiDung: 'Which of the following are types of NoSQL databases? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Document stores (e.g., MongoDB)',
        B: 'Key-value stores (e.g., Redis)',
        C: 'Graph databases (e.g., Neo4j)',
        D: 'Punch card paper readers',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Document, Key-value, Graph là các phân loại chính của CSDL NoSQL.',
    },
    {
      id: 41,
      noiDung: 'Which factors directly impact website page loading speed and performance? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Image file size and optimization',
        B: 'Number of HTTP network requests',
        C: 'Server response time and caching mechanisms',
        D: 'The color of the computer monitor',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Kích thước ảnh (A), số lượng request (B) và thời gian phản hồi/cache của server (C) quyết định tốc độ tải trang.',
    },
    {
      id: 42,
      noiDung: 'Which of the following are core components of an operating system? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Kernel',
        B: 'Memory manager',
        C: 'File system manager',
        D: 'Social media feed algorithm',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Kernel (nhân), quản lý bộ nhớ và quản lý hệ thống tệp là các thành phần cốt lõi của hệ điều hành.',
    },
    {
      id: 43,
      noiDung: 'Which principles belong to the SOLID design principles in object-oriented programming? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'C1',
      luaChon: {
        A: 'Single Responsibility Principle',
        B: 'Open/Closed Principle',
        C: 'Liskov Substitution Principle',
        D: 'Fast Execution Rule',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'S (Single Responsibility), O (Open/Closed), L (Liskov Substitution), I (Interface Segregation), D (Dependency Inversion).',
    },
    {
      id: 44,
      noiDung: 'Which data formats are widely used for web data serialization and API data exchange? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'JSON (JavaScript Object Notation)',
        B: 'XML (eXtensible Markup Language)',
        C: 'MP3 Audio Stream',
        D: 'YAML',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'JSON, XML, YAML là các định dạng biểu diễn dữ liệu có cấu trúc trao đổi qua API. MP3 là định dạng âm thanh.',
    },
    {
      id: 45,
      noiDung: 'Which of the following threats are listed in the OWASP Top 10 web application vulnerabilities? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Injection attacks (e.g., SQLi, XSS)',
        B: 'Broken Authentication',
        C: 'Security Misconfiguration',
        D: 'Monitor Resolution Overload',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Injection, Broken Auth và Security Misconfiguration là các lỗ hổng an ninh ứng dụng web hàng đầu trong danh mục OWASP.',
    },
  ],
};
