import { CurriculumTopicBank } from './types';

export const MODAL_VERBS_BANK: CurriculumTopicBank = {
  key: 'MODAL_VERBS',
  tenChuDe: 'Động Từ Khuyết Thiếu (Modal Verbs)',
  aliases: [
    'khuyết thiếu',
    'khuyet thieu',
    'modal verb',
    'modal verbs',
    'modal',
    'can could may might must should',
    'động từ tình thái',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'You __________ wear a hard hat at all times inside the active construction zone; it is a strict legal requirement.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'must', B: 'might', C: 'could', D: 'would' },
      dapAnDung: 'A',
      giaiThich: '"Must" diễn tả quy định bắt buộc mang tính pháp lý hoặc an toàn.',
    },
    {
      id: 2,
      noiDung: 'Look at the clear blue sky! It __________ rain this afternoon.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'can\'t', B: 'must', C: 'should', D: 'needn\'t' },
      dapAnDung: 'A',
      giaiThich: '"Can\'t" dùng để suy luận chắc chắn điều gì KHÔNG THỂ xảy ra dựa trên bằng chứng hiển nhiên (trời trong xanh).',
    },
    {
      id: 3,
      noiDung: 'Sarah\'s car is parked outside her house, so she __________ be home right now.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'must', B: 'can', C: 'ought', D: 'shall' },
      dapAnDung: 'A',
      giaiThich: '"Must be" dùng để suy đoán chắc chắn tới 90-95% ở hiện tại dựa trên bằng chứng rõ ràng.',
    },
    {
      id: 4,
      noiDung: 'You __________ have spoken to your senior manager in such a disrespectful tone yesterday.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'shouldn\'t', B: 'mustn\'t', C: 'needn\'t', D: 'couldn\'t' },
      dapAnDung: 'A',
      giaiThich: '"Shouldn\'t have V3/ed" diễn tả lời chỉ trích, trách móc một hành động lẽ ra không nên làm trong quá khứ.',
    },
    {
      id: 5,
      noiDung: 'The final train has already departed, so we __________ take an expensive late-night taxi home.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'had to', B: 'must to', C: 'could to', D: 'should to' },
      dapAnDung: 'A',
      giaiThich: '"Had to" là dạng quá khứ của "must / have to" chỉ nghĩa vụ bắt buộc trong quá khứ do hoàn cảnh.',
    },
    {
      id: 6,
      noiDung: 'You __________ buy a ticket; entrance to this municipal museum is completely free on Sundays.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'needn\'t', B: 'mustn\'t', C: 'couldn\'t', D: 'shouldn\'t' },
      dapAnDung: 'A',
      giaiThich: '"Needn\'t / don\'t have to" chỉ sự không cần thiết (bảo tàng miễn phí nên không cần mua vé). "Mustn\'t" là cấm đoán.',
    },
    {
      id: 7,
      noiDung: 'Where are my car keys? — I am not sure, you __________ have left them in the conference room.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'might', B: 'must', C: 'should', D: 'can' },
      dapAnDung: 'A',
      giaiThich: '"Might / May have V3/ed" dùng để suy đoán một việc có thể đã xảy ra trong quá khứ với độ chắc chắn thấp (có "not sure").',
    },
    {
      id: 8,
      noiDung: '__________ you please pass me the salt cellar from the other end of the dining table?',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'Could', B: 'Should', C: 'Must', D: 'Shall' },
      dapAnDung: 'A',
      giaiThich: '"Could you please...?" là lời yêu cầu/nhờ vả lịch sự.',
    },
    {
      id: 9,
      noiDung: 'Students __________ smoke or vape anywhere on the school campus; violators will be suspended.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'mustn\'t', B: 'needn\'t', C: 'don\'t have to', D: 'might not' },
      dapAnDung: 'A',
      giaiThich: '"Mustn\'t" diễn tả sự cấm đoán tuyệt đối theo nội quy.',
    },
    {
      id: 10,
      noiDung: 'He __________ run a full marathon in under three hours when he was in his twenties.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'could', B: 'can', C: 'was able', D: 'might' },
      dapAnDung: 'A',
      giaiThich: '"Could" diễn tả khả năng chung chung trong quá khứ ("when he was in his twenties").',
    },
    {
      id: 11,
      noiDung: 'Despite the dense mountain fog, the alpine search team __________ locate the lost hikers.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'was able to', B: 'could', C: 'can', D: 'might' },
      dapAnDung: 'A',
      giaiThich: 'Để diễn tả việc xoay sở thành công làm được việc cụ thể trong một tình huống khó khăn trong quá khứ, ta dùng "was/were able to", không dùng "could".',
    },
    {
      id: 12,
      noiDung: 'It was a sunny day, so I __________ have carried that cumbersome heavy umbrella all afternoon.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'needn\'t', B: 'mustn\'t', C: 'couldn\'t', D: 'shouldn\'t' },
      dapAnDung: 'A',
      giaiThich: '"Needn\'t have V3/ed" diễn tả hành động đã làm trong quá khứ nhưng thực tế là không cần thiết.',
    },
    {
      id: 13,
      noiDung: '__________ we go for a walk in the botanical gardens after dinner tonight?',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'Shall', B: 'Will', C: 'Must', D: 'Would' },
      dapAnDung: 'A',
      giaiThich: '"Shall we...?" là câu đề nghị rủ ai cùng làm gì một cách nhẹ nhàng, lịch sự.',
    },
    {
      id: 14,
      noiDung: 'You __________ better consult an experienced tax accountant before filing this fiscal report.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'had', B: 'would', C: 'should', D: 'could' },
      dapAnDung: 'A',
      giaiThich: 'Cụm từ "Had better + V-inf" mang nghĩa "tốt hơn hết nên làm gì" (lời khuyên mạnh mẽ).',
    },
    {
      id: 15,
      noiDung: 'Mark didn\'t reply to my emails; he __________ have been extremely busy with his clinical surgery.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'must', B: 'can', C: 'should', D: 'shall' },
      dapAnDung: 'A',
      giaiThich: '"Must have V3/ed" dùng để suy đoán chắc chắn về một sự việc xảy ra trong quá khứ.',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: '"Mustn\'t" expresses strong prohibition, whereas "don\'t have to" expresses absence of obligation.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Mustn\'t" = không được phép làm (cấm đoán). "Don\'t have to" = không bắt buộc phải làm (tùy ý).',
    },
    {
      id: 17,
      noiDung: 'Modal verbs like "can", "must", and "should" add "-s" when used with third-person singular subjects (e.g., "He cans swim").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Động từ khuyết thiếu không bao giờ chia thêm "-s/-es" ở ngôi thứ ba số ít (phải là "He can swim").',
    },
    {
      id: 18,
      noiDung: '"Could have done" means someone had the ability or opportunity to do something in the past, but did not actually do it.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Could have V3/ed" chỉ khả năng trong quá khứ mà người đó đã không thực hiện.',
    },
    {
      id: 19,
      noiDung: 'The past tense of "must" when expressing personal necessity or obligation is "had to".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Must" không có dạng quá khứ riêng, khi lùi về quá khứ ta dùng "had to".',
    },
    {
      id: 20,
      noiDung: 'To express capability in a specific challenging situation in the past, "was able to" is required instead of "could".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Khả năng giải quyết một tình huống cụ thể trong quá khứ dùng "was/were able to" (= managed to).',
    },
    {
      id: 21,
      noiDung: '"Needn\'t have done" means that an action was done in the past, but it turned out to be completely unnecessary.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Needn\'t have done" nghĩa là đã làm rồi nhưng thực tế việc đó không cần thiết.',
    },
    {
      id: 22,
      noiDung: '"Can" is followed by a to-infinitive (e.g., "She can to speak fluent German").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Các động từ khuyết thiếu (can, could, must, should, may, might) luôn đi trực tiếp với Bare Infinitive (động từ nguyên mẫu không "to").',
    },
    {
      id: 23,
      noiDung: '"Ought to" carries approximately the same meaning of moral advice and recommendation as "should".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Ought to" đồng nghĩa với "should" (nên làm gì).',
    },
    {
      id: 24,
      noiDung: '"Can\'t have done" expresses a logical conclusion that an event was completely impossible in the past.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Can\'t have V3/ed" dùng để suy đoán chắc chắn điều gì KHÔNG THỂ đã xảy ra trong quá khứ.',
    },
    {
      id: 25,
      noiDung: 'In questions asking for suggestions with "I" and "we", "Shall" is standardly used (e.g., "Shall we dance?").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Shall I / Shall we...?" dùng để đưa ra lời đề nghị hoặc xin ý kiến.',
    },
    {
      id: 26,
      noiDung: 'The idiom "had better" refers strictly to a past event and cannot be applied to the present or future.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Dù có từ "had", nhưng "had better" dùng để khuyên cho HIỆN TẠI hoặc TƯƠNG LAI ("You had better leave now").',
    },
    {
      id: 27,
      noiDung: '"May" and "Might" both express possibility, with "might" generally expressing slightly lower probability.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Cả hai đều chỉ khả năng có thể xảy ra, trong đó "might" mang xác suất thấp hơn một chút so với "may".',
    },
    {
      id: 28,
      noiDung: 'The negative form of "had better" is "hadn\'t better".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Phủ định của "had better" là "HAD BETTER NOT" (không dùng "hadn\'t better").',
    },
    {
      id: 29,
      noiDung: '"Would rather" expresses personal preference and is followed by a bare infinitive (e.g., "I would rather stay home").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Would rather + V-bare" (thích/thà làm gì hơn).',
    },
    {
      id: 30,
      noiDung: 'Modal verbs require auxiliary verbs like "do" or "does" to form negative sentences (e.g., "He doesn\'t can swim").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Động từ khuyết thiếu tự thêm "not" vào sau (cannot, shouldn\'t, mustn\'t), không mượn trợ động từ do/does.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which modal verbs can express logical deduction or certainty about present facts? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Must (chắc hẳn là)',
        B: 'Can\'t (chắc chắn không phải là)',
        C: 'Shall (chắc chắn là trong toán học)',
        D: 'Might (có thể là)',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Must, Can\'t, Might là các động từ tình thái chỉ mức độ suy đoán logic từ cao đến thấp.',
    },
    {
      id: 32,
      noiDung: 'Which modal expressions indicate that an action was NOT necessary? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Didn\'t need to do (không cần làm và đã không làm)',
        B: 'Needn\'t have done (đã làm nhưng thực ra không cần thiết)',
        C: 'Must have done',
        D: 'Don\'t have to do (hiện tại không bắt buộc)',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Didn\'t need to, Needn\'t have done, Don\'t have to đều diễn tả việc không có nghĩa vụ/không cần thiết.',
    },
    {
      id: 33,
      noiDung: 'Select all modal verbs that can be used to make polite requests: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Could you please help me?',
        B: 'Would you mind helping me?',
        C: 'Can you give me a hand?',
        D: 'Must you give me that now?',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Could, Would, Can là các modal verbs thông dụng để đưa ra lời yêu cầu lịch sự. D là câu phàn nàn/chất vấn.',
    },
    {
      id: 34,
      noiDung: 'Which sentences illustrate correct modal perfect structures (Modal + have + V3)? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'He must have forgotten his smartphone at the restaurant.',
        B: 'She could have passed the test if she had studied harder.',
        C: 'They should have notified us about the delay.',
        D: 'He must have forget his smartphone.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C đúng cấu trúc Modal + have + V3/ed. D sai vì "forget" chưa chia phân từ hai "forgotten".',
    },
    {
      id: 35,
      noiDung: 'Which sentences correctly use "mustn\'t" to show prohibition? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'You mustn\'t photograph classified military installations.',
        B: 'Pedestrians mustn\'t cross the street against the red light.',
        C: 'You mustn\'t come if you are too tired; it\'s your choice.',
        D: 'Visitors mustn\'t touch the ancient fragile manuscripts.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là các lệnh cấm đoán theo luật/quy định. C sai vì mang nghĩa không bắt buộc thì phải dùng "don\'t have to", không dùng "mustn\'t".',
    },
    {
      id: 36,
      noiDung: 'Which of the following semi-modal verbs take a to-infinitive? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Ought to',
        B: 'Have to',
        C: 'Used to',
        D: 'Should to',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Ought to, Have to, Used to đi với to-infinitive. "Should" không bao giờ đi với "to".',
    },
    {
      id: 37,
      noiDung: 'Select all sentences with grammatical errors regarding modal verbs: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'She musts submit her dissertation by Friday.',
        B: 'I can to swim very well.',
        C: 'You had better not drink and drive.',
        D: 'He ought to apologize for his rude remark.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A sai ("musts" thừa s). B sai ("can to swim" thừa to). C và D hoàn toàn đúng.',
    },
    {
      id: 38,
      noiDung: 'Which modals can express formal permission? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'May I enter the examination hall?',
        B: 'Could I borrow your fountain pen for a moment?',
        C: 'Can I leave the meeting early, Sir?',
        D: 'Must I speak loudly?',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'May, Could, Can được dùng để xin phép (trong đó May và Could trang trọng và lịch sự nhất).',
    },
    {
      id: 39,
      noiDung: 'Which expressions describe past habits that no longer happen in the present? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Used to play soccer every afternoon',
        B: 'Would spend every summer vacation by the seaside',
        C: 'Be used to playing soccer every afternoon',
        D: 'Get used to spending summer vacations',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: '"Used to + V" và "Would + V" diễn tả thói quen trong quá khứ đã chấm dứt. "Be/Get used to V-ing" là quen với việc gì ở hiện tại.',
    },
    {
      id: 40,
      noiDung: 'Which sentences correctly illustrate "would rather"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'I would rather stay home tonight than go to the cinema.',
        B: 'I would rather you didn\'t smoke inside the apartment.',
        C: 'She would rather to study abroad.',
        D: 'He would rather drink green tea than black coffee.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A và D đúng cấu trúc "would rather + V-bare than V-bare". B đúng cấu trúc giả định "would rather S + V-past". C sai vì sau would rather không dùng "to".',
    },
    {
      id: 41,
      noiDung: 'Select all contexts where "CAN" cannot be used and must be replaced by "BE ABLE TO": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'In the Future Simple: I will be able to speak fluent English next year.',
        B: 'In the Present Perfect: She has been able to solve three math problems.',
        C: 'After infinitive verbs: I want to be able to play the violin.',
        D: 'In the Present Simple: I can swim.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: '"Can" không có dạng tương lai (will can), hoàn thành (have canned) hay to-infinitive, nên ở A, B, C bắt buộc phải dùng "be able to".',
    },
    {
      id: 42,
      noiDung: 'Which sentences convey criticism about past failure or negligence? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'You should have backed up your computer files before reinstalling.',
        B: 'They ought to have warned us about the hazardous blizzard.',
        C: 'You must have backed up your computer files.',
        D: 'You shouldn\'t have disclosed confidential passwords to strangers.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Should have / Ought to have / Shouldn\'t have diễn tả lời trách móc, chỉ trích việc đã qua. C là câu suy đoán logic.',
    },
    {
      id: 43,
      noiDung: 'Which modal verbs express advice or recommendations? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'You should drink plenty of water.',
        B: 'You ought to get eight hours of sleep.',
        C: 'You had better see a doctor right away.',
        D: 'You must not exist.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Should, Ought to, Had better là các cấu trúc đưa ra lời khuyên hữu ích.',
    },
    {
      id: 44,
      noiDung: 'Select all sentences correctly using "can\'t have done": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'He can\'t have committed the crime because he was in Paris that entire week.',
        B: 'She can\'t have passed the bar exam; she didn\'t even study for one hour.',
        C: 'They can\'t have arrived already; their flight only took off 20 minutes ago.',
        D: 'He can\'t have went to the hospital yesterday.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C suy luận chắc chắn điều không thể xảy ra dựa trên bằng chứng xác thực. D sai vì phân từ hai của go là "gone", không dùng "went".',
    },
    {
      id: 45,
      noiDung: 'Which phrases express willingness or habitual actions in the past? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Every evening, grandfather would sit on the porch and tell us folk tales.',
        B: 'The car wouldn\'t start no matter how many times I turned the key.',
        C: 'I would help you if I had more free time.',
        D: 'We must start at 8 AM.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A diễn tả thói quen lặp đi lặp lại trong quá khứ ("would sit"). B diễn tả sự từ chối/bướng bỉnh của đồ vật ("wouldn\'t start"). C là câu điều kiện loại 2.',
    },
  ],
};
