import { CurriculumTopicBank } from './types';

export const PASSIVE_VOICE_BANK: CurriculumTopicBank = {
  key: 'PASSIVE_VOICE',
  tenChuDe: 'Câu Bị Động Nâng Cao (Passive Voice)',
  aliases: [
    'bị động',
    'bi dong',
    'passive voice',
    'passive',
    'câu bị động',
    'cau bi dong',
    'bị động nâng cao',
    'bị động đặc biệt',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'The renovated academic auditorium __________ by the school board next Monday morning.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'will inaugurate', B: 'will be inaugurated', C: 'is inaugurated', D: 'was inaugurated' },
      dapAnDung: 'B',
      giaiThich: 'Câu bị động ở thì tương lai đơn ("next Monday morning"): S + will be + V3/ed.',
    },
    {
      id: 2,
      noiDung: 'It __________ that regular cardiovascular exercise significantly improves cognitive brain functions.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'believes', B: 'is believed', C: 'was believing', D: 'believed' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc bị động khách quan / bị động với động từ chỉ ý kiến: "It is believed that + clause".',
    },
    {
      id: 3,
      noiDung: 'The famous tech entrepreneur is reported __________ millions of dollars to AI cancer research last year.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'to donate', B: 'to have donated', C: 'donating', D: 'having donated' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc bị động: "S + is reported + to have V3/ed" khi hành động quyên góp ("last year") xảy ra trước thời điểm tường thuật.',
    },
    {
      id: 4,
      noiDung: 'The legal agreement must __________ by authorized representatives of both corporations before 5 PM.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'sign', B: 'be signed', C: 'signed', D: 'being signed' },
      dapAnDung: 'B',
      giaiThich: 'Bị động với động từ khuyết thiếu (Modal verbs): modal + be + V3/ed.',
    },
    {
      id: 5,
      noiDung: 'When we arrived at the laboratory, the final chemical compound __________ by the technicians.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'was being analyzed', B: 'analyzed', C: 'is analyzed', D: 'has analyzed' },
      dapAnDung: 'A',
      giaiThich: 'Câu bị động ở thì Quá khứ tiếp diễn: S + was/were + being + V3/ed.',
    },
    {
      id: 6,
      noiDung: 'He doesn\'t like __________ what to do in his personal life.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'telling', B: 'being told', C: 'to tell', D: 'be told' },
      dapAnDung: 'B',
      giaiThich: 'Dạng bị động của danh động từ sau "like": "like being + V3/ed" (thích/không thích bị ai nói làm gì).',
    },
    {
      id: 7,
      noiDung: 'The ancient stone castle __________ severely __________ by enemy artillery in the 17th century.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'was / damaged', B: 'is / damaged', C: 'has / damaged', D: 'were / damaged' },
      dapAnDung: 'A',
      giaiThich: 'Bị động quá khứ đơn ("in the 17th century"): S + was/were + V3/ed. Chủ ngữ "castle" số ít dùng "was damaged".',
    },
    {
      id: 8,
      noiDung: 'I need to __________ my car serviced before setting off on the cross-country trip.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'have', B: 'make', C: 'do', D: 'let' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc nhờ bảo thể bị động: "have + something + V3/ed" (nhờ ai làm gì đó cho mình).',
    },
    {
      id: 9,
      noiDung: 'The criminal is thought __________ the border using a forged diplomat passport three days ago.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'C1',
      luaChon: { A: 'to cross', B: 'to have crossed', C: 'crossing', D: 'having crossed' },
      dapAnDung: 'B',
      giaiThich: 'Hành động vượt biên xảy ra trước thời điểm hiện tại ("three days ago"), dùng "to have crossed".',
    },
    {
      id: 10,
      noiDung: 'This delicate surgical operation needs __________ with the highest precision.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'performing', B: 'to be performed', C: 'both A and B', D: 'to perform' },
      dapAnDung: 'C',
      giaiThich: '"Need" mang nghĩa bị động cho vật có 2 cấu trúc tương đương: "need V-ing" hoặc "need to be V3/ed".',
    },
    {
      id: 11,
      noiDung: 'No official announcements __________ regarding the CEO\'s sudden resignation so far.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'have been made', B: 'were made', C: 'are making', D: 'have made' },
      dapAnDung: 'A',
      giaiThich: 'Dấu hiệu "so far" dùng thì Hiện tại hoàn thành bị động: "have/has been + V3/ed". Chủ ngữ số nhiều "announcements".',
    },
    {
      id: 12,
      noiDung: 'He was made __________ the complete confidential inventory before he was allowed to leave.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'sign', B: 'to sign', C: 'signing', D: 'signed' },
      dapAnDung: 'B',
      giaiThich: 'Ở thể chủ động: "make someone do something". Khi chuyển sang bị động: "be made to do something".',
    },
    {
      id: 13,
      noiDung: 'The stolen diamonds are believed __________ hidden in an underground vault.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'to be', B: 'being', C: 'be', D: 'to have' },
      dapAnDung: 'A',
      giaiThich: 'Hành động đang tồn tại ở hiện tại: "S + are believed to be + adj/V3".',
    },
    {
      id: 14,
      noiDung: 'By the time the rescue helicopter landed, all survivors __________ to safety.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'had been transported', B: 'were transported', C: 'have been transported', D: 'would be transported' },
      dapAnDung: 'A',
      giaiThich: 'Hành động hoàn thành trước một mốc trong quá khứ ("By the time... landed") dùng Quá khứ hoàn thành bị động: "had been + V3".',
    },
    {
      id: 15,
      noiDung: 'English __________ in almost every educational curriculum across the globe.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'teaches', B: 'is taught', C: 'taught', D: 'is teaching' },
      dapAnDung: 'B',
      giaiThich: 'Câu bị động Hiện tại đơn diễn tả sự thật hiển nhiên: S + is/am/are + V3/ed.',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'Intransitive verbs such as "arrive", "die", and "disappear" cannot form a passive voice sentence.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Nội động từ (intransitive verbs) không có tân ngữ trực tiếp nên không thể chuyển sang câu bị động.',
    },
    {
      id: 17,
      noiDung: 'In passive voice, "by + agent" is always obligatory and must never be omitted under any circumstance.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Khi tác nhân không xác định (someone, people) hoặc không quan trọng, ta thường lược bỏ "by + agent".',
    },
    {
      id: 18,
      noiDung: 'The causative structure "have something done" means arranging for someone else to perform a service.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Cấu trúc truyền khiến bị động "have/get something done" chỉ việc thuê/nhờ người khác làm gì cho mình.',
    },
    {
      id: 19,
      noiDung: 'Active sentence: "They made him apologize" becomes passive: "He was made apologize".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Câu bị động của "make" bắt buộc phải thêm "to": "He was made TO apologize".',
    },
    {
      id: 20,
      noiDung: 'Impersonal passive "It is said that S + V" can be transformed into "S is said to + V-inf".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Đây là hai dạng biến đổi tương đương của câu bị động khách quan.',
    },
    {
      id: 21,
      noiDung: 'The passive voice of the Present Continuous tense is formed using "am/is/are + being + past participle".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Công thức bị động Hiện tại tiếp diễn: S + is/am/are + being + V3/ed.',
    },
    {
      id: 22,
      noiDung: 'Sentences with two objects (direct and indirect) can typically yield two different passive voice variations.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Ví dụ: "They gave her a prize" -> "She was given a prize" hoặc "A prize was given to her".',
    },
    {
      id: 23,
      noiDung: 'The past participle of the verb "build" is "builded".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Quá khứ phân từ của "build" là "built".',
    },
    {
      id: 24,
      noiDung: 'For things, "need cleaning" and "need to be cleaned" carry equivalent passive meaning.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Đối với vật: "need + V-ing" = "need + to be V3/ed" (mang nghĩa cần được làm gì).',
    },
    {
      id: 25,
      noiDung: 'Verbs like "let" in the active become "be let to do" in standard passive English.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Let" không dùng ở thể bị động "be let to", thay vào đó người ta dùng "be allowed / permitted to do".',
    },
    {
      id: 26,
      noiDung: 'The preposition "with" is preferred over "by" when referring to the tool, instrument, or material used to perform an action.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "By" đi với người thực hiện, "with" đi với công cụ/vật liệu (vd: The bread was cut with a knife).',
    },
    {
      id: 27,
      noiDung: 'The Future Continuous tense has a widely used standard passive form: "will be being V3".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Các thì tương lai tiếp diễn và các thì hoàn thành tiếp diễn thường tránh dùng ở thể bị động vì cấu trúc quá nặng nề.',
    },
    {
      id: 28,
      noiDung: 'In academic writing, passive voice is commonly utilized to maintain objective and impersonal tone.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Văn phong học thuật rất chuộng thể bị động để làm nổi bật kết quả nghiên cứu hơn là người thực hiện.',
    },
    {
      id: 29,
      noiDung: 'Active: "Nobody saw him leave" becomes passive: "He was not seen to leave".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Khi chủ từ chủ động là "Nobody", câu bị động chuyển thành thể phủ định "He was not seen...".',
    },
    {
      id: 30,
      noiDung: 'The phrase "get married" is an example of a get-passive expressing a change of state.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Get + past participle" (get dressed, get married, get lost) là dạng bị động thông dụng chỉ sự chuyển đổi trạng thái.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which verbs CANNOT be transformed into the passive voice because they are intransitive? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Happen',
        B: 'Disappear',
        C: 'Destroy',
        D: 'Occur',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Happen, Disappear, Occur là các nội động từ không có tân ngữ nên không thể chia bị động. Destroy là ngoại động từ.',
    },
    {
      id: 32,
      noiDung: 'Which of the following sentences represent grammatically correct passive voice constructions? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The old bridge is being demolished by demolition crews.',
        B: 'All conference participants were provided with comprehensive itineraries.',
        C: 'The letter was wrote by our executive director.',
        D: 'The new policy has been implemented across all departments.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D chia bị động đúng. C sai vì phân từ hai của write là "written", không dùng "wrote".',
    },
    {
      id: 33,
      noiDung: 'Select all correct passive transformations of: "People say that she speaks seven languages fluently." (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'It is said that she speaks seven languages fluently.',
        B: 'She is said to speak seven languages fluently.',
        C: 'She is said speaking seven languages fluently.',
        D: 'It was said that she spoke seven languages fluently.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A (dùng It is said that) và B (dùng S + is said to V) là hai dạng bị động khách quan chuẩn. C sai cấu trúc, D sai thì (đang là says hiện tại).',
    },
    {
      id: 34,
      noiDung: 'Which sentences illustrate the causative passive structure ("have/get something done")? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'I had my air conditioner repaired yesterday afternoon.',
        B: 'She is getting her teeth whitened at the dental clinic.',
        C: 'He had cleaned the kitchen before his mother returned.',
        D: 'They had their wedding photos taken by a professional photographer.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là cấu trúc truyền khiến bị động (have/get + sth + V3). C là thì Quá khứ hoàn thành chủ động.',
    },
    {
      id: 35,
      noiDung: 'Which prepositions are appropriately used with passive verbs in the following contexts? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The mountain summit was covered with thick snow.',
        B: 'The suspect was arrested by undercover police detectives.',
        C: 'The statue was carved by a sharp chisel.',
        D: 'The cake was made with organic flour and honey.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A (covered with), B (arrested by agent), D (made with ingredients). C sai vì với dụng cụ phải dùng "carved with a chisel", không dùng "by".',
    },
    {
      id: 36,
      noiDung: 'Select all sentences containing a grammatical error in passive construction: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'He was let leave the room early.',
        B: 'The accident was happened at 8 PM yesterday.',
        C: 'The missing child was found safe and sound.',
        D: 'She was made to rewrite the essay three times.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A sai ("let" không chia bị động, phải dùng was allowed to leave). B sai ("happen" là nội động từ không chia bị động). C và D đúng.',
    },
    {
      id: 37,
      noiDung: 'Which reporting verbs can be used in impersonal passive structures ("It is ... that")? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Believed',
        B: 'Estimated',
        C: 'Expected',
        D: 'Dined',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'It is believed / estimated / expected that... là các cấu trúc bị động khách quan quen thuộc. "Dined" (ăn tối) không dùng trong cấu trúc này.',
    },
    {
      id: 38,
      noiDung: 'Which sentences correctly transform active sentences with perception verbs (see, hear) into passive? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'They saw him enter the bank. -> He was seen to enter the bank.',
        B: 'They heard her singing in the room. -> She was heard singing in the room.',
        C: 'They saw him enter the bank. -> He was seen enter the bank.',
        D: 'We heard the explosion echo. -> The explosion was heard to echo.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Động từ tri giác ở bị động: nếu đi với bare infinitive thì chuyển thành "to V" (A, D); nếu đi với V-ing thì giữ nguyên V-ing (B). C sai vì thiếu "to".',
    },
    {
      id: 39,
      noiDung: 'Select all passive sentences where the agent "by ..." can be naturally omitted: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The robber was arrested (by the police).',
        B: 'Spanish is spoken in many Latin American countries (by people).',
        C: 'The Mona Lisa was painted by Leonardo da Vinci.',
        D: 'My bicycle was stolen last night (by someone).',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A (hiển nhiên là cảnh sát bắt), B (hiển nhiên là con người nói), D (kẻ trộm không rõ danh tính). C bắt buộc phải giữ lại tác giả nổi tiếng "by Leonardo da Vinci".',
    },
    {
      id: 40,
      noiDung: 'Which of the following demonstrate correct passive forms across different tenses? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Present Perfect: has been repaired',
        B: 'Past Continuous: was being renovated',
        C: 'Past Perfect: had been inspected',
        D: 'Future Simple: will been delivered',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C đúng công thức bị động. D sai vì tương lai đơn bị động là "will BE delivered", không phải "will been".',
    },
    {
      id: 41,
      noiDung: 'Which sentences correctly use passive infinitives ("to be V3" or "to have been V3")? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The applicant hopes to be invited for an in-person interview.',
        B: 'He claimed to have been unfairly dismissed by his former employer.',
        C: 'She wants to be promote next month.',
        D: 'The package was supposed to be delivered this morning.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A (to be invited), B (to have been dismissed), D (to be delivered) đúng. C sai vì sau "to be" phải là phân từ hai "promoted", không dùng "promote".',
    },
    {
      id: 42,
      noiDung: 'Select all sentences correctly demonstrating "get-passive": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Several passengers got injured in the minor collision.',
        B: 'Don\'t leave your phone on the bench; it might get stolen.',
        C: 'He got fired for repeatedly breaching company policies.',
        D: 'She got happily yesterday morning.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (got injured), B (get stolen), C (got fired) là get-passive chuẩn. D là câu dùng trạng từ sai.',
    },
    {
      id: 43,
      noiDung: 'Which sentences correctly transform passive questions? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Has the parcel been dispatched yet?',
        B: 'Was the contract signed yesterday?',
        C: 'Did the contract be signed yesterday?',
        D: 'Will the results be announced tomorrow?',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D đặt câu hỏi bị động chuẩn. C sai ngữ pháp vì không đảo trợ động từ "Did" trong câu bị động ("Was the contract signed...").',
    },
    {
      id: 44,
      noiDung: 'Which passive constructions express necessity or obligation for inanimate objects? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The carpet needs vacuuming.',
        B: 'The carpet needs to be vacuumed.',
        C: 'The carpet needs to vacuum.',
        D: 'The windows require washing.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Need/Require + V-ing hoặc Need + to be V3 đều mang nghĩa bị động. C sai vì "need to vacuum" mang nghĩa chủ động cho người.',
    },
    {
      id: 45,
      noiDung: 'Select all sentences where the agent is introduced with "by" correctly: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'The law was passed by parliament after intense debate.',
        B: 'Romeo and Juliet was written by William Shakespeare.',
        C: 'The room was painted by a roller brush.',
        D: 'The goal was scored by the striker in the final minute.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D chỉ tác nhân gây ra hành động (parliament, Shakespeare, the striker). C sai vì dụng cụ quét sơn phải dùng "with a roller brush".',
    },
  ],
};
