import { CurriculumTopicBank } from './types';

export const PHRASAL_VERBS_BANK: CurriculumTopicBank = {
  key: 'PHRASAL_VERBS',
  tenChuDe: 'Cụm Động Từ Thông Dụng (Common Phrasal Verbs)',
  aliases: [
    'cụm động từ',
    'cum dong tu',
    'phrasal verb',
    'phrasal verbs',
    'phrasal',
    'động từ ghép',
    'dong tu ghep',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'Never __________ your ambitions merely because the journey seems demanding and long.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'give up', B: 'look after', C: 'put off', D: 'turn down' },
      dapAnDung: 'A',
      giaiThich: '"Give up" nghĩa là từ bỏ, buông xuôi ước mơ/mục tiêu.',
    },
    {
      id: 2,
      noiDung: 'Due to severe weather conditions, the center had to __________ the outdoor speaking festival until next weekend.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'call off', B: 'put off', C: 'bring up', D: 'run into' },
      dapAnDung: 'B',
      giaiThich: '"Put off" nghĩa là hoãn lại, dời sang thời gian sau (phân biệt với "call off" là hủy hẳn).',
    },
    {
      id: 3,
      noiDung: 'Whenever you encounter an unfamiliar term in the text, you can __________ it in the Cambridge dictionary.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'look up', B: 'look after', C: 'look for', D: 'look forward' },
      dapAnDung: 'A',
      giaiThich: '"Look up" nghĩa là tra cứu thông tin (trong từ điển, danh bạ, tài liệu).',
    },
    {
      id: 4,
      noiDung: 'She had to __________ the lucrative job offer because the daily commute was over two hours each way.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'turn on', B: 'turn down', C: 'turn up', D: 'turn off' },
      dapAnDung: 'B',
      giaiThich: '"Turn down" nghĩa là từ chối một lời mời hoặc một đề xuất công việc.',
    },
    {
      id: 5,
      noiDung: 'I accidentally __________ my former high school teacher while browsing at the downtown bookstore.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'ran into', B: 'took off', C: 'got over', D: 'broke down' },
      dapAnDung: 'A',
      giaiThich: '"Run into someone" nghĩa là tình cờ bắt gặp ai đó.',
    },
    {
      id: 6,
      noiDung: 'Please remember to __________ your shoes before entering the traditional Japanese tatami room.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'take off', B: 'take in', C: 'take on', D: 'take out' },
      dapAnDung: 'A',
      giaiThich: '"Take off" nghĩa là cởi (giày, dép, quần áo) hoặc máy bay cất cánh.',
    },
    {
      id: 7,
      noiDung: 'It took the athlete several months to __________ the physical exhaustion and emotional grief of the defeat.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'get over', B: 'get through', C: 'get on', D: 'get away' },
      dapAnDung: 'A',
      giaiThich: '"Get over" nghĩa là vượt qua, bình phục sau một cú sốc tâm lý hoặc cơn bệnh.',
    },
    {
      id: 8,
      noiDung: 'The car suddenly __________ on the highway, forcing us to call emergency roadside assistance.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'broke down', B: 'broke up', C: 'broke in', D: 'broke out' },
      dapAnDung: 'A',
      giaiThich: '"Break down" nghĩa là (máy móc, xe cộ) bị hỏng, ngừng hoạt động.',
    },
    {
      id: 9,
      noiDung: 'We are truly __________ spending the summer holiday with our grandparents in the countryside.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'looking forward to', B: 'looking up to', C: 'looking out for', D: 'looking down on' },
      dapAnDung: 'A',
      giaiThich: '"Look forward to + V-ing" nghĩa là háo hức mong chờ điều gì.',
    },
    {
      id: 10,
      noiDung: 'Don\'t throw away that old wooden crate; we can __________ it into a rustic coffee table.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'turn', B: 'make', C: 'keep', D: 'hold' },
      dapAnDung: 'A',
      giaiThich: '"Turn into" nghĩa là biến thành, chuyển hóa thành thứ khác.',
    },
    {
      id: 11,
      noiDung: 'The firefighters fought relentlessly for six hours to __________ the raging forest fire.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'put out', B: 'put off', C: 'put away', D: 'put up' },
      dapAnDung: 'A',
      giaiThich: '"Put out" nghĩa là dập tắt (ngọn lửa, thuốc lá, đèn).',
    },
    {
      id: 12,
      noiDung: 'He really __________ his father in both his meticulous work ethic and calm temperament.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'takes after', B: 'takes over', C: 'takes apart', D: 'takes on' },
      dapAnDung: 'A',
      giaiThich: '"Take after someone" nghĩa là giống ai đó (về ngoại hình hoặc tính cách).',
    },
    {
      id: 13,
      noiDung: 'The detective tried to __________ who had accessed the computer server during the blackout.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'find out', B: 'carry out', C: 'figure into', D: 'bring out' },
      dapAnDung: 'A',
      giaiThich: '"Find out" nghĩa là tìm ra, khám phá ra thông tin sự thật.',
    },
    {
      id: 14,
      noiDung: 'Our office ran __________ high-grade printing paper, so we had to order a new bulk supply.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'out of', B: 'into', C: 'away from', D: 'up to' },
      dapAnDung: 'A',
      giaiThich: '"Run out of something" nghĩa là cạn kiệt, dùng hết cái gì.',
    },
    {
      id: 15,
      noiDung: 'She has always __________ her elder sister as a role model of resilience and grace.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'looked up to', B: 'looked down on', C: 'looked out for', D: 'looked over' },
      dapAnDung: 'A',
      giaiThich: '"Look up to someone" nghĩa là ngưỡng mộ, kính trọng ai đó.',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'The phrasal verb "call off" means to cancel an event, while "put off" means to postpone it to a later time.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Call off" là hủy bỏ hoàn toàn, "put off" là hoãn lại thời điểm sau.',
    },
    {
      id: 17,
      noiDung: 'In separable phrasal verbs, when the object is a pronoun (him, her, it, them), it must be placed between the verb and the particle.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Với cụm động từ tách được, nếu tân ngữ là đại từ thì bắt buộc kẹp ở giữa (vd: "turn it on", không được nói "turn on it").',
    },
    {
      id: 18,
      noiDung: '"Take off" can describe both an aircraft ascending into flight and a person removing an item of clothing.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Take off" có cả hai nghĩa thông dụng: máy bay cất cánh và cởi bỏ trang phục.',
    },
    {
      id: 19,
      noiDung: 'The phrase "look forward to" must be followed by a bare infinitive verb (e.g., "I look forward to hear from you").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "To" ở đây là giới từ nên bắt buộc đi với V-ing hoặc danh từ ("look forward to hearing from you").',
    },
    {
      id: 20,
      noiDung: '"Give in" means to surrender or reluctantly agree to a demand after prolonged resistance.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Give in" nghĩa là nhượng bộ, đầu hàng trước áp lực.',
    },
    {
      id: 21,
      noiDung: 'The expression "make up for" means to compensate for something lost, missing, or inadequate.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Make up for" nghĩa là đền bù, bù đắp cho điều gì.',
    },
    {
      id: 22,
      noiDung: 'All English phrasal verbs are separable and can take nouns between the verb and the particle.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Rất nhiều cụm động từ là không thể tách rời (inseparable), ví dụ: "run into someone", "look after someone".',
    },
    {
      id: 23,
      noiDung: '"Look down on" someone means to respect and hold them in high esteem.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Look down on" nghĩa là coi thường, khinh miệt người khác. Tôn trọng là "look up to".',
    },
    {
      id: 24,
      noiDung: 'To "carry out" a survey means to perform or execute that survey systematically.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Carry out" nghĩa là tiến hành, thực thi (nghiên cứu, khảo sát, kế hoạch).',
    },
    {
      id: 25,
      noiDung: '"Come across" can mean discovering something unexpectedly or making a particular personal impression.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Come across" vừa có nghĩa tình cờ thấy cái gì, vừa có nghĩa tạo ấn tượng ban đầu (come across as friendly).',
    },
    {
      id: 26,
      noiDung: '"Hold on" is commonly used on telephone calls to request that the caller wait a brief moment.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Hold on" trong hội thoại điện thoại mang nghĩa "giữ máy một chút".',
    },
    {
      id: 27,
      noiDung: '"Bring up" can refer to raising a child as well as introducing a topic for discussion.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Bring up" mang cả hai nghĩa: nuôi nấng con cái và nêu ra một chủ đề để thảo luận.',
    },
    {
      id: 28,
      noiDung: 'The sentence "Please turn off it" is completely natural and grammatically flawless.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Với đại từ "it", bắt buộc phải kẹp giữa: "Please turn it off".',
    },
    {
      id: 29,
      noiDung: '"Check in" and "check out" are customary phrasal verbs used at hotels and airports.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Check in (làm thủ tục vào/nhận phòng), Check out (làm thủ tục ra/trả phòng).',
    },
    {
      id: 30,
      noiDung: 'Three-word phrasal verbs (e.g., "get along with", "catch up with") are virtually always inseparable.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Cụm động từ 3 từ (verb + adverb + preposition) gần như luôn là không thể tách rời.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which of the following phrasal verbs contain the verb "LOOK"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Look after (chăm sóc)',
        B: 'Look forward to (trông đợi)',
        C: 'Look into (điều tra, nghiên cứu)',
        D: 'Look down (nhìn thẳng phía trước)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C là các cụm động từ rất thông dụng với "Look". D không mang nghĩa là nhìn thẳng.',
    },
    {
      id: 32,
      noiDung: 'Which phrasal verbs can mean "to stop doing or having something"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Give up',
        B: 'Break into',
        C: 'Drop out of',
        D: 'Take up',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: '"Give up" (từ bỏ) và "Drop out of" (bỏ học, rút lui) đều chỉ việc dừng lại. "Break into" là đột nhập, "Take up" là bắt đầu một sở thích.',
    },
    {
      id: 33,
      noiDung: 'Which sentences use separable phrasal verbs correctly? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'She turned on the computer.',
        B: 'She turned the computer on.',
        C: 'She turned it on.',
        D: 'She turned on it.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C đều đúng ngữ pháp. D sai vì đại từ "it" bắt buộc phải kẹp giữa verb và particle ("turned it on").',
    },
    {
      id: 34,
      noiDung: 'Which phrasal verbs relate to telephone or online conversations? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Hang up (cúp máy)',
        B: 'Cut off (mất kết nối đột ngột)',
        C: 'Put through (nối máy cho ai)',
        D: 'Check in (nhận phòng khách sạn)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Hang up, Cut off, Put through là các thuật ngữ chuyên môn trong giao tiếp điện thoại.',
    },
    {
      id: 35,
      noiDung: 'Select all phrasal verbs meaning "to tolerate or endure": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Put up with',
        B: 'Bear with',
        C: 'Look up to',
        D: 'Run out of',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: '"Put up with" và "Bear with" đều mang nghĩa chịu đựng, kiên nhẫn với ai/điều gì.',
    },
    {
      id: 36,
      noiDung: 'Which phrasal verbs are INSEPARABLE? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Run into (tình cờ gặp)',
        B: 'Look after (chăm sóc)',
        C: 'Come across (tình cờ thấy)',
        D: 'Turn off (tắt thiết bị)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Run into, Look after, Come across không bao giờ tách rời tân ngữ (không nói "run him into"). "Turn off" là tách được.',
    },
    {
      id: 37,
      noiDung: 'Which expressions describe interpersonal relationships between friends or colleagues? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Get along with someone',
        B: 'Fall out with someone',
        C: 'Make up with someone',
        D: 'Put out with someone',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Get along with (hòa hợp), Fall out with (cãi vã, bất hòa), Make up with (làm hòa). "Put out with" không có nghĩa quan hệ bạn bè.',
    },
    {
      id: 38,
      noiDung: 'Select all correct meanings of the phrasal verb "WORK OUT": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'To exercise physically at the gym',
        B: 'To solve or find a solution to a problem',
        C: 'To develop or progress successfully',
        D: 'To completely demolish a building',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: '"Work out" có nhiều nghĩa: tập thể dục (A), tìm ra giải pháp/tính toán (B), phát triển suôn sẻ (C). D là tear down/demolish.',
    },
    {
      id: 39,
      noiDung: 'Which phrasal verbs describe starting or initiating an activity? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Take up a new hobby',
        B: 'Set up a new business',
        C: 'Give up smoking',
        D: 'Embark on a new career',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Take up (bắt đầu thói quen), Set up (thành lập), Embark on (khởi hành/bắt tay vào). "Give up" là từ bỏ.',
    },
    {
      id: 40,
      noiDung: 'Which phrasal verbs use the particle "OUT" to indicate discovery or revelation? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Find out the truth',
        B: 'Figure out the solution',
        C: 'Point out an error',
        D: 'Put out of town',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Find out (tìm ra sự thật), Figure out (nghĩ ra cách giải quyết), Point out (chỉ ra sai sót).',
    },
    {
      id: 41,
      noiDung: 'Select all phrasal verbs with multiple distinct meanings: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Take off (cất cánh / cởi đồ / thành công nhanh chóng)',
        B: 'Make up (trang điểm / bịa chuyện / làm hòa)',
        C: 'Break down (hỏng hóc / suy sụp tinh thần / phân tích chi tiết)',
        D: 'Look through (chỉ có duy nhất 1 nghĩa toán học)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Take off, Make up, Break down là các cụm động từ đa nghĩa kinh điển trong tiếng Anh.',
    },
    {
      id: 42,
      noiDung: 'Which sentences correctly use "CATCH UP"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Go ahead, I will catch up with you in five minutes.',
        B: 'Let\'s grab a cup of coffee and catch up on each other\'s news.',
        C: 'He ran fast to catch up to the leading runner.',
        D: 'She caught up her umbrella because of the storm.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C sử dụng "catch up" với nghĩa đuổi kịp và trò chuyện cập nhật tin tức chuẩn. D dùng sai ngữ cảnh.',
    },
    {
      id: 43,
      noiDung: 'Which phrasal verbs describe an unexpected event or encounter? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Bump into an old classmate',
        B: 'Come across a rare coin',
        C: 'Turn up without an invitation',
        D: 'Book up a reserved seat',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Bump into (tình cờ gặp), Come across (tình cờ thấy), Turn up (bất ngờ xuất hiện).',
    },
    {
      id: 44,
      noiDung: 'Select all three-word phrasal verbs: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Look forward to',
        B: 'Get away with',
        C: 'Cut down on',
        D: 'Take over',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C đều có cấu trúc 3 từ (verb + particle + preposition). D chỉ có 2 từ.',
    },
    {
      id: 45,
      noiDung: 'Which phrasal verbs mean "to decline or reject"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Turn down',
        B: 'Pass up',
        C: 'Turn away',
        D: 'Take up',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Turn down (từ chối), Pass up (bỏ qua/từ chối cơ hội), Turn away (từ chối cho vào). Take up là nhận lấy hoặc bắt đầu.',
    },
  ],
};
