import { CurriculumTopicBank } from './types';

export const PREPOSITIONS_BANK: CurriculumTopicBank = {
  key: 'PREPOSITIONS',
  tenChuDe: 'Giới Từ Chỉ Thời Gian & Nơi Chốn (Prepositions)',
  aliases: [
    'giới từ',
    'gioi tu',
    'preposition',
    'prepositions',
    'in on at',
    'giới từ thời gian',
    'giới từ nơi chốn',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'The crucial management meeting is scheduled to commence __________ 9:30 AM tomorrow.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'at', B: 'on', C: 'in', D: 'by' },
      dapAnDung: 'A',
      giaiThich: '"At" đi với giờ giấc cụ thể trong ngày (at 9:30 AM).',
    },
    {
      id: 2,
      noiDung: 'Our annual international academic symposium will take place __________ Friday, October 15th.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'on', B: 'in', C: 'at', D: 'for' },
      dapAnDung: 'A',
      giaiThich: '"On" đi với các ngày trong tuần hoặc ngày tháng cụ thể (on Friday, on October 15th).',
    },
    {
      id: 3,
      noiDung: 'ETC English Center was established __________ the autumn of 2018.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'in', B: 'at', C: 'on', D: 'from' },
      dapAnDung: 'A',
      giaiThich: '"In" đi với các mùa trong năm (in the autumn, in summer) hoặc năm (in 2018).',
    },
    {
      id: 4,
      noiDung: 'The CEO will arrive __________ Hanoi at 6 PM to inspect our new branch.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'in', B: 'at', C: 'to', D: 'on' },
      dapAnDung: 'A',
      giaiThich: '"Arrive in" đi với thành phố, quốc gia lớn (arrive in Hanoi). "Arrive at" đi với địa điểm cụ thể (arrive at the airport).',
    },
    {
      id: 5,
      noiDung: 'She is currently relaxing __________ the balcony, reading her favorite novel.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'on', B: 'in', C: 'at', D: 'to' },
      dapAnDung: 'A',
      giaiThich: '"On the balcony" là cụm từ chỉ vị trí chuẩn trên ban công.',
    },
    {
      id: 6,
      noiDung: 'The children were playing happily __________ the garden when the rain began.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'in', B: 'at', C: 'on', D: 'for' },
      dapAnDung: 'A',
      giaiThich: '"In the garden" (trong một không gian kín, có ranh giới bao quanh).',
    },
    {
      id: 7,
      noiDung: 'I usually finish reading all my work emails __________ the end of the working day.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'at', B: 'in', C: 'on', D: 'with' },
      dapAnDung: 'A',
      giaiThich: '"At the end of something" (vào thời điểm cuối của cái gì).',
    },
    {
      id: 8,
      noiDung: 'The grand fireworks display will light up the city sky __________ midnight.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'at', B: 'in', C: 'on', D: 'during' },
      dapAnDung: 'A',
      giaiThich: '"At midnight", "at noon", "at night" luôn đi với giới từ "at".',
    },
    {
      id: 9,
      noiDung: 'The certificate of academic achievement hangs proudly __________ the wall in his home office.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'on', B: 'in', C: 'at', D: 'above' },
      dapAnDung: 'A',
      giaiThich: '"On the wall" (trên bề mặt tường).',
    },
    {
      id: 10,
      noiDung: 'He promised to complete the technical documentation __________ Monday morning at the latest.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'by', B: 'at', C: 'until', D: 'in' },
      dapAnDung: 'A',
      giaiThich: '"By" mang nghĩa "trước hoặc chậm nhất vào lúc nào đó" (hạn chót).',
    },
    {
      id: 11,
      noiDung: 'We stopped for a quick lunch __________ a charming restaurant near the seaside pier.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'at', B: 'on', C: 'into', D: 'between' },
      dapAnDung: 'A',
      giaiThich: '"At a restaurant" (coi nhà hàng như một điểm đến/địa điểm cụ thể trên bản đồ).',
    },
    {
      id: 12,
      noiDung: 'The historical artifact dates back to the early years __________ the seventeenth century.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'of', B: 'in', C: 'at', D: 'on' },
      dapAnDung: 'A',
      giaiThich: '"The early years of the seventeenth century" (những năm đầu của thế kỷ 17).',
    },
    {
      id: 13,
      noiDung: 'Are you planning to travel anywhere abroad __________ this coming weekend?',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'at / on', B: 'during / on', C: 'at / during', D: 'in / at' },
      dapAnDung: 'A',
      giaiThich: '"At the weekend" (tiếng Anh Anh) hoặc "on the weekend" (tiếng Anh Mỹ) đều đúng.',
    },
    {
      id: 14,
      noiDung: 'The cat jumped __________ the fence and vanished into the neighboring shrubs.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'over', B: 'through', C: 'under', D: 'into' },
      dapAnDung: 'A',
      giaiThich: '"Jump over" (nhảy qua một rào cản từ bên này sang bên kia).',
    },
    {
      id: 15,
      noiDung: 'The doctor advised him to stay __________ bed for at least three full days to recover.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'in', B: 'on', C: 'at', D: 'into' },
      dapAnDung: 'A',
      giaiThich: '"Stay in bed" (nằm nghỉ trên giường khi bị bệnh).',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'We say "in the morning", "in the afternoon", but "at night".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Quy tắc bất biến: in the morning/afternoon/evening nhưng bắt buộc là "at night".',
    },
    {
      id: 17,
      noiDung: 'The preposition "on" is used with specific days and dates (e.g., on Monday, on July 4th).',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "On" luôn đi với ngày trong tuần và ngày tháng cụ thể.',
    },
    {
      id: 18,
      noiDung: 'When talking about traveling by public transportation (bus, train, plane), we usually say "in the bus" and "in the train".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Phương tiện công cộng người đứng hoặc đi lại được (bus, train, plane, ship) ta dùng "ON" (on the bus, on the train). "In" chỉ dùng cho car, taxi.',
    },
    {
      id: 19,
      noiDung: '"At the end" refers to the point where something stops, whereas "in the end" means "finally" or "after all".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "At the end of something" (ở điểm kết thúc), "In the end" (cuối cùng/rốt cuộc).',
    },
    {
      id: 20,
      noiDung: 'We say "arrive to London" in standard English.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Không bao giờ dùng "arrive to". Phải dùng "arrive IN London" hoặc "arrive AT the station".',
    },
    {
      id: 21,
      noiDung: 'The preposition "by" followed by a point in time indicates a deadline meaning "not later than".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "By 5 PM" nghĩa là chậm nhất là 5 giờ chiều.',
    },
    {
      id: 22,
      noiDung: 'We use "in" with centuries, decades, years, seasons, and months.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "In" bao quát khoảng thời gian lớn: thế kỷ (in the 21st century), năm (in 2024), mùa (in winter), tháng (in May).',
    },
    {
      id: 23,
      noiDung: 'The expression "on time" means punctual at the scheduled time, whereas "in time" means early enough for something.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "On time" (đúng giờ theo lịch trình), "In time" (kịp giờ, vừa vặn thời gian trước khi quá muộn).',
    },
    {
      id: 24,
      noiDung: 'We use the preposition "on" for small private vehicles like "on a car" and "on a taxi".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Với xe ô tô riêng và taxi, bắt buộc dùng "in" (in a car, in a taxi).',
    },
    {
      id: 25,
      noiDung: '"Between" is traditionally used for two distinct entities, while "among" refers to three or more within a group.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Between" thường dùng cho 2 đối tượng tách biệt, "Among" dùng trong tập thể 3 đối tượng trở lên.',
    },
    {
      id: 26,
      noiDung: 'When talking about an address with a specific house number, we use the preposition "in" (e.g., in 123 Main Street).',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Có số nhà cụ thể phải dùng "AT" (at 123 Main Street). Nếu chỉ có tên đường thì dùng "ON" (on Main Street).',
    },
    {
      id: 27,
      noiDung: 'The phrase "at the corner of the street" refers to the precise intersection point.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "At the corner of" chỉ vị trí ngã tư góc đường.',
    },
    {
      id: 28,
      noiDung: 'Before time words like "next", "last", "this", and "every", we do not use prepositions in/on/at (e.g., "see you next week").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Không dùng in/on/at trước next, last, this, every (vd: nói "next Monday", không nói "on next Monday").',
    },
    {
      id: 29,
      noiDung: '"Across" implies moving from one side to the other side of a surface (like a road or river).',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Across the road / river" nghĩa là băng qua từ bên này sang bên kia.',
    },
    {
      id: 30,
      noiDung: 'The expression "at present" is synonymous with "currently" or "at the moment".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "At present" đồng nghĩa với "at the moment" (hiện tại).',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which time expressions correctly use the preposition "IN"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A1',
      luaChon: {
        A: 'In 2026',
        B: 'In the 21st century',
        C: 'In December',
        D: 'In Monday morning',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'In đi với năm, thế kỷ, tháng. D sai vì có ngày thứ ("Monday") nên phải dùng "On Monday morning".',
    },
    {
      id: 32,
      noiDung: 'Which time expressions correctly take the preposition "AT"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A1',
      luaChon: {
        A: 'At noon',
        B: 'At dawn',
        C: 'At 10:45 PM',
        D: 'At summer',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'At noon, At dawn, At 10:45 PM là các mốc thời điểm cụ thể. Mùa phải dùng "in summer".',
    },
    {
      id: 33,
      noiDung: 'Select all instances where the preposition "ON" is used correctly: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'On Sunday afternoon',
        B: 'On New Year\'s Day',
        C: 'On page 45',
        D: 'On 2025',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (ngày thứ), B (ngày lễ cụ thể), C (trên trang sách). D sai vì năm phải dùng "in 2025".',
    },
    {
      id: 34,
      noiDung: 'Which phrases indicate being physically aboard public passenger transit vehicles? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'On the commuter train',
        B: 'On the commercial flight',
        C: 'On a bicycle',
        D: 'On a compact taxi',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'On the train, on the flight, on a bicycle là chuẩn. Với taxi phải dùng "in a taxi".',
    },
    {
      id: 35,
      noiDung: 'Which pairs illustrate the difference between "in time" and "on time"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The 7:00 PM train departed on time (exactly at 7:00 PM).',
        B: 'We arrived in time to catch the train before the doors closed.',
        C: 'She was born on time in 1995.',
        D: 'He finished the exam just in time before the bell rang.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D dùng on time / in time chính xác ngữ cảnh. C dùng sai.',
    },
    {
      id: 36,
      noiDung: 'Select all correct prepositions indicating location: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'At the airport (điểm dừng cụ thể)',
        B: 'In the classroom (trong không gian phòng học)',
        C: 'On the ceiling (trên bề mặt trần nhà)',
        D: 'To the table (chỉ vị trí tĩnh trên bàn)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'At, In, On biểu thị vị trí tĩnh chính xác. "To" chỉ hướng chuyển động, không chỉ vị trí tĩnh.',
    },
    {
      id: 37,
      noiDung: 'Which of the following phrases DO NOT require a preposition before them? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'This morning',
        B: 'Next Sunday',
        C: 'Yesterday evening',
        D: 'The 10th of May',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'This morning, Next Sunday, Yesterday evening không đi với giới từ. D bắt buộc phải có "on the 10th of May".',
    },
    {
      id: 38,
      noiDung: 'Which prepositions express motion towards the interior of an object or enclosure? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Into',
        B: 'Onto',
        C: 'In through',
        D: 'Off',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: '"Into" và "In through" diễn tả chuyển động tiến vào bên trong. "Onto" là lên bề mặt, "Off" là rời khỏi.',
    },
    {
      id: 39,
      noiDung: 'Which sentences use "AT" correctly for events and social gatherings? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'I met Sarah at the wedding reception.',
        B: 'There were over ten thousand fans at the rock concert.',
        C: 'They were discussing strategy at the regional conference.',
        D: 'He lives at Vietnam.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'At a wedding, At a concert, At a conference chỉ sự kiện. D sai vì quốc gia phải dùng "in Vietnam".',
    },
    {
      id: 40,
      noiDung: 'Select all expressions of time using "DURING" correctly: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'During the summer holidays',
        B: 'During the keynote presentation',
        C: 'During three hours',
        D: 'During the Middle Ages',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: '"During" đi với danh từ chỉ khoảng thời gian/sự kiện. C sai vì với số giờ đo lường cụ thể phải dùng "for three hours".',
    },
    {
      id: 41,
      noiDung: 'Which sentences demonstrate the correct usage of "under" vs "below"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The dog is sleeping under the wooden dining table.',
        B: 'The temperature dropped below freezing last night.',
        C: 'The submarine was cruising 200 meters below sea level.',
        D: 'He hid below the blanket.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (dưới vật che chắn trực tiếp dùng under), B và C (dưới mức thang đo nhiệt độ, độ cao dùng below). D thường dùng "under the blanket".',
    },
    {
      id: 42,
      noiDung: 'Which prepositional phrases indicate being on the left or right side? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A1',
      luaChon: {
        A: 'On the left',
        B: 'On the right',
        C: 'In the left',
        D: 'At the left-hand side',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'On the left, On the right, At the left-hand side là các cách diễn đạt phương hướng chuẩn. Không dùng "in the left".',
    },
    {
      id: 43,
      noiDung: 'Select all sentences with correct dependent prepositions after adjectives: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'She is exceptionally good at English grammar.',
        B: 'He is interested in renewable energy technologies.',
        C: 'They are proud of their daughter\'s achievements.',
        D: 'She is afraid from spiders.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Good at, Interested in, Proud of là các tính từ đi với giới từ cố định. D sai vì phải là "afraid of spiders".',
    },
    {
      id: 44,
      noiDung: 'Which prepositions express contrast or concession? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Despite',
        B: 'In spite of',
        C: 'Due to',
        D: 'Notwithstanding',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Despite, In spite of, Notwithstanding đều là giới từ chỉ sự tương phản (mặc dù). Due to mang nghĩa "bởi vì".',
    },
    {
      id: 45,
      noiDung: 'Select all correct sentences using prepositions for addresses: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'He lives at 45 Oxford Street.',
        B: 'The bookshop is located on Oxford Street.',
        C: 'The store is in 45 Oxford Street.',
        D: 'Her apartment is on the second floor.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'At + số nhà (A), On + tên đường (B), On + tầng nhà (D) đều chuẩn. C sai vì có số nhà không dùng "in".',
    },
  ],
};
