import { CurriculumTopicBank } from './types';

export const PRESENT_PERFECT_BANK: CurriculumTopicBank = {
  key: 'PRESENT_PERFECT',
  tenChuDe: 'Thì Hiện Tại Hoàn Thành (Present Perfect Tense)',
  aliases: [
    'hiện tại hoàn thành',
    'hien tai hoan thanh',
    'present perfect',
    'thì ht hoàn thành',
    'ht ht',
    'since',
    'for',
    'already yet',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'She __________ in London for five years, but she plans to relocate to Manchester soon.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'lived', B: 'has lived', C: 'is living', D: 'lives' },
      dapAnDung: 'B',
      giaiThich: 'Diễn tả hành động bắt đầu trong quá khứ kéo dài đến hiện tại ("for five years"), dùng thì Hiện tại hoàn thành.',
    },
    {
      id: 2,
      noiDung: 'Have you ever __________ a live symphony orchestra perform Beethoven in Vienna?',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'hear', B: 'heard', C: 'hearing', D: 'hears' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc câu hỏi trải nghiệm: "Have + S + ever + V3/ed?". Quá khứ phân từ của "hear" là "heard".',
    },
    {
      id: 3,
      noiDung: 'I haven\'t received the official auditor feedback on our financial statements __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'already', B: 'just', C: 'yet', D: 'since' },
      dapAnDung: 'C',
      giaiThich: '"Yet" thường đứng ở cuối câu phủ định trong thì Hiện tại hoàn thành mang nghĩa "chưa".',
    },
    {
      id: 4,
      noiDung: 'Look! Someone __________ a cup of hot espresso all over the conference table.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'spilled', B: 'has spilled', C: 'spills', D: 'was spilling' },
      dapAnDung: 'B',
      giaiThich: 'Hành động vừa xảy ra để lại dấu vết/kết quả rõ ràng ở hiện tại ("Look!"), dùng Hiện tại hoàn thành.',
    },
    {
      id: 5,
      noiDung: 'Where is Dr. Martinez? — She __________ to the central hospital to examine an urgent patient.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'has gone', B: 'has been', C: 'went', D: 'was going' },
      dapAnDung: 'A',
      giaiThich: '"Has gone to" chỉ người đã đi đến đó và hiện chưa trở về (phân biệt với "has been to" - đã từng đến và đã về).',
    },
    {
      id: 6,
      noiDung: 'Professor Williams __________ at this international university since October 2015.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'taught', B: 'has taught', C: 'is teaching', D: 'teaches' },
      dapAnDung: 'B',
      giaiThich: 'Dấu hiệu nhận biết "since + mốc thời gian trong quá khứ" đòi hỏi dùng thì Hiện tại hoàn thành.',
    },
    {
      id: 7,
      noiDung: 'This is the first time I __________ such an authentic Japanese sushi banquet.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'ate', B: 'have eaten', C: 'eat', D: 'had eaten' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc "This is the first/second time + S + have/has + V3/ed".',
    },
    {
      id: 8,
      noiDung: 'The research team __________ three clinical trials so far this year.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'completed', B: 'has completed', C: 'was completing', D: 'completes' },
      dapAnDung: 'B',
      giaiThich: 'Cụm từ "so far this year" (cho đến nay trong năm nay) là dấu hiệu điển hình của thì Hiện tại hoàn thành.',
    },
    {
      id: 9,
      noiDung: 'We haven\'t seen each other __________ we graduated from high school together.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'for', B: 'since', C: 'when', D: 'during' },
      dapAnDung: 'B',
      giaiThich: '"Since" đi với một mệnh đề ở thì quá khứ đơn ("since we graduated") làm mốc thời gian bắt đầu.',
    },
    {
      id: 10,
      noiDung: 'How many foreign countries __________ you __________ to in your entire life?',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'did / travel', B: 'have / been', C: 'do / go', D: 'were / visited' },
      dapAnDung: 'B',
      giaiThich: 'Hỏi về trải nghiệm cuộc đời tính đến hiện tại dùng "have you been to...".',
    },
    {
      id: 11,
      noiDung: 'Be quiet! The board members __________ just __________ an important strategic agreement.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'have / reached', B: 'had / reached', C: 'did / reach', D: 'are / reaching' },
      dapAnDung: 'A',
      giaiThich: 'Trạng từ "just" đứng giữa trợ động từ "have" và phân từ hai "reached" để diễn tả hành động vừa mới xảy ra.',
    },
    {
      id: 12,
      noiDung: 'Up to the present moment, scientists __________ no conclusive evidence of alien life.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'found', B: 'have found', C: 'find', D: 'are finding' },
      dapAnDung: 'B',
      giaiThich: '"Up to the present" (cho tới thời điểm hiện tại) đi với thì Hiện tại hoàn thành.',
    },
    {
      id: 13,
      noiDung: 'He __________ his smartphone screen twice this week alone.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'cracked', B: 'has cracked', C: 'cracks', D: 'is cracking' },
      dapAnDung: 'B',
      giaiThich: 'Khoảng thời gian chưa kết thúc ("this week") và số lần lặp lại ("twice") dùng thì Hiện tại hoàn thành.',
    },
    {
      id: 14,
      noiDung: 'The CEO __________ the press regarding the recent corporate merger yet.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'didn\'t address', B: 'hasn\'t addressed', C: 'wasn\'t addressing', D: 'doesn\'t address' },
      dapAnDung: 'B',
      giaiThich: 'Chủ ngữ "The CEO" số ít, kết hợp với "yet" ở cuối câu phủ định nên dùng "hasn\'t addressed".',
    },
    {
      id: 15,
      noiDung: 'I have known Clara __________ nearly twenty years; we are lifelong best friends.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'since', B: 'for', C: 'in', D: 'at' },
      dapAnDung: 'B',
      giaiThich: '"For" đi kèm khoảng thời gian ("for nearly twenty years"), trong khi "since" đi với mốc thời gian.',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'The preposition "since" is followed by a specific starting point in time, while "for" is followed by a duration of time.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Since" đi với mốc thời gian (vd: 2010, Monday), "for" đi với khoảng thời gian (vd: 3 hours, 5 years).',
    },
    {
      id: 17,
      noiDung: 'The sentence "I have visited Tokyo last year" is grammatically correct in standard English.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Có mốc thời gian xác định trong quá khứ ("last year"), bắt buộc phải dùng thì Quá khứ đơn ("I visited Tokyo last year").',
    },
    {
      id: 18,
      noiDung: '"Has gone to Paris" implies that the subject is currently in Paris or on the way there and has not yet returned.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Has gone to" chỉ người đi và chưa về, còn "has been to" chỉ người đã đi và đã trở về.',
    },
    {
      id: 19,
      noiDung: 'The adverb "already" usually emphasizes that an action has been completed earlier than expected.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Already" nhấn mạnh hành động đã hoàn tất sớm hơn dự kiến.',
    },
    {
      id: 20,
      noiDung: 'Present Perfect tense can never be used to describe an unfinished time period like "this morning" or "this week".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Hiện tại hoàn thành rất phổ biến khi diễn tả hành động trong khoảng thời gian chưa kết thúc ("this morning", "this month").',
    },
    {
      id: 21,
      noiDung: 'The past participle form of the irregular verb "choose" is "chosen".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Bảng động từ bất quy tắc: choose - chose - chosen.',
    },
    {
      id: 22,
      noiDung: 'In the sentence "We have lived here since three months", the preposition "since" is used correctly.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Three months" là khoảng thời gian nên phải dùng "for three months", không dùng "since".',
    },
    {
      id: 23,
      noiDung: 'The adverb "yet" is typically placed at the end of negative sentences and questions in the Present Perfect.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Yet" thường đứng cuối câu phủ định hoặc nghi vấn trong thì Hiện tại hoàn thành.',
    },
    {
      id: 24,
      noiDung: 'Stative verbs like "know", "believe", and "own" cannot be used in the Present Perfect Simple tense.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Động từ chỉ trạng thái (stative verbs) hoàn toàn được dùng ở Hiện tại hoàn thành đơn (ví dụ: "I have known him for years").',
    },
    {
      id: 25,
      noiDung: 'The question "Have you ever been to Canada?" is asking about life experience up to the present moment.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Have you ever been to...?" dùng để hỏi về trải nghiệm tính đến hiện tại.',
    },
    {
      id: 26,
      noiDung: 'The past participle of "write" is "written".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Động từ bất quy tắc: write - wrote - written.',
    },
    {
      id: 27,
      noiDung: 'We can use the Present Perfect tense with specific past time markers like "yesterday at 3 PM".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Khi có mốc thời gian quá khứ cụ thể như "yesterday at 3 PM", ta phải dùng Quá khứ đơn hoặc Quá khứ tiếp diễn.',
    },
    {
      id: 28,
      noiDung: '"Ever" is commonly used in affirmative statements rather than questions or negative sentences.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Ever" chủ yếu dùng trong câu hỏi (Have you ever...?) hoặc sau so sánh nhất, hiếm khi dùng trong câu khẳng định thông thường.',
    },
    {
      id: 29,
      noiDung: 'Present Perfect tense can connect a past event with a direct present consequence.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Bản chất của thì Hiện tại hoàn thành là cầu nối giữa sự việc trong quá khứ và kết quả ở hiện tại.',
    },
    {
      id: 30,
      noiDung: 'The contraction "She\'s finished her degree" stands for "She is finished her degree".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Trong câu này, "She\'s" là viết tắt của "She has" ("She has finished").',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which of the following time markers are typically used with the Present Perfect tense? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Since last Monday',
        B: 'Already',
        C: 'Two days ago',
        D: 'So far',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Since last Monday, Already, So far là dấu hiệu của Hiện tại hoàn thành. "Two days ago" là dấu hiệu của Quá khứ đơn.',
    },
    {
      id: 32,
      noiDung: 'Which sentences use the Present Perfect tense correctly to talk about life experiences? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'I have never flown in a hot air balloon.',
        B: 'She has visited over thirty countries so far.',
        C: 'He has broken his leg when he was seven years old.',
        D: 'Have you ever seen the Northern Lights?',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D diễn tả trải nghiệm không mốc thời gian cụ thể. C sai vì có mệnh đề chỉ thời gian quá khứ rõ ràng ("when he was seven"), phải dùng Quá khứ đơn.',
    },
    {
      id: 33,
      noiDung: 'Select all correct sentences containing "since" or "for": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'They have collaborated on this project for six months.',
        B: 'We have been friends since our freshman year.',
        C: 'She has worked here since four years.',
        D: 'I haven\'t heard from him for a very long time.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D dùng since/for chính xác. C sai vì "four years" phải dùng "for four years".',
    },
    {
      id: 34,
      noiDung: 'Which of the following verbs have the SAME past simple and past participle forms? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Buy (bought / bought)',
        B: 'Teach (taught / taught)',
        C: 'Write (wrote / written)',
        D: 'Keep (kept / kept)',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Buy, Teach, Keep có V2 và V3 giống nhau. Write có V2 là wrote và V3 là written.',
    },
    {
      id: 35,
      noiDung: 'Identify all sentences where the Present Perfect indicates a present result: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'I have lost my apartment keys, so I cannot enter right now.',
        B: 'The company has announced bankruptcy, causing its stock to plummet.',
        C: 'Shakespeare has written Hamlet in the seventeenth century.',
        D: 'He has painted the fence; the paint is still completely wet.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D diễn tả hành động quá khứ để lại kết quả trực tiếp ở hiện tại. C sai ngữ pháp vì Shakespeare đã qua đời và có mốc thời gian quá khứ, phải dùng Quá khứ đơn.',
    },
    {
      id: 36,
      noiDung: 'Which of the following adverbs typically appear between "have/has" and the past participle? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Just',
        B: 'Already',
        C: 'Never',
        D: 'Yesterday',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Just, Already, Never đứng giữa trợ động từ và V3/ed. Yesterday không dùng cho Hiện tại hoàn thành.',
    },
    {
      id: 37,
      noiDung: 'Select all grammatically correct questions in the Present Perfect: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Has your sister arrived at the airport yet?',
        B: 'How long have you owned this vehicle?',
        C: 'When have you graduated from university?',
        D: 'What have you learned from this training course?',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D đặt câu hỏi hoàn toàn đúng. C sai vì câu hỏi với "When" đòi hỏi thời điểm cụ thể nên phải dùng Quá khứ đơn ("When did you graduate...?").',
    },
    {
      id: 38,
      noiDung: 'Which sentences correctly use "just", "already", or "yet"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'We haven\'t received the shipment yet.',
        B: 'She has already finished her master\'s thesis.',
        C: 'He has just stepped out of the office.',
        D: 'They have yet finished their homework.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C sử dụng đúng vị trí trạng từ. D sai vì "yet" không đứng giữa trợ động từ và V3 như vậy (phải là "have not finished... yet").',
    },
    {
      id: 39,
      noiDung: 'Which irregular verbs have three distinct forms for base, past simple, and past participle? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Do - Did - Done',
        B: 'Go - Went - Gone',
        C: 'Cut - Cut - Cut',
        D: 'Sing - Sang - Sung',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Do, Go, Sing có 3 dạng khác nhau hoàn toàn. Cut có cả 3 dạng giống nhau.',
    },
    {
      id: 40,
      noiDung: 'Select all contexts where Present Perfect is preferred over Past Simple: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Announcing recent news without mentioning the exact time',
        B: 'Describing an action that started in the past and continues into the present',
        C: 'Narrating a sequence of completed historical events in 1945',
        D: 'Describing how many times someone has done something in their life up to now',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là các chức năng cốt lõi của Hiện tại hoàn thành. C kể chuỗi sự kiện lịch sử trong quá khứ đã kết thúc thì dùng Quá khứ đơn.',
    },
    {
      id: 41,
      noiDung: 'Which sentences illustrate the correct usage of "have been to" vs "have gone to"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: '"I have been to Italy twice" (I am now back home speaking to you).',
        B: '"Mark is not at his desk; he has gone to the post office."',
        C: '"Where have you been? I was searching for you everywhere!"',
        D: '"Look! I have gone to Paris and bought this souvenir there."',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C sử dụng đúng nghĩa. D sai vì nếu đã về và đang khoe món quà thì phải dùng "have been to Paris".',
    },
    {
      id: 42,
      noiDung: 'Which of the following phrases require the Present Perfect tense? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'It is the first time that S + have/has + V3',
        B: 'This is the most remarkable painting I have ever seen',
        C: 'Last night at midnight',
        D: 'Over the last few decades',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D đi với Hiện tại hoàn thành. C đi với Quá khứ tiếp diễn/Quá khứ đơn.',
    },
    {
      id: 43,
      noiDung: 'Which sentences correctly combine "never" with the Present Perfect? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'I have never witnessed such breathtaking natural beauty before.',
        B: 'She hasn\'t never visited a wildlife sanctuary.',
        C: 'They have never eaten spicy Mexican tacos.',
        D: 'He has never missed a single class this semester.',
      },
      dapAnDung: ['A', 'C', 'D'],
      giaiThich: 'A, C, D đúng cấu trúc "have/has + never + V3". B sai lỗi phủ định kép ("hasn\'t never").',
    },
    {
      id: 44,
      noiDung: 'Select all sentences with grammatical errors regarding the Present Perfect: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'She has went to the department store yesterday.',
        B: 'Have you drank enough water today?',
        C: 'We have known each other since kindergarten.',
        D: 'They have already finished their evaluation report.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A sai 2 lỗi: "went" (phải là gone) và "yesterday" (không dùng với HTHT). B sai vì phân từ hai của drink là "drunk", không phải "drank". C và D đúng.',
    },
    {
      id: 45,
      noiDung: 'Which of the following are valid uses of the Present Perfect Continuous compared to Present Perfect Simple? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Emphasizing the duration or ongoing process of an activity (have been waiting for 2 hours)',
        B: 'Emphasizing the completed result or quantity produced (have written 3 chapters)',
        C: 'Focusing on the temporary nature of an ongoing action',
        D: 'Describing an action that permanently finished 100 years ago',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: 'A và C là đặc trưng của HTHT Tiếp diễn (nhấn mạnh tính liên tục, quá trình). B là của HTHT Đơn (nhấn mạnh kết quả, số lượng). D là của Quá khứ đơn.',
    },
  ],
};
