import { CurriculumTopicBank } from './types';

export const RELATIVE_CLAUSES_BANK: CurriculumTopicBank = {
  key: 'RELATIVE_CLAUSES',
  tenChuDe: 'Mệnh Đề Quan Hệ (Relative Clauses)',
  aliases: [
    'mệnh đề quan hệ',
    'menh de quan he',
    'relative clause',
    'relative clauses',
    'who',
    'whom',
    'which',
    'that',
    'whose',
    'mđqh',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'The teacher __________ conducts the IELTS Masterclass at ETC Center has over ten years of expertise.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'who', B: 'which', C: 'whom', D: 'whose' },
      dapAnDung: 'A',
      giaiThich: '"Who" làm chủ ngữ thay thế cho danh từ chỉ người ("The teacher").',
    },
    {
      id: 2,
      noiDung: 'The academic textbook __________ I borrowed from the central library contains comprehensive grammar exercises.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'who', B: 'which', C: 'whom', D: 'whose' },
      dapAnDung: 'B',
      giaiThich: '"Which" thay thế cho danh từ chỉ vật ("The academic textbook").',
    },
    {
      id: 3,
      noiDung: 'That is the diligent student __________ research paper was published in an international journal.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'who', B: 'whom', C: 'whose', D: 'that' },
      dapAnDung: 'C',
      giaiThich: '"Whose" chỉ quan hệ sở hữu đối với danh từ đứng sau ("whose research paper" = the student\'s research paper).',
    },
    {
      id: 4,
      noiDung: 'The technology company __________ my brother works as a senior architect provides excellent perks.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'where', B: 'which', C: 'that', D: 'when' },
      dapAnDung: 'A',
      giaiThich: '"Where" là trạng từ quan hệ thay thế cho nơi chốn (= at which / in which).',
    },
    {
      id: 5,
      noiDung: 'Mr. David, __________ you met at the educational exhibition yesterday, is our academic director.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'whom', B: 'which', C: 'whose', D: 'that' },
      dapAnDung: 'A',
      giaiThich: '"Whom" làm tân ngữ chỉ người trong mệnh đề quan hệ không xác định (sau dấu phẩy không dùng "that").',
    },
    {
      id: 6,
      noiDung: '2020 was the unforgettable year __________ the global pandemic disrupted educational institutions worldwide.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'when', B: 'where', C: 'which', D: 'why' },
      dapAnDung: 'A',
      giaiThich: '"When" là trạng từ quan hệ thay thế cho từ chỉ thời gian ("the unforgettable year").',
    },
    {
      id: 7,
      noiDung: 'The reason __________ he decided to withdraw from the competition remains confidential.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'why', B: 'where', C: 'when', D: 'which' },
      dapAnDung: 'A',
      giaiThich: '"Why" là trạng từ quan hệ chỉ lý do, thường đi liền sau "the reason".',
    },
    {
      id: 8,
      noiDung: 'All students __________ have registered for the mock test must arrive 15 minutes before start time.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'who', B: 'which', C: 'whose', D: 'whom' },
      dapAnDung: 'A',
      giaiThich: '"Who" làm chủ ngữ chỉ người cho "All students".',
    },
    {
      id: 9,
      noiDung: 'The presentation, __________ lasted nearly two hours, was extremely informative.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'which', B: 'that', C: 'what', D: 'who' },
      dapAnDung: 'A',
      giaiThich: 'Trong mệnh đề quan hệ không xác định (có dấu phẩy), chỉ dùng "which", tuyệt đối không dùng "that".',
    },
    {
      id: 10,
      noiDung: 'The candidate with __________ I had an interview this morning demonstrated remarkable analytical skills.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'whom', B: 'who', C: 'that', D: 'which' },
      dapAnDung: 'A',
      giaiThich: 'Sau giới từ ("with"), đại từ quan hệ chỉ người bắt buộc phải là "whom", không được dùng "who" hay "that".',
    },
    {
      id: 11,
      noiDung: 'The building in __________ our language department is situated was erected in 1985.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'which', B: 'where', C: 'that', D: 'whose' },
      dapAnDung: 'A',
      giaiThich: 'Sau giới từ ("in"), đại từ quan hệ chỉ vật bắt buộc là "which" ("in which" = where).',
    },
    {
      id: 12,
      noiDung: 'She has two daughters, both of __________ have achieved master degrees in applied linguistics.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'whom', B: 'who', C: 'them', D: 'which' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc lượng từ đi với mệnh đề quan hệ: "both of whom", "all of whom", "neither of whom".',
    },
    {
      id: 13,
      noiDung: 'The boy __________ injured in the bicycle accident was promptly rushed to the emergency room.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'who was', B: 'whom was', C: 'which was', D: 'whose was' },
      dapAnDung: 'A',
      giaiThich: '"who was injured" là mệnh đề quan hệ đầy đủ ở dạng bị động chỉ người.',
    },
    {
      id: 14,
      noiDung: 'He failed his driving test three consecutive times, __________ surprised none of his close friends.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'which', B: 'that', C: 'what', D: 'who' },
      dapAnDung: 'A',
      giaiThich: '"Which" đứng sau dấu phẩy có thể thay thế cho toàn bộ nội dung của mệnh đề đứng trước nó.',
    },
    {
      id: 15,
      noiDung: 'Is that the best documentary __________ you have ever watched about ocean ecosystems?',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'that', B: 'which', C: 'what', D: 'who' },
      dapAnDung: 'A',
      giaiThich: 'Sau dạng so sánh nhất ("the best documentary"), ta ưu tiên dùng "that" làm đại từ quan hệ.',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'In non-defining relative clauses (separated by commas), the relative pronoun "that" cannot be used.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "That" không bao giờ được đứng sau dấu phẩy trong mệnh đề quan hệ không xác định.',
    },
    {
      id: 17,
      noiDung: 'When a relative pronoun functions as the object of a defining relative clause, it can be safely omitted.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Đại từ quan hệ làm tân ngữ trong mệnh đề xác định có thể lược bỏ (vd: The book [which] I bought).',
    },
    {
      id: 18,
      noiDung: 'A preposition can be placed directly before the relative pronoun "that" (e.g., "the house in that I live").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Tuyệt đối không đặt giới từ trước "that" (phải dùng "in which", hoặc để giới từ ở cuối: "that I live in").',
    },
    {
      id: 19,
      noiDung: '"Whose" can be used to indicate possession for both people and inanimate objects/organizations.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Whose" có thể chỉ sở hữu cho người (whose son) lẫn vật/tổ chức (a company whose products...).',
    },
    {
      id: 20,
      noiDung: 'Non-defining relative clauses provide essential information needed to identify the noun being referred to.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Mệnh đề KHÔNG xác định (non-defining) chỉ cung cấp thông tin phụ bổ sung, lược bỏ đi câu vẫn đủ nghĩa.',
    },
    {
      id: 21,
      noiDung: 'The relative pronoun "which" can refer back to an entire preceding clause or sentence.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Sau dấu phẩy, "which" có thể thay thế cho toàn bộ sự việc nêu ở mệnh đề trước đó.',
    },
    {
      id: 22,
      noiDung: 'Reduced relative clauses using present participles (-ing) can only replace passive verb forms.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. V-ing dùng rút gọn mệnh đề mang nghĩa CHỦ ĐỘNG (vd: the man sitting there = who is sitting there). Bị động dùng V3/ed.',
    },
    {
      id: 23,
      noiDung: 'The adverb "where" is equivalent to preposition + "which" (e.g., "the city where I was born" = "the city in which I was born").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Where" tương đương với "in/at/on which" chỉ nơi chốn.',
    },
    {
      id: 24,
      noiDung: 'The sentence "He is the man who I talked to him yesterday" is grammatically redundant and incorrect.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Lỗi thừa tân ngữ "him" (vì "who" đã thay thế cho "the man"). Câu đúng: "He is the man who I talked to yesterday".',
    },
    {
      id: 25,
      noiDung: '"What" can be used as a standard relative pronoun with an explicit antecedent noun (e.g., "The movie what I saw").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "What" mang nghĩa "the thing that", không đi sau danh từ tiền ngữ xác định (không nói "The movie what I saw").',
    },
    {
      id: 26,
      noiDung: 'After superlative adjectives (the most, the best), "that" is preferred over "which".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Sau cấu trúc so sánh nhất hoặc các từ all, everything, nothing..., người ta ưu tiên dùng "that".',
    },
    {
      id: 27,
      noiDung: 'In "The student who won first prize received a trophy", "who won first prize" is a defining relative clause.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Mệnh đề này không có dấu phẩy và làm rõ đối tượng học sinh nào nên là mệnh đề quan hệ xác định.',
    },
    {
      id: 28,
      noiDung: 'Relative pronouns when acting as subject can be omitted freely in standard English.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Đại từ quan hệ làm CHỦ NGỮ không được lược bỏ (chỉ được rút gọn thành cụm V-ing hoặc V3/ed).',
    },
    {
      id: 29,
      noiDung: 'Expressions of quantity such as "many of which", "none of whom" are frequently used in non-defining clauses.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Các cụm lượng từ kết hợp đại từ quan hệ (some of which, all of whom) rất phổ biến trong văn phong học thuật.',
    },
    {
      id: 30,
      noiDung: 'The word "whose" must be immediately followed by a noun without an article (e.g., "whose book", not "whose a book").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Sau "whose" là danh từ không kèm mạo từ a/an/the.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'In which of the following sentences can the relative pronoun be safely omitted? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The smartphone which I purchased last week is defective.',
        B: 'The professor who delivered the keynote speech is famous.',
        C: 'The documentary that we watched last night won an award.',
        D: 'The girl who lives next door plays the piano.',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: 'Ở câu A và C, đại từ quan hệ đóng vai trò tân ngữ (I purchased, we watched) nên có thể lược bỏ. Ở B và D làm chủ ngữ nên không được bỏ.',
    },
    {
      id: 32,
      noiDung: 'Which of the following sentences use non-defining relative clauses correctly with punctuation? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'My father, who is a retired civil engineer, loves gardening.',
        B: 'Paris, which is the capital of France, attracts millions of tourists.',
        C: 'My father that is a retired engineer loves gardening.',
        D: 'London which is situated on the River Thames is very old.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A và B dùng dấu phẩy và đại từ (who, which) chuẩn. C sai vì dùng "that" cho tên riêng/danh từ xác định. D sai vì thiếu dấu phẩy quanh "London".',
    },
    {
      id: 33,
      noiDung: 'Select all grammatically correct sentences that use prepositions with relative pronouns: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The topic about which they argued was rather trivial.',
        B: 'The client to whom she sent the proposal responded promptly.',
        C: 'The topic about that they argued was rather trivial.',
        D: 'The girl who I was speaking to is my cousin.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A (about which), B (to whom), D (who... to) đều chuẩn. C sai vì không bao giờ đặt giới từ trước "that".',
    },
    {
      id: 34,
      noiDung: 'Which relative pronouns can refer exclusively to persons? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Who',
        B: 'Whom',
        C: 'Which',
        D: 'Where',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: '"Who" và "Whom" chỉ dùng cho người. "Which" dùng cho vật, "Where" dùng cho nơi chốn.',
    },
    {
      id: 35,
      noiDung: 'Which of the following sentences demonstrate correct participle reduction of relative clauses? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The boy sitting in the front row is very attentive. (= who is sitting)',
        B: 'The scientific article published yesterday created a buzz. (= which was published)',
        C: 'The car stolen last night was found abandoned.',
        D: 'The girl worn a red dress sang beautifully.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (chủ động -> V-ing), B và C (bị động -> V3/ed) đều rút gọn chính xác. D sai vì chủ động phải dùng "wearing", không dùng "worn".',
    },
    {
      id: 36,
      noiDung: 'Identify all sentences containing a grammatical mistake: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The woman whom dog barked all night apologized to us.',
        B: 'The company whose headquarters is in Tokyo is expanding.',
        C: 'The house where I lived in was demolished.',
        D: 'He is the author whose novel became a global bestseller.',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: 'A sai vì phải dùng từ chỉ sở hữu "whose dog", không dùng "whom". C sai lỗi thừa giới từ "in" khi đã có "where" (phải là "where I lived" hoặc "which I lived in").',
    },
    {
      id: 37,
      noiDung: 'Which of the following phrases typically prompt the use of "that" rather than "which"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'All that glitters is not gold.',
        B: 'Everything that he stated was true.',
        C: 'The first person that arrived got a reward.',
        D: 'My sister, that lives in Sydney, is a nurse.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Sau All, Everything, The first... ưu tiên dùng "that". D sai vì sau dấu phẩy không dùng "that".',
    },
    {
      id: 38,
      noiDung: 'Which relative adverbs replace prepositional phrases? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Where (= in/at which)',
        B: 'When (= on/in which)',
        C: 'Why (= for which)',
        D: 'Who (= of which)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Where, When, Why là 3 trạng từ quan hệ tương đương với các cụm giới từ chỉ nơi chốn, thời gian, lý do.',
    },
    {
      id: 39,
      noiDung: 'Select all sentences where "which" correctly refers to the entire main clause: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'He always arrives twenty minutes late, which irritates his colleagues.',
        B: 'She passed the difficult medical exam on her first attempt, which made her parents proud.',
        C: 'The laptop which is black belongs to Peter.',
        D: 'The flights were all cancelled due to snow, which created complete airport chaos.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D dùng "which" sau dấu phẩy để bổ nghĩa cho toàn bộ sự việc ở vế trước. C là mệnh đề hạn định bổ nghĩa cho danh từ "laptop".',
    },
    {
      id: 40,
      noiDung: 'Which sentences show correct usage of quantity expressions in relative clauses? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'We interviewed twenty candidates, none of whom had relevant experience.',
        B: 'She bought five vintage dresses, all of which were made of silk.',
        C: 'They tested two prototypes, both of them failed the stress test.',
        D: 'He presented three proposals, neither of which was accepted.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A (none of whom) và B (all of which) nối 2 mệnh đề chuẩn. C sai lỗi run-on sentence (phải dùng "both of which", không dùng "both of them" nối bằng dấu phẩy). D sai vì "neither" chỉ dùng cho 2 đối tượng, không dùng cho 3 (phải là "none of which").',
    },
    {
      id: 41,
      noiDung: 'Which sentences correctly reduce a relative clause with to-infinitive? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Neil Armstrong was the first man to walk on the moon. (= who walked)',
        B: 'She is the youngest athlete to win an Olympic medal.',
        C: 'Here is an application form for you to fill in.',
        D: 'The man to drive that sports car is my uncle.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Sau "the first", "the youngest" hoặc để chỉ mục đích, mệnh đề quan hệ rút gọn bằng to-V (A, B, C). D diễn đạt không tự nhiên.',
    },
    {
      id: 42,
      noiDung: 'Select all defining relative clauses where "that" can replace "who" or "which": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'The technician who repaired my computer is very skilled. -> ...technician that repaired...',
        B: 'The book which is lying on the shelf belongs to Anna. -> ...book that is lying...',
        C: 'Dr. John, who is a surgeon, works at City Hospital. -> Dr. John, that is a surgeon...',
        D: 'The company which produces solar panels won an eco award. -> ...company that produces...',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Trong mệnh đề quan hệ xác định, "that" có thể thay thế cho cả "who" và "which" (A, B, D). C là mệnh đề không xác định có dấu phẩy nên không được thay bằng "that".',
    },
    {
      id: 43,
      noiDung: 'Which sentences contain a contact clause (relative clause with the pronoun omitted)? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The delicious meal we prepared yesterday received great compliments.',
        B: 'The girl sitting over there looks very familiar.',
        C: 'This is the exact hotel they recommended to us.',
        D: 'The song that she sang went viral on social media.',
      },
      dapAnDung: ['A', 'C'],
      giaiThich: 'A (meal [which] we prepared) và C (hotel [that] they recommended) là các contact clause có đại từ quan hệ được lược bỏ.',
    },
    {
      id: 44,
      noiDung: 'Select all sentences correctly demonstrating "whose" indicating possession: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'I spoke with a woman whose luggage had been misplaced at the terminal.',
        B: 'We visited an ancient castle whose walls were built in the 12th century.',
        C: 'Who\'s laptop is left in the conference room?',
        D: 'The author whose biography was published last month is visiting our town.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D dùng "whose" chỉ sở hữu chuẩn. C sai vì "Who\'s" là viết tắt của "Who is" hoặc "Who has", không phải tính từ sở hữu.',
    },
    {
      id: 45,
      noiDung: 'Which of the following demonstrate correct subject-verb agreement inside a relative clause? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'She is one of those talented writers who create unforgettable stories.',
        B: 'He is the only one of the applicants who has passed the technical test.',
        C: 'The students who was absent yesterday must submit their doctor notes.',
        D: 'The equipment that were imported from Germany functions reliably.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A đúng ("those writers who create"). B đúng ("the only one... who has passed"). C sai ("students who was" -> were). D sai ("equipment" không đếm được -> was imported).',
    },
  ],
};
