import { CurriculumTopicBank } from './types';

export const REPORTED_SPEECH_BANK: CurriculumTopicBank = {
  key: 'REPORTED_SPEECH',
  tenChuDe: 'Câu Tường Thuật Gián Tiếp (Reported Speech)',
  aliases: [
    'tường thuật',
    'tuong thuat',
    'gián tiếp',
    'gian tiep',
    'reported speech',
    'indirect speech',
    'câu gián tiếp',
    'cau gian tiep',
    'lùi thì',
    'lui thi',
    'reported questions',
  ],
  questions: [
    // === 15 CÂU SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'Sarah said, "I am studying for my IELTS test right now." -> Sarah said that she __________ for her IELTS test then.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'is studying', B: 'was studying', C: 'studied', D: 'had studied' },
      dapAnDung: 'B',
      giaiThich: 'Khi động từ tường thuật ở quá khứ ("said"), thì hiện tại tiếp diễn ("am studying") lùi về quá khứ tiếp diễn ("was studying"), "now" đổi thành "then".',
    },
    {
      id: 2,
      noiDung: '"I have lost my passport," John told the police officer. -> John told the officer that he __________ his passport.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'has lost', B: 'had lost', C: 'loses', D: 'was losing' },
      dapAnDung: 'B',
      giaiThich: 'Thì hiện tại hoàn thành ("have lost") lùi về thì quá khứ hoàn thành ("had lost") trong câu tường thuật.',
    },
    {
      id: 3,
      noiDung: '"Where do you live?" the interviewer asked Mark. -> The interviewer asked Mark where __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'did he live', B: 'he lived', C: 'does he live', D: 'he lives' },
      dapAnDung: 'B',
      giaiThich: 'Trong câu hỏi gián tiếp có từ để hỏi (Wh-question), trật tự từ trở về dạng khẳng định (S + V): "where he lived", không đảo trợ động từ.',
    },
    {
      id: 4,
      noiDung: '"Do you speak Spanish?" she asked me. -> She asked me __________ I spoke Spanish.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'that', B: 'if', C: 'what', D: 'weather' },
      dapAnDung: 'B',
      giaiThich: 'Câu hỏi Yes/No chuyển sang gián tiếp sử dụng liên từ "if" hoặc "whether".',
    },
    {
      id: 5,
      noiDung: '"Please don\'t make noise in the study hall," the librarian said. -> The librarian told us __________ noise in the study hall.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'not make', B: 'not to make', C: 'don\'t make', D: 'to not make' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc tường thuật câu mệnh lệnh phủ định: "tell someone not to + V-inf".',
    },
    {
      id: 6,
      noiDung: '"I will send you the project quotation tomorrow," David said. -> David said that he __________ me the quotation the following day.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'will send', B: 'would send', C: 'sent', D: 'is sending' },
      dapAnDung: 'B',
      giaiThich: '"Will" lùi thì thành "would" trong câu tường thuật gián tiếp.',
    },
    {
      id: 7,
      noiDung: '"Why didn\'t you attend the meeting yesterday?" the manager asked. -> The manager asked why __________ the meeting the day before.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'hadn\'t I attended', B: 'I hadn\'t attended', C: 'I didn\'t attend', D: 'didn\'t I attend' },
      dapAnDung: 'B',
      giaiThich: 'Quá khứ đơn lùi về quá khứ hoàn thành ("hadn\'t attended"), và trật tự câu hỏi gián tiếp là S + had + V3.',
    },
    {
      id: 8,
      noiDung: '"Can you help me carry these heavy parcels?" she asked. -> She asked me if I __________ her carry those parcels.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'can help', B: 'could help', C: 'helped', D: 'would help' },
      dapAnDung: 'B',
      giaiThich: 'Động từ khiếm khuyết "can" lùi thì thành "could" trong câu gián tiếp.',
    },
    {
      id: 9,
      noiDung: '"You should consult a doctor immediately," Susan told Peter. -> Susan advised Peter __________ a doctor immediately.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'consulting', B: 'to consult', C: 'consult', D: 'that consult' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc tường thuật lời khuyên với "advise": "advise someone to + V-inf".',
    },
    {
      id: 10,
      noiDung: '"Let\'s organize a charity book fair this weekend," Alex suggested. -> Alex suggested __________ a charity book fair that weekend.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'to organize', B: 'organizing', C: 'organized', D: 'organize' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc tường thuật lời gợi ý: "suggest + V-ing" hoặc "suggest that S + (should) + V-inf".',
    },
    {
      id: 11,
      noiDung: '"I must finish this assignment before 5 PM," he said. -> He said that he __________ finish that assignment before 5 PM.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'must', B: 'had to', C: 'has to', D: 'would have' },
      dapAnDung: 'B',
      giaiThich: '"Must" chỉ nghĩa vụ thực tế trong quá khứ chuyển thành "had to" trong câu gián tiếp.',
    },
    {
      id: 12,
      noiDung: '"I bought this second-hand laptop two weeks ago," Michael said. -> Michael said he had bought that laptop two weeks __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'before', B: 'ago', C: 'earlier then', D: 'prior to' },
      dapAnDung: 'A',
      giaiThich: 'Trong câu gián tiếp, trạng từ chỉ thời gian "ago" đổi thành "before" (hoặc "previously").',
    },
    {
      id: 13,
      noiDung: '"I am sorry I arrived late for the presentation," Tom said. -> Tom apologized __________ late for the presentation.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'for arriving', B: 'to arrive', C: 'that he arrived', D: 'about arriving' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc tường thuật lời xin lỗi: "apologize (to someone) for + V-ing".',
    },
    {
      id: 14,
      noiDung: '"The water boils at 100 degrees Celsius," the physics teacher explained. -> The teacher explained that water __________ at 100 degrees Celsius.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'boiled', B: 'boils', C: 'had boiled', D: 'is boiling' },
      dapAnDung: 'B',
      giaiThich: 'Quy tắc ngoại lệ lùi thì: khi nội dung tường thuật là một chân lý, sự thật khoa học hiển nhiên, thì giữ nguyên Hiện tại đơn ("boils").',
    },
    {
      id: 15,
      noiDung: '"Don\'t touch the wet paint," the decorator warned us. -> The decorator warned us __________ the wet paint.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'against touching', B: 'not touch', C: 'to not touch', D: 'for touching' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc tường thuật cảnh báo: "warn someone against V-ing" (hoặc "warn someone not to V").',
    },

    // === 15 CÂU TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'In indirect questions, the question word order reverts to normal statement word order (Subject + Verb), and the question mark is omitted.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Câu hỏi gián tiếp không đảo trợ động từ lên trước chủ ngữ mà đưa về trật tự câu trần thuật (S + V) và kết thúc bằng dấu chấm.',
    },
    {
      id: 17,
      noiDung: 'When the reporting verb is in the Present Simple tense (e.g., "He says"), the tense of verbs in the reported clause must still be shifted back into the past.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Khi động từ tường thuật ở hiện tại (says, tells, asks), thì của động từ trong câu gián tiếp KHÔNG đổi.',
    },
    {
      id: 18,
      noiDung: 'The time expression "tomorrow" in direct speech changes to "the next day" or "the following day" in reported speech.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Tomorrow" chuyển thành "the following day", "the next day" hoặc "the day after".',
    },
    {
      id: 19,
      noiDung: 'In reported speech, modal verbs like "would", "could", "should", and "might" do not shift further into another tense form.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Các trợ động từ khuyết thiếu ở quá khứ (would, could, should, might, ought to) giữ nguyên dạng.',
    },
    {
      id: 20,
      noiDung: 'The pronoun "this" in direct speech always changes to "that" or "the" when referring to time or distant objects in reported speech.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Đại từ/chỉ từ "this" thường đổi thành "that" hoặc "the" tương ứng.',
    },
    {
      id: 21,
      noiDung: 'Direct imperative "Be quiet!" can be correctly reported as: He told us to be quiet.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Tường thuật câu mệnh lệnh khẳng định: "tell someone + to-infinitive".',
    },
    {
      id: 22,
      noiDung: 'Past Perfect tense ("had worked") in direct speech must be shifted back to an earlier tense form in reported speech.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Quá khứ hoàn thành là thì xa nhất trong quá khứ nên giữ nguyên dạng ("had worked"), không lùi thì tiếp.',
    },
    {
      id: 23,
      noiDung: 'The verb "tell" requires a personal object (e.g., "He told me that..."), whereas "say" cannot take an object without "to" (e.g., "He said to me that...").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Tell + O + (that)" còn "Say (+ to O) + (that)". Tuyệt đối không dùng "He said me".',
    },
    {
      id: 24,
      noiDung: 'When reporting general truths or scientific facts, verb backshifting is mandatory in formal English.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Chân lý hoặc sự thật khoa học vẫn được giữ nguyên ở thì hiện tại đơn, không bắt buộc lùi thì.',
    },
    {
      id: 25,
      noiDung: 'In Yes/No questions, we can use either "if" or "whether" interchangeably to introduce the reported clause.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Cả "if" và "whether" đều được sử dụng để giới thiệu mệnh đề trong câu hỏi Yes/No gián tiếp.',
    },
    {
      id: 26,
      noiDung: '"Here" in direct speech commonly becomes "there" in reported speech.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Trạng từ chỉ nơi chốn "here" chuyển thành "there" khi tường thuật gián tiếp.',
    },
    {
      id: 27,
      noiDung: 'The sentence: He asked me where was I going is grammatically standard reported speech.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Câu chuẩn phải là: "He asked me where I was going" (không đảo trợ động từ "was" trước chủ ngữ "I").',
    },
    {
      id: 28,
      noiDung: 'The reporting structure for offering help can be: "He offered to help me."',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Offer to do something" là cấu trúc chuẩn để tường thuật lời đề nghị giúp đỡ.',
    },
    {
      id: 29,
      noiDung: '"Yesterday" changes to "the day after" in reported speech.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Yesterday" đổi thành "the day before" hoặc "the previous day". "The day after" là của "tomorrow".',
    },
    {
      id: 30,
      noiDung: 'Reporting verbs such as "refuse", "agree", "promise", and "threaten" are commonly followed by a to-infinitive.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Các động từ refuse, agree, promise, threaten đi trực tiếp với to-V (ví dụ: promised to return soon).',
    },

    // === 15 CÂU MULTIPLE CHOICE (CHỌN NHIỀU ĐÁP ÁN) ===
    {
      id: 31,
      noiDung: 'Which of the following time and place adverbs undergo backshifting in reported speech? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Now -> Then',
        B: 'Today -> That day',
        C: 'Yesterday -> The previous day',
        D: 'Always -> Never',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C là các quy tắc biến đổi trạng từ thời gian chuẩn. "Always" là trạng từ chỉ tần suất, không đổi thành "never".',
    },
    {
      id: 32,
      noiDung: 'Which reporting verbs are followed by "someone + to-infinitive"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Advise',
        B: 'Remind',
        C: 'Suggest',
        D: 'Encourage',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Advise/Remind/Encourage + O + to V. Riêng "Suggest" đi với "V-ing" hoặc "that S + (should) + V", không dùng "suggest someone to V".',
    },
    {
      id: 33,
      noiDung: 'Which of the following sentences correctly report the question: "Why are you laughing?" (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'She asked me why I was laughing.',
        B: 'She inquired why I was laughing.',
        C: 'She asked why was I laughing.',
        D: 'She wondered why I was laughing.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Các câu A, B, D đều đúng trật tự từ (S + V) và sử dụng động từ tường thuật thích hợp. Câu C sai vì đảo trợ động từ "was".',
    },
    {
      id: 34,
      noiDung: 'Select ALL sentences that correctly transform direct speech into reported speech with correct tense shifting:',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: '"I want a coffee." -> He said he wanted a coffee.',
        B: '"I have booked the flight." -> She said she had booked the flight.',
        C: '"I will be there." -> Mark said he will be there.',
        D: '"I saw the accident." -> They said they had seen the accident.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A (hiện tại đơn -> quá khứ đơn), B (hiện tại hoàn thành -> quá khứ hoàn thành), D (quá khứ đơn -> quá khứ hoàn thành) đều lùi thì chính xác. C sai vì "will" chưa lùi về "would".',
    },
    {
      id: 35,
      noiDung: 'Which of the following reporting structures use preposition + V-ing? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Apologize for V-ing',
        B: 'Insist on V-ing',
        C: 'Promise to V-ing',
        D: 'Accuse someone of V-ing',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Apologize for, Insist on, Accuse someone of đều đi với V-ing. Promise đi với to-infinitive ("promise to do").',
    },
    {
      id: 36,
      noiDung: 'Which modal verbs do NOT change when moving from direct to reported speech? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Should',
        B: 'Might',
        C: 'Can',
        D: 'Ought to',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Should, might, ought to giữ nguyên. Riêng "can" phải chuyển thành "could".',
    },
    {
      id: 37,
      noiDung: 'Which of the following are grammatically correct reported commands or requests? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The police officer ordered the driver to step out of the car.',
        B: 'My mother reminded me to lock the front door.',
        C: 'He told me don\'t touch the wire.',
        D: 'She warned us not to walk alone at midnight.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D dùng to-V / not to-V chính xác. C sai vì phải dùng "not to touch", không dùng "don\'t touch".',
    },
    {
      id: 38,
      noiDung: 'Identify all sentences where backshifting is NOT strictly necessary because the statement remains true at the time of reporting:',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'C1',
      luaChon: {
        A: '"The Earth orbits the Sun," Galileo stated.',
        B: '"I am staying at the Hilton until next Sunday," said John (and it is still Friday).',
        C: '"I bought a car in 1990," said Tom.',
        D: '"Light travels faster than sound," the science tutor explained.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A và D là chân lý khoa học không đổi thì; B là sự việc vẫn đang tiếp tục có hiệu lực ở thời điểm nói. C là hành động quá khứ cụ thể nên cần lùi thì.',
    },
    {
      id: 39,
      noiDung: 'Which conjunctions can properly introduce an indirect Yes/No question? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'If',
        B: 'Whether',
        C: 'That',
        D: 'Unless',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: '"If" và "Whether" là hai liên từ dùng để mở đầu câu hỏi Yes/No gián tiếp.',
    },
    {
      id: 40,
      noiDung: 'Which sentences correctly report: "I will call you as soon as I arrive"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'She said she would call me as soon as she arrived.',
        B: 'She promised she would call me as soon as she arrived.',
        C: 'She promised to call me as soon as she arrived.',
        D: 'She said she will call me as soon as she arrives.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (câu tường thuật chuẩn), B (dùng promise that), C (dùng promise to-inf). D sai vì không lùi thì trong văn cảnh quá khứ.',
    },
    {
      id: 41,
      noiDung: 'Which verbs can be followed directly by a "that-clause" without a personal object? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Say',
        B: 'Explain',
        C: 'Tell',
        D: 'Claim',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Say that, Explain that, Claim that không cần tân ngữ chỉ người. "Tell" bắt buộc phải có tân ngữ: "tell someone that".',
    },
    {
      id: 42,
      noiDung: 'Which of the following demonstrate correct backshifting for past continuous: "I was cooking when you called"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'She said she had been cooking when I called.',
        B: 'She said she was cooking when I called.',
        C: 'She said she has been cooking when I called.',
        D: 'She said she had cooked when I called.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'Quá khứ tiếp diễn có thể lùi về Quá khứ hoàn thành tiếp diễn (A) hoặc giữ nguyên Quá khứ tiếp diễn (B) khi có mốc thời gian rõ ràng.',
    },
    {
      id: 43,
      noiDung: 'Select all correct transformations of: "Don\'t forget to send the attachment," Anna said to me.',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Anna reminded me to send the attachment.',
        B: 'Anna told me not to forget to send the attachment.',
        C: 'Anna suggested sending the attachment.',
        D: 'Anna warned me against sending the attachment.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: '"Don\'t forget to V" tương đương với "remind someone to V" (A) hoặc "tell someone not to forget" (B). C và D làm sai nghĩa gốc.',
    },
    {
      id: 44,
      noiDung: 'Which pronouns and possessives in: "I will lend you my textbook" must change when reported by Anna to Ben? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'I -> She',
        B: 'You -> Him',
        C: 'My -> Her',
        D: 'Textbook -> Book',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Anna nói với Ben nên đại từ "I" đổi thành "she", tân ngữ "you" đổi thành "him", tính từ sở hữu "my" đổi thành "her". Danh từ "textbook" giữ nguyên.',
    },
    {
      id: 45,
      noiDung: 'Which of the following indirect questions are punctuated and ordered correctly? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Could you tell me what time the train arrives?',
        B: 'He asked how much the registration fee was.',
        C: 'She inquired whether the library was open on Sundays.',
        D: 'They asked where was the nearest metro station?',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A là câu hỏi lịch sự gián tiếp (dấu chấm hỏi ở cuối theo mệnh đề chính "Could you tell me"). B và C là câu trần thuật tường thuật (kết thúc dấu chấm). D sai vì đảo "was" trước "the nearest station".',
    },
  ],
};
