import { CurriculumTopicBank } from './types';

export const SUBJECT_VERB_AGREEMENT_BANK: CurriculumTopicBank = {
  key: 'SUBJECT_VERB_AGREEMENT',
  tenChuDe: 'Sự Hòa Hợp Chủ Vị (Subject-Verb Agreement)',
  aliases: [
    'hòa hợp chủ vị',
    'hoa hop chu vi',
    'chủ vị',
    'chu vi',
    'subject verb',
    'subject-verb agreement',
    'su hoa hop chu vi',
    'chia động từ theo chủ ngữ',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'Neither the department manager nor his assistant __________ aware of the revised policy guidelines.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'is', B: 'are', C: 'were', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Quy tắc "Neither S1 nor S2": Động từ hòa hợp theo chủ ngữ gần nhất (S2 là "his assistant" số ít nên dùng "is").',
    },
    {
      id: 2,
      noiDung: 'The committee __________ divided in their opinions regarding the proposed annual budget cut.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'is', B: 'are', C: 'was', D: 'has been' },
      dapAnDung: 'B',
      giaiThich: 'Danh từ tập thể (committee, team, staff) khi các thành viên chia rẽ quan điểm hoặc hành động độc lập mang nghĩa số nhiều, dùng "are".',
    },
    {
      id: 3,
      noiDung: 'Each of the participants __________ awarded a commemorative medal upon completing the marathon.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'was', B: 'were', C: 'are', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc "Each of + danh từ số nhiều" luôn đi với động từ số ít ("was").',
    },
    {
      id: 4,
      noiDung: 'The number of international applicants to our language center __________ significantly this semester.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'has increased', B: 'have increased', C: 'are increasing', D: 'were increasing' },
      dapAnDung: 'A',
      giaiThich: '"The number of + danh từ số nhiều" luôn đi với động từ số ít ("has increased"). Ngược lại, "A number of" đi với động từ số nhiều.',
    },
    {
      id: 5,
      noiDung: 'Bread and butter __________ her favorite breakfast combination every single morning.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'is', B: 'are', C: 'were', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Hai danh từ nối bằng "and" nhưng cùng chỉ một món ăn hoặc một thể thống nhất thì động từ chia số ít ("is").',
    },
    {
      id: 6,
      noiDung: 'Ten thousand dollars __________ a substantial sum of money to invest in an early-stage startup.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'is', B: 'are', C: 'were', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Các danh từ chỉ số tiền, khoảng cách, thời gian, khối lượng được coi là một đơn vị tổng thể nên đi với động từ số ít ("is").',
    },
    {
      id: 7,
      noiDung: 'The professor, along with three laboratory assistants, __________ conducting fieldwork in the Amazon basin.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'is', B: 'are', C: 'were', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Khi chủ ngữ nối với các từ như "along with", "together with", "as well as", động từ chia theo chủ ngữ đầu tiên ("The professor" số ít -> "is").',
    },
    {
      id: 8,
      noiDung: 'Physics __________ always been his most captivating academic subject at high school.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'has', B: 'have', C: 'are', D: 'were' },
      dapAnDung: 'A',
      giaiThich: 'Tên các môn học tận cùng bằng "-s" (Physics, Mathematics, Economics, Politics) là danh từ số ít, đi với "has".',
    },
    {
      id: 9,
      noiDung: 'Every boy and girl in the school choir __________ given a personalized sheet music folder.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'was', B: 'were', C: 'are', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Chủ ngữ bắt đầu bằng "Every" hoặc "Each" dù có nối bằng "and" vẫn luôn chia động từ ở số ít ("was").',
    },
    {
      id: 10,
      noiDung: 'A pair of leather boots __________ left near the entrance hallway.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A1',
      luaChon: { A: 'was', B: 'were', C: 'are', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Chủ ngữ là "A pair of" (một đôi) là số ít nên động từ chia số ít ("was").',
    },
    {
      id: 11,
      noiDung: 'A large percentage of the harvested crops __________ destroyed by the unseasonal frost.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'was', B: 'were', C: 'is', D: 'has' },
      dapAnDung: 'B',
      giaiThich: 'Cấu trúc "percentage / fraction of + N": động từ chia theo danh từ đứng sau ("crops" số nhiều đếm được -> "were destroyed").',
    },
    {
      id: 12,
      noiDung: 'Not only the coach but also all the soccer players __________ thrilled by the championship victory.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'were', B: 'was', C: 'is', D: 'has been' },
      dapAnDung: 'A',
      giaiThich: 'Cấu trúc "Not only S1 but also S2": động từ chia theo chủ ngữ gần nhất (S2 là "all the soccer players" số nhiều -> "were").',
    },
    {
      id: 13,
      noiDung: 'The elderly __________ special care, respect, and accessible public facilities in every society.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'deserve', B: 'deserves', C: 'is deserving', D: 'has deserved' },
      dapAnDung: 'A',
      giaiThich: '"The + tính từ" chỉ một tập hợp người (The elderly, the poor, the rich) đóng vai trò chủ ngữ số nhiều, chia động từ nguyên mẫu ("deserve").',
    },
    {
      id: 14,
      noiDung: 'There __________ a comprehensive dictionary and three notebooks on the study desk.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'is', B: 'are', C: 'were', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Với cấu trúc "There is / There are", động từ chia theo danh từ đầu tiên ngay sau nó ("a comprehensive dictionary" số ít -> "is").',
    },
    {
      id: 15,
      noiDung: 'Measles __________ an infectious viral illness that primarily affects young children.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'is', B: 'are', C: 'were', D: 'have been' },
      dapAnDung: 'A',
      giaiThich: 'Tên các căn bệnh tận cùng bằng "-s" (Measles, Mumps, Rabies, Diabetes) là danh từ số ít, đi với "is".',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'The expression "A number of students" takes a plural verb, whereas "The number of students" takes a singular verb.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "A number of + N(số nhiều)" đi với động từ số nhiều; "The number of + N(số nhiều)" đi với động từ số ít.',
    },
    {
      id: 17,
      noiDung: 'Titles of books, films, and artistic works ending in plural nouns always take plural verbs (e.g., "The Chronicles of Narnia are a book").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Tên một tác phẩm nghệ thuật, sách báo hay bộ phim luôn được coi là một thực thể số ít (phải dùng "The Chronicles of Narnia IS a book").',
    },
    {
      id: 18,
      noiDung: 'Indefinite pronouns such as "everyone", "someone", "nobody", and "anything" take singular verbs.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Các đại từ bất định kết thúc bằng -one, -body, -thing luôn đi kèm động từ số ít.',
    },
    {
      id: 19,
      noiDung: 'When subjects are joined by "either... or" or "neither... nor", the verb agrees with the subject closest to it.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Quy tắc tiệm cận (proximity rule): động từ chia theo chủ ngữ gần nó nhất.',
    },
    {
      id: 20,
      noiDung: 'Nouns indicating periods of time, monetary sums, or physical distances take singular verbs when thought of as a single whole quantity.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Thời gian (two hours), tiền bạc (50 dollars), khoảng cách (10 miles) khi là một đại lượng thống nhất luôn đi với động từ số ít.',
    },
    {
      id: 21,
      noiDung: 'The word "news" is plural in form and therefore always takes a plural verb in standard English.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "News" (tin tức) là danh từ không đếm được và luôn đi với động từ số ít (The news is good).',
    },
    {
      id: 22,
      noiDung: 'When a subject is modified by parenthetical expressions like "as well as" or "together with", the verb agrees with the main first subject.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Các cụm từ chèn thêm (as well as, accompanied by, together with) không làm thay đổi số của chủ ngữ chính đứng trước.',
    },
    {
      id: 23,
      noiDung: 'The plural noun "police" takes a singular verb (e.g., "The police is investigating").',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Police", "cattle", "people" là các danh từ tập hợp luôn luôn đi với động từ số nhiều ("The police ARE investigating").',
    },
    {
      id: 24,
      noiDung: 'In expressions like "one of the students who...", the verb inside the relative clause typically agrees with the plural noun "students".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "One of the students who have passed..." (who thay thế cho students số nhiều). Tuy nhiên nếu có "the only one of..." thì chia số ít.',
    },
    {
      id: 25,
      noiDung: 'Nouns that consist of two symmetrical parts, such as "scissors", "glasses", and "trousers", take plural verbs.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Scissors, glasses, pants, trousers đi với động từ số nhiều, trừ khi đứng sau "a pair of".',
    },
    {
      id: 26,
      noiDung: 'The phrase "More than one student" takes a plural verb because it represents multiple people.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Quy tắc ngữ pháp đặc biệt: "More than one + N(số ít)" luôn đi với động từ số ít ("More than one student HAS failed").',
    },
    {
      id: 27,
      noiDung: 'Gerund phrases functioning as subjects (e.g., "Swimming in cold oceans") take a singular verb.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Danh động từ (V-ing) làm chủ ngữ luôn luôn đi với động từ số ít.',
    },
    {
      id: 28,
      noiDung: 'Inverted sentences beginning with "Here" or "There" determine verb number based on the subject that follows the verb.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Động từ sau Here/There hòa hợp theo danh từ đứng ngay sau nó (There is a book / There are three books).',
    },
    {
      id: 29,
      noiDung: 'Fractional and percentage expressions take singular or plural verbs depending on whether the noun following "of" is singular/uncountable or plural.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Ví dụ: "Half of the cake IS gone", nhưng "Half of the students ARE absent".',
    },
    {
      id: 30,
      noiDung: 'The subject "None" must always and strictly take a singular verb in all registers of modern English.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "None of + N(số nhiều)" có thể đi với động từ số ít (trong văn phong cực kỳ trang trọng) hoặc động từ số nhiều (rất phổ biến trong văn phong chuẩn hiện đại).',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which nouns take a SINGULAR verb despite ending in the letter "-s"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'News (tin tức)',
        B: 'Mathematics (môn toán)',
        C: 'Economics (môn kinh tế học)',
        D: 'Scissors (cái kéo)',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'News, Mathematics, Economics chia số ít. "Scissors" có 2 lưỡi kéo đối xứng nên chia số nhiều.',
    },
    {
      id: 32,
      noiDung: 'Which sentences demonstrate correct subject-verb agreement? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'A number of students have registered for the seminar.',
        B: 'The number of participants is thirty.',
        C: 'A number of students has registered for the seminar.',
        D: 'Every student has a textbook.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A đúng (A number of + plural verb). B đúng (The number of + singular verb). D đúng (Every + singular). C sai vì A number of phải đi số nhiều.',
    },
    {
      id: 33,
      noiDung: 'Which indefinite pronouns always take a SINGULAR verb? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Everyone',
        B: 'Nobody',
        C: 'Each',
        D: 'Both',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Everyone, Nobody, Each luôn chia số ít. "Both" (cả hai) luôn chia số nhiều.',
    },
    {
      id: 34,
      noiDung: 'Select all sentences where the collective noun correctly takes a PLURAL verb: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The jury were unable to agree on a unanimous verdict.',
        B: 'The staff are arguing among themselves about the new schedule.',
        C: 'The herd of cattle is grazing peacefully on the hill.',
        D: 'The team are putting on their individual training jerseys.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Khi các thành viên trong tập thể hành động độc lập hoặc chia rẽ quan điểm (A, B, D), động từ chia số nhiều. C coi cả đàn bò là một khối duy nhất.',
    },
    {
      id: 35,
      noiDung: 'Which sentences illustrate correct agreement with subjects joined by coordinating conjunctions? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Either my parents or my brother is picking me up.',
        B: 'Neither the manager nor the employees were informed.',
        C: 'Not only John but also his sisters love classical music.',
        D: 'Either my brother or my parents is coming.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C tuân thủ quy tắc chia động từ theo chủ ngữ gần nhất. D sai vì "parents" là số nhiều thì động từ phải là "are coming".',
    },
    {
      id: 36,
      noiDung: 'Which plural-looking nouns take a PLURAL verb? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Trousers (quần dài)',
        B: 'Binoculars (ống nhòm)',
        C: 'Mumps (bệnh quai bị)',
        D: 'Police (lực lượng cảnh sát)',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Trousers, Binoculars, Police luôn chia số nhiều. Mumps là tên bệnh nên chia số ít.',
    },
    {
      id: 37,
      noiDung: 'Select all sentences with subject-verb agreement errors: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The quality of these handmade products are exceptional.',
        B: 'Ten miles are too far to walk in one afternoon.',
        C: 'Reading books expands your intellectual horizon.',
        D: 'The captain, together with his crew members, was commended.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A sai (chủ ngữ là "The quality" số ít nên phải dùng "is exceptional"). B sai (khoảng cách 10 miles dùng "is too far"). C và D đúng.',
    },
    {
      id: 38,
      noiDung: 'Which of the following take a PLURAL verb when used as the subject? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The homeless (người vô gia cư nói chung)',
        B: 'Cattle (đàn gia súc)',
        C: 'Both of the proposals',
        D: 'Every student and teacher',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'The + Adj, Cattle, Both of đều đi với động từ số nhiều. "Every..." luôn đi với số ít.',
    },
    {
      id: 39,
      noiDung: 'Which sentences correctly match verbs with "there is / there are"? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'There is a sofa and two armchairs in the living room.',
        B: 'There are two armchairs and a sofa in the living room.',
        C: 'There are a sofa and two armchairs in the living room.',
        D: 'There is plenty of fresh milk in the refrigerator.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A đúng ("a sofa" số ít đứng đầu). B đúng ("two armchairs" số nhiều đứng đầu). D đúng ("plenty of milk" không đếm được). C sai vì danh từ đầu tiên là "a sofa" số ít.',
    },
    {
      id: 40,
      noiDung: 'Select all sentences where percentage or fraction expressions agree correctly: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Two-thirds of the cake has been eaten.',
        B: 'Two-thirds of the candidates have passed the examination.',
        C: 'Forty percent of the forest was lost in the wildfire.',
        D: 'Forty percent of the trees was lost in the wildfire.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (cake không đếm được -> has), B (candidates số nhiều -> have), C (forest số ít -> was). D sai vì "trees" số nhiều phải dùng "were lost".',
    },
    {
      id: 41,
      noiDung: 'Which sentences correctly use "one of the..." constructions? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'C1',
      luaChon: {
        A: 'She is one of those dedicated doctors who work tirelessly for patients.',
        B: 'She is the only one of the applicants who has international experience.',
        C: 'One of the laptops is broken.',
        D: 'One of the laptops are broken.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A đúng ("who work" bổ nghĩa cho doctors). B đúng ("the only one... who has"). C đúng ("One of the laptops is"). D sai.',
    },
    {
      id: 42,
      noiDung: 'Which subjects represent compound concepts treated as singular? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Fish and chips is a classic British culinary dish.',
        B: 'Law and order is essential for a peaceful civil society.',
        C: 'Time and tide waits for no man.',
        D: 'Cats and dogs are common domestic pets.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A, B, C là các cặp danh từ nối bằng "and" nhưng biểu thị một khái niệm/món ăn thống nhất nên chia số ít. D là hai loài động vật riêng biệt chia số nhiều.',
    },
    {
      id: 43,
      noiDung: 'Select all sentences correctly using "more than one": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'More than one researcher has verified the experimental findings.',
        B: 'More than one attendee was surprised by the unexpected announcement.',
        C: 'More than one researcher have verified the findings.',
        D: 'More students than one were absent.',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A và B tuân thủ "More than one + N(số ít) + V(số ít)". D đúng vì chủ ngữ "More students than one" chia theo students số nhiều. C sai.',
    },
    {
      id: 44,
      noiDung: 'Which sentences demonstrate correct agreement with introductory parentheticals? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'The prime minister, accompanied by three ministers, has arrived.',
        B: 'The singer, along with her backing dancers, is rehearsing.',
        C: 'The prime minister, accompanied by three ministers, have arrived.',
        D: 'The singer, along with her dancers, are rehearsing.',
      },
      dapAnDung: ['A', 'B'],
      giaiThich: 'A và B chia theo chủ ngữ chính đầu tiên (The prime minister -> has, The singer -> is). C và D sai.',
    },
    {
      id: 45,
      noiDung: 'Which of the following relative pronoun clauses have correct subject-verb agreement? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'The book that contains rare historical maps is kept in a glass vault.',
        B: 'The books that contain rare historical maps are kept in a glass vault.',
        C: 'The manager who supervises thirty engineers works late every day.',
        D: 'The manager who supervise thirty engineers works late every day.',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'A (book -> contains), B (books -> contain), C (manager -> supervises). D sai vì "manager" số ít thì động từ trong mệnh đề quan hệ phải có "-s".',
    },
  ],
};
