import { CurriculumTopicBank } from './types';

export const TOURISM_TRAVEL_BANK: CurriculumTopicBank = {
  key: 'TOURISM_TRAVEL',
  tenChuDe: 'Từ Vựng Du Lịch, Khách Sạn & Khám Phá (Travel & Tourism)',
  aliases: [
    'du lịch',
    'du lich',
    'travel',
    'tourism',
    'khách sạn',
    'khach san',
    'hotel',
    'resort',
    'sân bay',
    'san bay',
    'airport',
    'flight',
    'chuyến bay',
    'kỳ nghỉ',
    'ky nghi',
    'vacation',
    'holiday',
    'khám phá',
    'kham pha',
    'tourist',
    'booking',
    'check in',
  ],
  questions: [
    // === 15 SINGLE CHOICE ===
    {
      id: 1,
      noiDung: 'Passengers must proceed directly to Departure Gate 14 as soon as the flight announces final __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'boarding', B: 'landing', C: 'parking', D: 'braking' },
      dapAnDung: 'A',
      giaiThich: '"Boarding" là quá trình hành khách bước lên máy bay (final boarding: lượt gọi lên máy bay cuối cùng).',
    },
    {
      id: 2,
      noiDung: 'A detailed travel __________ was emailed to all participants outlining daily sightseeing destinations and transport.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'itinerary', B: 'receipt', C: 'brochure', D: 'recipe' },
      dapAnDung: 'A',
      giaiThich: '"Itinerary" là lịch trình chi tiết của một chuyến du lịch.',
    },
    {
      id: 3,
      noiDung: 'The seaside boutique resort offers luxurious ocean-view __________ equipped with private balconies.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'suites', B: 'suits', C: 'camps', D: 'huts' },
      dapAnDung: 'A',
      giaiThich: '"Suite" (phòng khách sạn cao cấp gồm nhiều không gian tiện nghi).',
    },
    {
      id: 4,
      noiDung: 'Due to severe technical malfunctions, the international flight had to make an emergency __________ in Athens.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'landing', B: 'takeoff', C: 'boarding', D: 'cruising' },
      dapAnDung: 'A',
      giaiThich: '"Emergency landing" nghĩa là hạ cánh khẩn cấp.',
    },
    {
      id: 5,
      noiDung: 'Ecotourism aims to preserve natural habitats while providing economic opportunities for __________ communities.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'indigenous', B: 'artificial', C: 'industrial', D: 'synthetic' },
      dapAnDung: 'A',
      giaiThich: '"Indigenous communities" nghĩa là các cộng đồng dân cư bản địa/địa phương.',
    },
    {
      id: 6,
      noiDung: 'Before departing on an international trek, make sure your passport has at least six months of remaining __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'validity', B: 'ability', C: 'quantity', D: 'capacity' },
      dapAnDung: 'A',
      giaiThich: '"Validity" nghĩa là hiệu lực (hộ chiếu còn thời hạn hiệu lực tối thiểu 6 tháng).',
    },
    {
      id: 7,
      noiDung: 'We requested a late __________ at 2:00 PM because our return flight was scheduled for late evening.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'checkout', B: 'checkin', C: 'breakout', D: 'takeout' },
      dapAnDung: 'A',
      giaiThich: '"Late checkout" là dịch vụ trả phòng khách sạn trễ hơn giờ quy định.',
    },
    {
      id: 8,
      noiDung: 'The mountain pass offers breathtaking panoramic __________ of the alpine valley below.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'views', B: 'looks', C: 'glances', D: 'stares' },
      dapAnDung: 'A',
      giaiThich: '"Panoramic views" nghĩa là góc nhìn toàn cảnh hùng vĩ.',
    },
    {
      id: 9,
      noiDung: 'A valid transit __________ is required for citizens of certain nations during international layovers.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'visa', B: 'license', C: 'diploma', D: 'bill' },
      dapAnDung: 'A',
      giaiThich: '"Transit visa" (thị thực quá cảnh tại sân bay trung gian).',
    },
    {
      id: 10,
      noiDung: 'The hotel concierge was extremely helpful, offering personalized __________ for authentic local seafood bistros.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'recommendations', B: 'accusations', C: 'prohibitions', D: 'penalties' },
      dapAnDung: 'A',
      giaiThich: '"Recommendations" (những lời gợi ý/khuyến nghị hữu ích).',
    },
    {
      id: 11,
      noiDung: 'All international travelers arriving at the border checkpoint must pass through customs and __________ control.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'immigration', B: 'emigration', C: 'admission', D: 'emission' },
      dapAnDung: 'A',
      giaiThich: '"Immigration control" (quầy kiểm soát nhập cảnh tại cửa khẩu sân bay).',
    },
    {
      id: 12,
      noiDung: 'Booking flight tickets during the __________ season usually guarantees significant fare discounts and fewer crowds.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B2',
      luaChon: { A: 'off-peak', B: 'peak', C: 'high', D: 'rush' },
      dapAnDung: 'A',
      giaiThich: '"Off-peak season" nghĩa là mùa thấp điểm du lịch.',
    },
    {
      id: 13,
      noiDung: 'The airline policy states that every passenger is permitted one piece of carry-on __________ weighing up to 7 kg.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'luggage', B: 'luggages', C: 'baggages', D: 'cargoes' },
      dapAnDung: 'A',
      giaiThich: '"Luggage" là danh từ không đếm được, không thêm số nhiều "-s".',
    },
    {
      id: 14,
      noiDung: 'The cruise ship docked at the historic harbor, giving tourists eight hours of leisure for independent __________.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'B1',
      luaChon: { A: 'exploration', B: 'explosion', C: 'exposure', D: 'extinction' },
      dapAnDung: 'A',
      giaiThich: '"Exploration" nghĩa là sự khám phá, trải nghiệm.',
    },
    {
      id: 15,
      noiDung: 'A __________ flight flies directly to the destination without any intermediate stops or airport changes.',
      loaiCauHoi: 'SINGLE',
      trinhDo: 'A2',
      luaChon: { A: 'non-stop', B: 'layover', C: 'connecting', D: 'chartered' },
      dapAnDung: 'A',
      giaiThich: '"Non-stop flight" là chuyến bay thẳng không quá cảnh hay đổi máy bay.',
    },

    // === 15 TRUE / FALSE ===
    {
      id: 16,
      noiDung: 'A "layover" refers to a brief stopover or waiting period between connecting flights at an intermediate airport.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Layover là khoảng thời gian dừng nghỉ/quá cảnh giữa 2 chặng bay nối chuyến.',
    },
    {
      id: 17,
      noiDung: 'The noun "luggage" is plural and can be used in the form "three luggages".',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Luggage" là danh từ không đếm được; muốn đếm ta phải dùng "three pieces of luggage".',
    },
    {
      id: 18,
      noiDung: 'A hotel concierge is responsible for assisting guests with bookings, city excursions, and local transport.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Nhân viên Concierge chuyên hỗ trợ thông tin, đặt bàn, tour du lịch cho khách lưu trú.',
    },
    {
      id: 19,
      noiDung: 'Duty-free shops at international airports sell merchandise exempt from local national sales taxes and import tariffs.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Cửa hàng miễn thuế (Duty-free) bán hàng hóa được miễn thuế xuất nhập khẩu và thuế tiêu thụ đặc biệt.',
    },
    {
      id: 20,
      noiDung: 'Overbooking is an uncommon practice where airlines strictly sell fewer tickets than actual available seats.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. "Overbooking" là việc hãng hàng không bán VƯỢT QUÁ số ghế thực tế vì dự trù có hành khách bỏ vé.',
    },
    {
      id: 21,
      noiDung: 'A hostel typically provides budget shared dormitory rooms with communal facilities for backpackers.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Hostel (nhà trọ du lịch) có phòng ngủ tập thể giường tầng giá rẻ cho dân du lịch bụi.',
    },
    {
      id: 22,
      noiDung: 'Jet lag is a temporary sleep disruption caused by crossing multiple geographical time zones rapidly via air travel.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Jet lag là hội chứng mệt mỏi do lệch múi giờ sinh học khi bay đường dài.',
    },
    {
      id: 23,
      noiDung: 'All-inclusive resorts charge separate extra fees for every regular breakfast, lunch, and dinner meal.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Khu nghỉ dưỡng "All-inclusive" (trọn gói) đã bao gồm tiền phòng, toàn bộ các bữa ăn và đồ uống.',
    },
    {
      id: 24,
      noiDung: 'A round-trip ticket provides transportation to a destination and back to the original point of departure.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Vé khứ hồi (Round-trip ticket) bao gồm cả lượt đi và lượt về.',
    },
    {
      id: 25,
      noiDung: 'Excess baggage charges are applied when passenger luggage exceeds the complimentary airline weight limit.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Phí hành lý quá cước (Excess baggage charge) phát sinh khi hành lý vượt quá số cân nặng miễn cước.',
    },
    {
      id: 26,
      noiDung: 'The term "sightseeing" refers to touring around visiting famous historic monuments and natural attractions.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Sightseeing" là hoạt động đi tham quan các danh lam thắng cảnh.',
    },
    {
      id: 27,
      noiDung: 'A boarding pass is issued at the departure gate only after the airplane has reached its final destination.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A1',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'B',
      giaiThich: 'Sai. Thẻ lên máy bay (Boarding pass) được cấp khi làm thủ tục check-in TRƯỚC khi lên máy bay.',
    },
    {
      id: 28,
      noiDung: 'Sustainable tourism minimizes environmental degradation and protects cultural authenticity of host nations.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Du lịch bền vững đề cao bảo vệ môi trường sinh thái và tôn trọng bản sắc văn hóa địa phương.',
    },
    {
      id: 29,
      noiDung: 'A "red-eye flight" is a flight scheduled to depart late at night and arrive early the following morning.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'B2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. "Red-eye flight" (chuyến bay đêm) bay xuyên đêm khiến hành khách dễ mỏi mắt thiếu ngủ.',
    },
    {
      id: 30,
      noiDung: 'Baggage carousel is the rotating conveyor belt where arriving passengers retrieve their checked luggage.',
      loaiCauHoi: 'TRUE_FALSE',
      trinhDo: 'A2',
      luaChon: { A: 'True (Đúng)', B: 'False (Sai)' },
      dapAnDung: 'A',
      giaiThich: 'Đúng. Băng chuyền hành lý (Baggage carousel) tại khu vực nhận hành lý đến của sân bay.',
    },

    // === 15 MULTIPLE CHOICE ===
    {
      id: 31,
      noiDung: 'Which travel documents are commonly mandatory when traveling internationally? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Valid passport',
        B: 'Entry visa (if required by destination country)',
        C: 'Gym membership card',
        D: 'Boarding pass',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Hộ chiếu, thị thực nhập cảnh và thẻ lên máy bay là các giấy tờ du lịch quốc tế bắt buộc. Thẻ tập gym không có giá trị xuất nhập cảnh.',
    },
    {
      id: 32,
      noiDung: 'Which amenities are commonly expected in a standard hotel room? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Complimentary Wi-Fi',
        B: 'En-suite bathroom with toiletries',
        C: 'Air conditioning',
        D: 'Commercial jet engine',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Wi-Fi, phòng tắm khép kín và điều hòa là các tiện nghi phòng khách sạn tiêu chuẩn.',
    },
    {
      id: 33,
      noiDung: 'Which activities describe responsible ecotourism practices? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Carrying reusable water bottles and avoiding single-use plastics',
        B: 'Purchasing locally made artisanal handicrafts to support host families',
        C: 'Carving personal names onto ancient coral reefs or historic monuments',
        D: 'Staying on designated hiking trails to prevent soil erosion',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'A, B, D là các hành động du lịch sinh thái có trách nhiệm. C là hành vi phá hoại di sản.',
    },
    {
      id: 34,
      noiDung: 'Which terms specify seat preferences inside commercial passenger aircraft? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Window seat',
        B: 'Aisle seat',
        C: 'Middle seat',
        D: 'Roof rack seat',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Window (ghế cạnh cửa sổ), Aisle (ghế cạnh lối đi), Middle (ghế ở giữa). Máy bay không có ghế trên nóc.',
    },
    {
      id: 35,
      noiDung: 'Select all forms of budget-friendly traveler accommodation: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Youth hostel',
        B: 'Guesthouse / Homestay',
        C: 'Presidential penthouse suite',
        D: 'Campsite',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Hostel, Homestay, Campsite là các loại hình lưu trú tiết kiệm. Penthouse là phòng siêu sang đắt đỏ.',
    },
    {
      id: 36,
      noiDung: 'Which announcements are typically heard inside an airport terminal? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Flight gate change notification',
        B: 'Final boarding call for a departing flight',
        C: 'Weather forecast for cooking soup',
        D: 'Unattended baggage security reminder',
      },
      dapAnDung: ['A', 'B', 'D'],
      giaiThich: 'Đổi cửa khởi hành (A), lượt lên tàu cuối cùng (B) và cảnh báo hành lý vô chủ (D) là các thông báo sân bay quen thuộc.',
    },
    {
      id: 37,
      noiDung: 'Which items are strictly regulated or prohibited in carry-on cabin baggage? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Flammable aerosol spray cans',
        B: 'Sharp cutting scissors exceeding permitted length',
        C: 'Bottles of liquid exceeding 100 ml outside security checkpoints',
        D: 'A paperback novel',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Bình xịt dễ cháy, kéo sắc nhọn và chất lỏng > 100ml bị cấm/hạn chế trong hành lý xách tay.',
    },
    {
      id: 38,
      noiDung: 'Select all compound nouns relating to travel and hospitality: (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Boarding pass',
        B: 'Travel agency',
        C: 'Package holiday',
        D: 'Gravity field',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Boarding pass (thẻ lên máy bay), Travel agency (công ty du lịch), Package holiday (kỳ nghỉ trọn gói) là danh từ ghép ngành du lịch.',
    },
    {
      id: 39,
      noiDung: 'Which factors contribute to causing jet lag for long-haul passengers? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Crossing multiple time zones in a short duration',
        B: 'Disruption of the body\'s natural circadian rhythm',
        C: 'Dehydration and dry cabin air during prolonged flights',
        D: 'The color of the airplane wings',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Vượt nhiều múi giờ, rối loạn nhịp sinh học và không khí khô thiếu nước gây ra hiện tượng jet lag.',
    },
    {
      id: 40,
      noiDung: 'Which phrases describe different modes of transport for travelers? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A1',
      luaChon: {
        A: 'By public transit bus',
        B: 'On foot (đi bộ)',
        C: 'By high-speed bullet train',
        D: 'By thinking mentally',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Xe bus công cộng, đi bộ, tàu cao tốc là các phương thức di chuyển du lịch.',
    },
    {
      id: 41,
      noiDung: 'Which benefits are offered by comprehensive international travel insurance? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Emergency overseas medical and hospital treatment coverage',
        B: 'Compensation for lost or stolen checked luggage',
        C: 'Reimbursement for unexpected flight cancellations due to illness',
        D: 'Free luxury shopping at all international boutiques',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Bảo hiểm du lịch chi trả chi phí y tế khẩn cấp, hành lý thất lạc và hủy chuyến bay bất khả kháng.',
    },
    {
      id: 42,
      noiDung: 'Select all verbs that commonly collocate with "flight": (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Book a flight',
        B: 'Board a flight',
        C: 'Miss a flight',
        D: 'Bake a flight',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Book (đặt), Board (lên), Miss (lỡ) chuyến bay là các cụm từ kết hợp chuẩn.',
    },
    {
      id: 43,
      noiDung: 'Which of the following are tourist attractions categorized as World Heritage Sites? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B1',
      luaChon: {
        A: 'Ha Long Bay (Vietnam)',
        B: 'Machu Picchu (Peru)',
        C: 'Angkor Wat (Cambodia)',
        D: 'A local neighborhood supermarket parking lot',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Vịnh Hạ Long, Machu Picchu và Angkor Wat là các Di sản Thế giới được UNESCO công nhận.',
    },
    {
      id: 44,
      noiDung: 'Which actions should a traveler take upon arriving at a hotel reception? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'A2',
      luaChon: {
        A: 'Present government identification or passport',
        B: 'Provide the booking confirmation voucher',
        C: 'Receive the room electronic keycard',
        D: 'Demand ownership of the hotel real estate',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Xuất trình hộ chiếu/CCCD (A), mã đặt phòng (B) và nhận thẻ phòng (C) là quy trình check-in chuẩn.',
    },
    {
      id: 45,
      noiDung: 'Which types of tourism focus on cultural immersion and local traditions? (Chọn tất cả đáp án đúng)',
      loaiCauHoi: 'MULTIPLE',
      trinhDo: 'B2',
      luaChon: {
        A: 'Heritage tourism',
        B: 'Culinary and gastronomic tourism',
        C: 'Community-based rural homestay tourism',
        D: 'Heavy metal industrial smelting inspection',
      },
      dapAnDung: ['A', 'B', 'C'],
      giaiThich: 'Du lịch di sản, du lịch ẩm thực và du lịch cộng đồng trải nghiệm văn hóa bản địa.',
    },
  ],
};
